---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: valkey-tls
spec:
  secretName: valkey-tls
  commonName: valkey.database.svc.cluster.local
  dnsNames:
    - valkey
    - valkey.database.svc
    - valkey.database.svc.cluster.local
  privateKey:
    algorithm: ECDSA
    size: 384
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
