apiVersion: v1
kind: Secret
metadata:
  name: valkey-acl
type: Opaque
stringData:
  users.acl: ENC[AES256_GCM,data:Sjc2l/mDSyvXA1xzBAuCeIdM7f1NjrVHAjXel8bM3MNsN1zn8HOHaEaLmB3ePFNY+7smYL6XEjMmUipyYOZT/zC1TQNfm2tFwhJfPJEP2FvLH6SON71bv7OvoD7L3KNwi5WiEApmaXDGSlhdcn5NLlqHbt8LKh1bWqiC9H1rXHlXSwd2A/ySGo1+y86s1/M5mQ2L4XONAXZCL1pSouEtQ1NMdU8w5yRc2AKlkkpdsewpvkK4j6KCiIq+E2k0HwYsG6mcKPRqk4VoiYXgVcBEoWjOtAaIlq3IecSanY7cY+XRvmOvE1LRPWUlWxBOKkcLSWzxP/nPZdh+vP1yIPWGwDiVfnCPg2EpkGzVvwhRmUOHyZ3ybp2zB3ePfTY6Zxamprp9qJWWLWYwnfPOa3C0sbJTqkT0G1T6JQpT0oaBAAsx+WYB8tUpVA74drAccMh0whkAF7osTCfWlHNoCAtDQoVOeJAPhSKNoTXd4QE4CiV9mZ0Gi88YOF+pUVka3EQzV8SvAuUSlL3//05hm3i8GzSyTVFEMSiInmEGB87if0yLDC48RWRjf31hiV457xVcsasE+7LWLeBwTRvabWK1/1a9cMxgfXwESw4xtMpmSiXEHk7kYC+Jm0PFp9W9DYtS9Lr1D6JKV46RJ8xaDnUZVX1KPtgGFi7XMpIvMRtWb68RVUn8YsFCpUSEoVqfkva+v+OFMwIKj75xlo7LeicsuyFU9tIl+d8HtuECtbTaFUu1Yfbirva6,iv:H+Nlf5e9Q4vi4wJeatSrc/MnwZpHH0KqrGhl241Q4EQ=,tag:SmKwCvq+IRQT1y4i44lgdA==,type:str]
  metricsPassword: ENC[AES256_GCM,data:uawvRNRAqc/lSKzSa8m3fHsmCPyyvlIexnrCNWVUax1WYWJJvTNVhFNuWpbKK5AbiWIJe8hg0Fr4gUhbZEPT9Q==,iv:bX7wRvDymrTKlYs/dw8UVT3TcGwQkHQKZoy36+mGTAE=,tag:e6tfupEOrKkVIZvDcSm/ZQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaN0swaXNoTlhUYzk5VVJt
        WjBGbzZaTVZWdzEvK0l3S2VZckZxQk1iSVVnCnZwd0JHWHh2LzhNWHZkVzgwa2lQ
        dWY3blhYUkphZ09pUzJ3MGdwMWJLUE0KLS0tIHd1aU1QaDV5OGJPSktHVUE2bkFh
        OGo5ZmpwanlseEVXbEhOTm1NemxVSEEKNWlOKbZaSVqJzUCDcc7LHyCiu83tgSqE
        xCJemzpzpO6MH+xgk+jpBxB9GtVsMW8vh+L0cmA42HhyhuCJ3Mpunw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-08T05:45:04Z"
  mac: ENC[AES256_GCM,data:L5DtqQJf6FqOm188nFZGxf+PCqRqZzNaf+hva0KY2PyN2KOAHrY/VWcHE+ztbo3Dq/oDG5LXk757R+FkUEoUx8DZKFe4mMptnQ0d8FbDHRGn2NS/EPpxIJ+GDBsd5NYYmb2p7hgG3Jt1o31dxIJL4NghZWJsNX2q/btomR+C/qM=,iv:Oq33CBhCDRIGMgV5J6CuSPxZ542zslk0C2ale5MZ3dk=,tag:9ZY1tKrqKo/gpEQYDbtvGA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
