apiVersion: v1
kind: Secret
metadata:
  name: valkey-acl
type: Opaque
stringData:
  users.acl: ENC[AES256_GCM,data:ocyOxUNZkI5FEQec+jdc/tEK8YqUko2AUnl2mNQW/WH3J5iapo5jk73z2RcA97vJBpzGn17vy3Xi2Kc9ip+DbiRyaPIHWohDvymCqJlAYK9b/Nvxd7/W2DuVttWRoAisgFxaE655e51N06M7EB/bvoeApYOeIFJcBedEGC9T0t9/dcVH+KKT14uZu0gYoL9MVmDlMcLaEAaZFTWRM91jf6Y6g6L52ExKFIta826OxUeoGhzqMSJpGYUmaXwhYeim+qxjoVezRSsxvrG8hcMfDeXB/kikhez8CPjJCY+GMoXj0et5bQSZTDrlUsySghew+JCqW5qbHm8m2akJyRdcF12hi2nA15Mkqj1DB275DTWtL/iiYd99rWRvN1XpSTH0gIeGhVd7EE+KWc0WjJ1B1Fpzjn+n+ghcLZ2B/ORGok2Lj2YqSa27je02dA3qrmdT/WDU2segFaLCjyRjY6kG6Yp9mdYplidMmonA9ubkxELnIwZCmiIuRg1YP6tNN9fpoUfwPootETeIml0w5uicYlcQdghYe32D0CTKogNGQ6mdTku8d+KkUf7EsEmStc31Oyj3QfdcaGTiFBSRlm3aFH31JDBQGk4gKvi3fHYzB3eB3BQsOK9UwkaSMweIC7KMHZ8gSStfPiYgyD6QmM+GWUQKoucYrY6X5r5ViBRtmg==,iv:JpasDD8EGRXbt2KUQ+vizz1WyqfAh+NunNflS1QWJtM=,tag:eLW4Is4q5xTnJjtLdmOaTg==,type:str]
  metricsPassword: ENC[AES256_GCM,data:uawvRNRAqc/lSKzSa8m3fHsmCPyyvlIexnrCNWVUax1WYWJJvTNVhFNuWpbKK5AbiWIJe8hg0Fr4gUhbZEPT9Q==,iv:bX7wRvDymrTKlYs/dw8UVT3TcGwQkHQKZoy36+mGTAE=,tag:e6tfupEOrKkVIZvDcSm/ZQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaN0swaXNoTlhUYzk5VVJt
        WjBGbzZaTVZWdzEvK0l3S2VZckZxQk1iSVVnCnZwd0JHWHh2LzhNWHZkVzgwa2lQ
        dWY3blhYUkphZ09pUzJ3MGdwMWJLUE0KLS0tIHd1aU1QaDV5OGJPSktHVUE2bkFh
        OGo5ZmpwanlseEVXbEhOTm1NemxVSEEKNWlOKbZaSVqJzUCDcc7LHyCiu83tgSqE
        xCJemzpzpO6MH+xgk+jpBxB9GtVsMW8vh+L0cmA42HhyhuCJ3Mpunw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-08T03:58:53Z"
  mac: ENC[AES256_GCM,data:9g7iSoCNN8tgCAHNCc9HFa5zuEjx0BuaKxqlmomFUYvXMcjEesBVgxx8jTI0d6qdoG7uSk+pakuKys5uu0XCYbFpNgRN3eGvbMBFAUEp7azPx7s7C9+FHJqZMg0uKFq/IddTy+aZIAaFekkVKFA6U2vJKgfwtQtUhgPkgNitnEI=,iv:9mj7qwVzQ1yNkjOI+aO5o3yEo5EwuT2DrwOPxwHnTHA=,tag:GF3Xsas37VFlQIh+PO/6nA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
