apiVersion: v1
kind: Secret
metadata:
  name: valkey-acl
type: Opaque
stringData:
  users.acl: ENC[AES256_GCM,data:Poz42miqOn+6oOPH4kVE+iB162KJImVGn17JOuan1uP832vrTjVVZmAnIFM4ppH3e1vKwQiuKi6VY3x14llLywPO5b0w7tSGuq2Ctx3nSw8INPvC8wWOzWyXlhzV2Rn8aSPB8qsVZFdAPUc+1Dwa//R7zeaUNRZegA5tfPxyTOfCk+7+QLeQxn/72CucEQxjIQI8Go7XkKUVq3wd41usgYMCn3F/g9+qd8+DsSciiY6KneXNABec1ygYAqQgIS71bcjEHz/iF8drbbeMBSCnutSGgNZnJv4w3saGpjCQx58mFkmj0rhoAel/xErUhYmMzBBu/uuL2HGLHYYbGMXfWrDLHlcxT+4t4PUjmT/dKLqDv0hPNox8wAAJWREYqX7YyZtier3adzhYR//Vx7ag7Ij2HZ+RYwyg939a9CIPR1JicisG79Tzzd6kKG18ZCOoE9x/Kk+IBhc2rK6k3/BUOj5tU4t2uUgAZBgXzc8rdziZ51fqWRV9602WfA==,iv:QOt7Au08uC7+iJdoUsBi9PZ2UWOA5wl8IXEi3t/PXcQ=,tag:1EFEPzg1D4pbCrtSx7nAWg==,type:str]
  metricsPassword: ENC[AES256_GCM,data:uawvRNRAqc/lSKzSa8m3fHsmCPyyvlIexnrCNWVUax1WYWJJvTNVhFNuWpbKK5AbiWIJe8hg0Fr4gUhbZEPT9Q==,iv:bX7wRvDymrTKlYs/dw8UVT3TcGwQkHQKZoy36+mGTAE=,tag:e6tfupEOrKkVIZvDcSm/ZQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaN0swaXNoTlhUYzk5VVJt
        WjBGbzZaTVZWdzEvK0l3S2VZckZxQk1iSVVnCnZwd0JHWHh2LzhNWHZkVzgwa2lQ
        dWY3blhYUkphZ09pUzJ3MGdwMWJLUE0KLS0tIHd1aU1QaDV5OGJPSktHVUE2bkFh
        OGo5ZmpwanlseEVXbEhOTm1NemxVSEEKNWlOKbZaSVqJzUCDcc7LHyCiu83tgSqE
        xCJemzpzpO6MH+xgk+jpBxB9GtVsMW8vh+L0cmA42HhyhuCJ3Mpunw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-02T02:59:31Z"
  mac: ENC[AES256_GCM,data:C+Z2aUJRyTLiYlxp+pjK550iSpruaKNqKjyOQJece15WA8BPDrBz4JkIQfB8atCkqam+tmbVnZx4dw5dBxtwgYdcBvfhK5Mxb6mi/WrvUoE+L3zP7ikv+dFEvZQmq2LmubE+JE4rEa6gleRvBpcB3CPD5e1lLeUWnm36pGLuAJ8=,iv:fv8h6CvTciGclAWOcQotbFw0T4y+76kuHcAdUR19omQ=,tag:ZAs5mmOM5S1sk0y9n44MIQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
