apiVersion: v1
kind: Secret
metadata:
  name: valkey-acl
type: Opaque
stringData:
  users.acl: ENC[AES256_GCM,data:eoF/Ex3cwHznPq6jQTVtI7DLiYcihMf/7Z+h17CvPLOqCIgLHpR9JXWvC/LRYivuxoSKlGgdEjHbGfsUyh/djYrKRhKygsV336h7CXxSKf1TY6Aem8HUT+A6IzmU30JLz7aOpVa8l67V8DUrQmwPPvZLgaBLq5TWBGzBQt+V7eSoSNcc/uGtuUIIICIQOUzPdh2evudT3t7C2a+tHsTg6TtaPw51gOTovwG3FCz8JlUch5NMxdrPZ3aowUMR7RZJlFs3co9dPAZgHDj66p9OAWXWu9BVH+fhQlS+7pTKm2GJTG+4EB7LbwXfedOyTg7ULBmabWrUU4lxMvZUTM0xa+PaCdWd0JggUPu5nQU37zh0DejrtBdIkyvc1jjO,iv:8Z//U4FJ5vhpS94BeaPATfGxfY7AgAXcKCZJBgNiyaQ=,tag:TrfArenO0aFGfraoyws33w==,type:str]
  metricsPassword: ENC[AES256_GCM,data:uawvRNRAqc/lSKzSa8m3fHsmCPyyvlIexnrCNWVUax1WYWJJvTNVhFNuWpbKK5AbiWIJe8hg0Fr4gUhbZEPT9Q==,iv:bX7wRvDymrTKlYs/dw8UVT3TcGwQkHQKZoy36+mGTAE=,tag:e6tfupEOrKkVIZvDcSm/ZQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaN0swaXNoTlhUYzk5VVJt
        WjBGbzZaTVZWdzEvK0l3S2VZckZxQk1iSVVnCnZwd0JHWHh2LzhNWHZkVzgwa2lQ
        dWY3blhYUkphZ09pUzJ3MGdwMWJLUE0KLS0tIHd1aU1QaDV5OGJPSktHVUE2bkFh
        OGo5ZmpwanlseEVXbEhOTm1NemxVSEEKNWlOKbZaSVqJzUCDcc7LHyCiu83tgSqE
        xCJemzpzpO6MH+xgk+jpBxB9GtVsMW8vh+L0cmA42HhyhuCJ3Mpunw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-29T07:20:53Z"
  mac: ENC[AES256_GCM,data:h4kYeFTKki+DBRWOer3lsdFs5hm1QDG+du1y9auO5GwSVa5U4IzooPvW8wr0TgsD2rlCRCVavvrohdWIS+4kq3rokiJzV13WzFXosRoI4pBYN7aw9xUThDcuFdTgeyh64C7qs/nXhaUSblTBa547Xk7riStsTwlp1mlC6cvwjP8=,iv:porjP+6qG3mWAwwnBPRUrP2ZXOfL7LepZiy81laPHoc=,tag:VxgIX1udBSCJHJdCArAwfA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
