apiVersion: v1
kind: Secret
metadata:
  name: valkey-acl
type: Opaque
stringData:
  users.acl: ENC[AES256_GCM,data:H4liISuSKX1FtWMSRPLDtRn1qqffAZE0etn5aj5zR3dxnkAVj/Jr57kbfLWKM3sADuWvzZOKbl0wAodStOOYhTEVur0KAXtFKpEvV8SW2htyR38uzTJibgzvanlZRNQ1MQO0RF3cxIPa2a/1EpP/i8i93zQ/KCwE,iv:/W7+32caUW2o1DuKX5NtpgFpCWk41bio6SaOAbcAiZc=,tag:m8hp78Bdl24KEcdB7WNfdw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOE5BNmxybjFobC9ReXZr
        VzZuWHNLZ2ZPdDdoMWFKcmVscnZhNGF3UHlBCkY3eWQ4MzYxeUZkME4xYjlpRHJ2
        UXBsclJMZnJGNEx5Q2dBOFh5cjVjS2cKLS0tIENabTd2UlZ4WlZpdUNkaUFyUC8w
        L0FHUWUvMUUzcVd4WGVSblZGUVpMTUEKO7/9qkMHzmJUhZUfm3bICZklp5j1xoCe
        gDLYJxrLC+owz0WqLM03Rs0Wszbt8bsoualBr6XA0UkuAXxgm+onmg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-29T06:28:28Z"
  mac: ENC[AES256_GCM,data:ItYAX5niWPZJGzxErbIzHJrGHL3iLqv+Gnhz+YSSusMVgkno8SQPB7wSlVp4kvbi8EIz0QSBQGLgVzD4AZl+mk6mgGeVhx/yCZdIXDUIq5pywSE56Fv5cHzOjUrC2kMukhKJQ7un4PWj5DkaTDT35NECLsM4Ihgny6NVVjb2uJM=,iv:M64Azyd9mzqrl6WLH8feqqQZ2XbsFI4sTvLT4Dr4vh0=,tag:czj7V9n3tWX0CHQ/VKwARg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
