---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: authentik-postgres
  labels:
    monitoring: otel
spec:
  podMetricsEndpoints:
    - port: metrics
      interval: "30s"
      path: /metrics
  selector:
    matchLabels:
      cnpg.io/cluster: authentik-postgres
  namespaceSelector:
    matchNames:
      - auth
