apiVersion: v1
kind: Secret
metadata:
  name: rustfs-secrets
stringData:
  RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:nMNnnJG0U6FDMWbd,iv:2PYwH2Npa829a/y6vIF5S9UfMWAq2Zaj5T7WXxuO0Ws=,tag:oA5RKYYfWm3aFDMQmTFi2A==,type:str]
  RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:8iZ+zGTHfGBrxILbx0gz+0UYX9i3X51BIsoMf7oxQPsdSWhzlsA/JiOavcrZzwBQ1DTQWqyNWe3PzO0Mm08nXQ==,iv:H+IzdwDoJxUdWmkFMdxNF5x6WCn1SDlaQPaUaZ4YLVE=,tag:SBTBg9MggWHb8MJuQeXJyw==,type:str]
  RUSTFS_IDENTITY_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:poC2Fb0v9gyegFz76YN2QRkPSGgRZcqFUPu5AI7g4lfoVQ2byHrfr9Kvz9xtSQuvYBP2Ik+D2jFM/LLFqE0Y1v7u7zb4xUKWJ/C1CLHHbIfvX+Y2+k85GLJWq3qR8fohZ9JuJq18c8UEMLfKlkZ7xrYPLUMzJDlZgs9qe7pbpbY=,iv:asbw2Qis/xKpHTJrfBLZo0SjxZdq2ixSRUgdgjiYf0E=,tag:enwnQpo9H2m0g4ytvu+Elw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaU15YXIwazEvMmVHRTl2
        WG1YcFFobVVOTE1LVXNPeVY5NEVhOG9iK25zCm9IaE9ETzM4SDgyM0FtVkNuaTd1
        V0pPdkt4cGJaa2tlNVU5cFB0b0VIajQKLS0tIDYxMkY2a0NpOExnSjBiczdZcnVq
        RXI4VytSUm9qd0VzNmlkblg5eG1STU0KEJxi/39ex1A9R46cUzOuqFMWNIqt93bG
        4zUWi6DaKo4jWG2szm+jr2ouTAIuqzTZk7z+SKc4qoshX/Ue3FWs6A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T12:50:20Z"
  mac: ENC[AES256_GCM,data:Hzk0kCHA0I8A0qKFKz1AyFNBEjv85eTDu2GUYFXDqq2lYB55/sHmvrDYa54zyTRQoBwByBYsnWVb6y1aEuqiv9GBRx1o7zcufkJF40vwaNjvhxvo8R5/73MM3z7jstJ/zBS03qgXpq5f3t+P1GiL3cJJJ8EtGb7MSYVgLQQqeHo=,iv:1W3nJz1taRdLBl+Qb/evggH85kywgwLXIaDxBduMFL4=,tag:iQq9pIa5Wlsc/RH+CRUWlw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
