apiVersion: v1
kind: Secret
metadata:
  name: rustfs-secrets
stringData:
  RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:nMNnnJG0U6FDMWbd,iv:2PYwH2Npa829a/y6vIF5S9UfMWAq2Zaj5T7WXxuO0Ws=,tag:oA5RKYYfWm3aFDMQmTFi2A==,type:str]
  RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:8iZ+zGTHfGBrxILbx0gz+0UYX9i3X51BIsoMf7oxQPsdSWhzlsA/JiOavcrZzwBQ1DTQWqyNWe3PzO0Mm08nXQ==,iv:H+IzdwDoJxUdWmkFMdxNF5x6WCn1SDlaQPaUaZ4YLVE=,tag:SBTBg9MggWHb8MJuQeXJyw==,type:str]
  #ENC[AES256_GCM,data:3gEbMBLY35jq5FycWK76Of8jQLNsu2YrkMd5d73/,iv:DRrS0RXUpRkybsKztRJruqgVm3zbah7lQ6ZS++KJhMI=,tag:npCCMYzq5QT7KsvZ7x1usg==,type:comment]
  #ENC[AES256_GCM,data:j+Uv6MmVmzaBQIZw3RrFgL9X+DqXEAbKdGAJvdhrx/3ZlCe6JhIiXwqSpCSfJYt3x84=,iv:mhVWE1zMypnoxwkY7iep8wIRghY8QHSgJCTMtJEGpyw=,tag:SgWgg3EZqY8Hvn5EhBzx9Q==,type:comment]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaU15YXIwazEvMmVHRTl2
        WG1YcFFobVVOTE1LVXNPeVY5NEVhOG9iK25zCm9IaE9ETzM4SDgyM0FtVkNuaTd1
        V0pPdkt4cGJaa2tlNVU5cFB0b0VIajQKLS0tIDYxMkY2a0NpOExnSjBiczdZcnVq
        RXI4VytSUm9qd0VzNmlkblg5eG1STU0KEJxi/39ex1A9R46cUzOuqFMWNIqt93bG
        4zUWi6DaKo4jWG2szm+jr2ouTAIuqzTZk7z+SKc4qoshX/Ue3FWs6A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T21:13:01Z"
  mac: ENC[AES256_GCM,data:/G0jqD6QmEkcxGvI1bWqHKgtErsnJZqKT1xp/eOpmq6WYM8ZPrlC9ehB48ZZpoP+brdNtQtgR6fyHM/nZKoh2VXmFr+3eUJ+hjtQDBQU8zGi3suox8bK2t1qEP7EERDPnUeFFZ4ldG06huyNx6B3Aa8kgIL1FjvjUD9cVfSjF6Y=,iv:zW1+uKv2UbE0UcWrFy3QnEHYsz6ve3ItoRPKra3lsMw=,tag:HpuFOfv5S3AMp+7r+46xww==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
