---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./racknas-downloads.yaml
  - ./racknas-media.yaml
  - ./racknas-transcode.yaml
  - ./racknas-photos.yaml
  - ./racknas-garage.yaml
