---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: racknas-downloads
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 50Ti
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - nconnect=4
    - rsize=1048576
    - wsize=1048576
    - noatime
    - nodiratime
    - timeo=30
    - retrans=3
  nfs:
    server: ${RACKNAS_ADDR}
    path: /volume1/media
  claimRef:
    name: racknas-downloads
    namespace: downloads
