apiVersion: v1
kind: Secret
metadata:
  name: trek-secrets
type: Opaque
stringData:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:qbg0ZCqfERT9RO3ar+NSTSigtIQ19lkTbUUExv91ipZWd/lJtyEOD6gIELiQx+SZsB1cy4Oryiyo6w91W57x2Q==,iv:UpVSFYjEqdGtZ/Ee7Tl5EP6fF4q//GL4PnKVAKnugNw=,tag:IXrSBYQgteaHBJLC8ZNPKQ==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:SDL3DushZyLYcxMBNKwTi8/OoYz1P3r5fbzUZYg9h3w3z+Xes7LFkhmj/DB5+5b9BFJWx4VIRiV/OJiSZjmlRA7PNyYwyJCc4aQZSciX5TkXq07QOAzB8GcxxQyYGC/bGjZSdQeiSojB/tooKEqMugTqAZPbpIMVAG3TcxGX6yM=,iv:2+GBkAK7c7nd0mpA2L7EW86rAZqc+NMPZlpMrLuPlvI=,tag:Fo43lJumqyD0zGyquV/Jmg==,type:str]
  UNSPLASH_ACCESS_KEY: ENC[AES256_GCM,data:eEVA7bjYey9qGKr+3XVd/lLyI4G3coh/ZAmrrCoHGMR6ahNVQv6MjTpOzw==,iv:HtIldyKIC39S4mTuRpqZay45ZOrx1P7NN6y4jrVfYzM=,tag:zi7Dag6IbRxacnPfOSPH9g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRlZYcG1sKzFKSjM5eFIz
        dElFSVVHbk8xa3FXK3RvalhJT0ROd3pRVXlVClg3THNnM29DOWFoOG9Hc2hUaGJq
        R1FTRFR2d2JyNFg0SWE2Wkc1bURONWMKLS0tIDR2ZzNCa3FBdDQ1SGZCbW5mcmNL
        MFpMWnNaMjkzN2hZeUFQSExUTGZiNjgKRJbriEvoc8BaRjnPZLQi2LlGeH25Ct7y
        zlqkipFfTINjf2y/niwAcP9Iex0mp1y7iZTPxINGe4EPzOU6QAITwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-06T19:24:02Z"
  mac: ENC[AES256_GCM,data:LIzrp0Wxhfs3TuPm5gUGiHYF3N+XBpxewxp0s8QvDSOX7nmGYFQyPfqXIB5FgOMh0C3xaG2q9BemtGvB/98gdvKvkL9diS1j0hMWbCJEvUuB9Aq0Je1Cp5KdtOeh/vY4zIbNdtee93yg5cU/ditzINB6OGpYQ60opc7wmYdBotA=,iv:pyXcKGXEgoNgzBXZ35lW4jI8dhuO/Mr6/Y3Mgp/RZAI=,tag:1H3glp6yfoMXJatnCd6QQQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
