apiVersion: v1
kind: Secret
metadata:
  name: trek-secrets
type: Opaque
stringData:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:qbg0ZCqfERT9RO3ar+NSTSigtIQ19lkTbUUExv91ipZWd/lJtyEOD6gIELiQx+SZsB1cy4Oryiyo6w91W57x2Q==,iv:UpVSFYjEqdGtZ/Ee7Tl5EP6fF4q//GL4PnKVAKnugNw=,tag:IXrSBYQgteaHBJLC8ZNPKQ==,type:str]
  ADMIN_EMAIL: ENC[AES256_GCM,data:wFrYsuK60MCRq/wUMoE1VdhYfRhqyw/o,iv:5K4JKOpIdIVxU7+/p7DRvpJn/zxjihmeRv+Iz20g/oY=,tag:UHAyE6l+xmh0iHgIHKhMvw==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:+RQ60l/TjcNlQnSk8kKT5l2rsZUAd0S2JnTjuC4iN1g=,iv:fCyTJPSjKm6IJOO3czH3yl423YQ+KAAwhLH7ewn50rM=,tag:lIIDDlJrx67SYpkN4pqJ3Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRlZYcG1sKzFKSjM5eFIz
        dElFSVVHbk8xa3FXK3RvalhJT0ROd3pRVXlVClg3THNnM29DOWFoOG9Hc2hUaGJq
        R1FTRFR2d2JyNFg0SWE2Wkc1bURONWMKLS0tIDR2ZzNCa3FBdDQ1SGZCbW5mcmNL
        MFpMWnNaMjkzN2hZeUFQSExUTGZiNjgKRJbriEvoc8BaRjnPZLQi2LlGeH25Ct7y
        zlqkipFfTINjf2y/niwAcP9Iex0mp1y7iZTPxINGe4EPzOU6QAITwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T20:28:39Z"
  mac: ENC[AES256_GCM,data:VyOsWeuld8bXa7rsM/IpCTaoFaVh/kA6ZUxQHm9U7ms46wJ0sdzyms+i0UqnVskG1sjTWZZx50bn7AJNcZufen32g5nxN5X7EpusAZK/eEapKmWh8z3EUCYJE4e/1MBswCgsKaWcKBx6Jdr0UXljfH5f8qQog4K5ourhXOe9QI4=,iv:ljrpKdhr8J7JDOk8Fn5bV19zoJoBRo9FJoA3dlzw+2k=,tag:cmxF2Cc6MrO0I01MPAOTJQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
