apiVersion: v1
kind: Secret
metadata:
  name: trek-secrets
type: Opaque
stringData:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:qbg0ZCqfERT9RO3ar+NSTSigtIQ19lkTbUUExv91ipZWd/lJtyEOD6gIELiQx+SZsB1cy4Oryiyo6w91W57x2Q==,iv:UpVSFYjEqdGtZ/Ee7Tl5EP6fF4q//GL4PnKVAKnugNw=,tag:IXrSBYQgteaHBJLC8ZNPKQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRlZYcG1sKzFKSjM5eFIz
        dElFSVVHbk8xa3FXK3RvalhJT0ROd3pRVXlVClg3THNnM29DOWFoOG9Hc2hUaGJq
        R1FTRFR2d2JyNFg0SWE2Wkc1bURONWMKLS0tIDR2ZzNCa3FBdDQ1SGZCbW5mcmNL
        MFpMWnNaMjkzN2hZeUFQSExUTGZiNjgKRJbriEvoc8BaRjnPZLQi2LlGeH25Ct7y
        zlqkipFfTINjf2y/niwAcP9Iex0mp1y7iZTPxINGe4EPzOU6QAITwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T21:11:49Z"
  mac: ENC[AES256_GCM,data:mPHECPIgGXsJqPIsiGcGsuLgaTyWVzy24ExhCefQ49pAihNV5fqQyfDyMzIiQN4rrEH+MwMEVVvj/JuVjfQkyVZD+F3P270lJNqSsG9/elpaCRnpIkhcSFFybx5terGO27rvep83yz8DBpOPfz2BbWwWz3H5ongB4ZNBQPK5zLw=,iv:OlhcWQq6DnbzyumnGEOoosHM6jkCDukfNLIvI31PUow=,tag:vTYQLdmxgY6nrY1ZW9ya0g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
