---
area/ansible:
  - changed-files:
      - any-glob-to-any-file:
          - ansible/**/*
area/bootstrap:
  - changed-files:
      - any-glob-to-any-file:
          - bootstrap/**/*
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
area/github:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*
area/ipxe:
  - changed-files:
      - any-glob-to-any-file:
          - ipxe/**/*
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file:
          - kubernetes/**/*
area/lint:
  - changed-files:
      - any-glob-to-any-file:
          - .editorconfig
          - .fluxschema.yml
          - .gitattributes
          - .pre-commit-config.yaml
          - .shellcheckrc
          - .yamllint.yaml
area/mise:
  - changed-files:
      - any-glob-to-any-file:
          - .mise.toml
          - requirements.txt
area/renovate:
  - changed-files:
      - any-glob-to-any-file:
          - .renovaterc.json5
area/scripts:
  - changed-files:
      - any-glob-to-any-file:
          - scripts/**/*
area/talos:
  - changed-files:
      - any-glob-to-any-file:
          - talos/**/*
area/taskfile:
  - changed-files:
      - any-glob-to-any-file:
          - .taskfiles/**/*
          - Taskfile.yaml
area/terraform:
  - changed-files:
      - any-glob-to-any-file:
          - terraform/**/*
