apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:01b2JNByyaIktA==,iv:ehjNI3gpLjh8JC3j8Oz77My9UhxpVqnkYXkaVIGoEzE=,tag:RLAoueU/aMyLHHXaTatKBg==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:UpyKxOKE/027q5paGy8nxUPtbKFWMDdAjSf/lNhbYt6AAdiQqlJSgsBPeHXiftPzdnmCTXwbAmUJl6y3QurP2g==,iv:STm2tfMNMSzraXBHE+VGad2zG7Qp591FOp3+c4xTs/I=,tag:yKHErPpREneojN/ebu7afA==,type:str]
  MINIO_LICENSE: ENC[AES256_GCM,data:AKGzg7yLnf3f2o9+inqRvpqy0lHnJXko8pjtR91/Cmzrua6XOX4uHMGSWuoFaLz3xKJN6KzNkmq+U8f7Dn45TrgBAbC2WANH/OXVrgotT76i2yk3Q9lVFBJsTFnyF0oi/dWrhhhTG4GaEgf1sAi0Sb0s+Fis7+kpPBJ26PQcUnGTjsyGGpT5udk6uvVbcVW29F3e+0dnljUqN8u/CRnhcQuTytBd6dGZ+mhtv+enOgAXQZ/hp0eLIq+kCoQtwcBiF7hbiugHiScnx87/lQy2MjcRdQOPYj0s/11jKi2+4WjMJ6tzPpSQHgkjOYEQf7W0jUxXR+19G3bf4ht+CKiW6MC213UT6SOoR7djymah5rm1PKjEjRLaoXCrlUgk2ufQInPK9nmzflBx8ZR6LPmn21W9Tl8CIbbbRDWVQqrkOoBl1xHl6KX1NFAEav94xr0/DfCLUxdQMeFZhjP3B+kNLw0WTLxbm6hmvmQanNBb4jEKOd8jHeryOAF2PToFw9X9HyI1yd9ur5kuA8j+omk3Jowp+nlPZwuyspj4vgCSHokZjn/QaX+PZYK2qMvdMrHv+5bzrfmMK8nleeg9mPCkg9rtl7L+ThqCu6MDEc7eJzwBQp4L6c3uNOk+cGZlpQZyXKrGP8j0GPuaKZaKpPqzgRvNO0BABQ==,iv:eNilyYT69wJCcLHup410QkqsXvyFOloqLkF6dao9tQ0=,tag:lcNQXh2JEv0jC2z32hzaQw==,type:str]
  MINIO_IDENTITY_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:PZm3IKDOjekiDJJJmn9j3pxI6zZtbnJiVVR4j1s4nE0xKTazFm/n/+Xq1rbt7Z/+fqovI2hY2lHlEUMPnU0D+K9tgrrX/aIvBVp6uVHHA1vqYqTsxR5N1g/nKi7f3EYEjHiRsM6LSER2WC0BZ6/B8Gi9IuzioUdvekrgx6sROM4=,iv:GLX1e/aNXQH8LYM4BLD2R24XOdB15zhmb8P8pScdN10=,tag:79Q9rl2EQJi/QLD7aMRYQw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaUs0Rk9JK1gvQy9sUWtT
        QVFpUnFwNnVYdHRqcWZTTi92WHlVcnJGWm44CkswRGhqY24xZVpVRU9rVXh0U0h4
        dWFPRjdmOUhsa0ZIMjVuVlV1ZkIvZk0KLS0tIHBmRHVneXpBVmZQN3FxRUEwSGJG
        aTEzTjdleEpMMUVDdzRwMGw3SVMzNzAKr7bLC2PHQeYZZBVtr5oXLkmgh+LM73oR
        urRFYPC8sht1rDC+a1N1u3+bPIkUFugy942Z9ZLlEpC+7pzQtN6pig==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T11:40:48Z"
  mac: ENC[AES256_GCM,data:mylb7OQ4betqpclo+9c8j7c0beomdBM1V3pJ0IuFjXxjd0CgZw4G85QTFb8tPuaAW27285mfUchtm1JupGYFmDfOVW2GuQjam/C6B3g6TzqPNj7tjRHVHAZZfWu3XbkRPy7fgdsYGaPVY+KQ/7w53dUOxRbFde9hA9ZZAuD/+Go=,iv:le/Cd/3s0jenZiLtEccS1UxcS0AINn/kAM5cA3APAUE=,tag:KdA/O+emuM+GslkAfVXGVA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
