apiVersion: v1
kind: Secret
metadata:
  name: pr-review-secret
stringData:
  GH_TOKEN: ENC[AES256_GCM,data:fkypyIZLKciVOtq/v+3JsmmsnfZ96C06a9vjl5WFm0LWv/WFfMylvRmd84FEKIdNj8XnDuJBLUisL6LjQr2NIm84OvUh9jnbqtx0dnhAwPNV07LJIeO7iiHyPIaK,iv:pUfoj8EAIEPa/5K1fzgHW3DsruOvxYUmc4ic8GoDHso=,tag:ZsKErmHA24WzICK3HlbuXw==,type:str]
  GH_REPO: ENC[AES256_GCM,data:ADhSrggf9LhSjICmCatXlPk=,iv:CtCJWI60+vvPFx+7qWnqLmapz/ZQlc/ujhbZioA7Fjw=,tag:1VY0al0krEb2Ktzuhd8cOQ==,type:str]
  OLLAMA_URL: ENC[AES256_GCM,data:yQh/BkOVenJ+oTU1PcQZxO6mzFuXhqafJOnSEY4ZqsKtVruicvmWNCrphwEr,iv:c1A37o55U5R9HkdGtLlq/w8S1D72oWCfbCt38pkylbA=,tag:g02grRF2vWc57QAsV+fKig==,type:str]
  OLLAMA_MODEL: ENC[AES256_GCM,data:qjgQtLfclXx2Dg==,iv:tpsacHE5DgADMmZqrPNqNzfT7WKW9GNsgP+kP9lR8SY=,tag:i7fSWFYNCU/3LrVJZq/etw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYm9ORUtKSkVnN0o5R2J4
        VGd0c2ZPUUg3SnE2YXVjQkxPUnh2MVlIaXo0CkNCSjkzTlFIck9PbUQva1VqQXMy
        TitpWExadC9sWjdJeWZOMDZzZEFzOWcKLS0tIHZDdmRjU05nek5uaTJOejFnTFJ1
        ZE9BejNWR01hQ0E1dTFpMHp0bXVwSU0KMy0UVC+vFVRHBoPg7DMn09ENL48K4I5z
        nCKTjwOHvslgr4yW1wpHonkuUXXM7ItxV4F+Ts8cFIGSCnx7l8dEDQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-26T05:14:34Z"
  mac: ENC[AES256_GCM,data:vq39XXvBVFutucWLSWF744j8WQfc/kQcl35GHc6NRG/l4lQLNFZd6/RdoXAkpP1C9FmY1lyxsD1nvKCoRn6Y8aMKKSrCltl3/8AdQmDyGIdpiQWUHn1UeXlZ9URL4m1YtO+JNminX435tl+24E16hc03njcSv2Ujt/lG1Civ3qw=,iv:pPdXuWZ/RAmnRMhjmkAituJFfnRdIVf6NqJtpdqhFnc=,tag:wwWSoup9nx/5oryYSiOo2A==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
