apiVersion: v1
kind: Secret
metadata:
  name: pr-review-secret
stringData:
  GH_TOKEN: ENC[AES256_GCM,data:fkypyIZLKciVOtq/v+3JsmmsnfZ96C06a9vjl5WFm0LWv/WFfMylvRmd84FEKIdNj8XnDuJBLUisL6LjQr2NIm84OvUh9jnbqtx0dnhAwPNV07LJIeO7iiHyPIaK,iv:pUfoj8EAIEPa/5K1fzgHW3DsruOvxYUmc4ic8GoDHso=,tag:ZsKErmHA24WzICK3HlbuXw==,type:str]
  GH_REPO: ENC[AES256_GCM,data:ADhSrggf9LhSjICmCatXlPk=,iv:CtCJWI60+vvPFx+7qWnqLmapz/ZQlc/ujhbZioA7Fjw=,tag:1VY0al0krEb2Ktzuhd8cOQ==,type:str]
  OLLAMA_URL: ENC[AES256_GCM,data:yQh/BkOVenJ+oTU1PcQZxO6mzFuXhqafJOnSEY4ZqsKtVruicvmWNCrphwEr,iv:c1A37o55U5R9HkdGtLlq/w8S1D72oWCfbCt38pkylbA=,tag:g02grRF2vWc57QAsV+fKig==,type:str]
  OLLAMA_MODEL: ENC[AES256_GCM,data:voLudKO6rMS1QA==,iv:LCv2jalkGIvPlOWX/TYhsEoXEFYio6W9u1aDH53B8U4=,tag:7S4Xdd6enCJWgfCakqVbVw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYm9ORUtKSkVnN0o5R2J4
        VGd0c2ZPUUg3SnE2YXVjQkxPUnh2MVlIaXo0CkNCSjkzTlFIck9PbUQva1VqQXMy
        TitpWExadC9sWjdJeWZOMDZzZEFzOWcKLS0tIHZDdmRjU05nek5uaTJOejFnTFJ1
        ZE9BejNWR01hQ0E1dTFpMHp0bXVwSU0KMy0UVC+vFVRHBoPg7DMn09ENL48K4I5z
        nCKTjwOHvslgr4yW1wpHonkuUXXM7ItxV4F+Ts8cFIGSCnx7l8dEDQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-26T03:34:04Z"
  mac: ENC[AES256_GCM,data:l85g/ytpIWPl+wOhyPUQME52SBtFecw3oEwtIvHQWJIlcD1UPEA7fnHuUkZ/lj+MZlvaDL1CmJ6Je8umHZxM+QXya9t1dEkVbAI5UwiEPAOqLRcTNZrD0e7Qk4SOn/f2fAa/NjOAIKlLzZ+dtjGyyyzanx76n6RJEPkbL3pVXmk=,iv:01tBj33AEj+ORIkOafE9/YjKwGaPl9kSlXuDemChkp8=,tag:Zcvs6qw1NZBIpprVUZCHZw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
