apiVersion: v1
kind: Secret
metadata:
  name: minio-terraform-secrets
stringData:
  minio_root_user: ENC[AES256_GCM,data:gUyx8hZVH0hADg==,iv:yR/iQMT75AXsMbDR9X8vB2Uq9IEm0bpA1TQ2sPk/d3E=,tag:EzDbc6IcTJ2MgewWFrXz1g==,type:str]
  minio_root_password: ENC[AES256_GCM,data:vFtNW6Nh7O/7JlHAM3OccyVwdGQmxFJDrT/rs3/iptuHybxYTK69HCQtCpqPVAHUaasvYYHVkkpK5XquQtPnaQ==,iv:6Yf2GhYhyu5BFvW0GAGdxzX0SmKAoiJQCRtwMhEiXMM=,tag:1xQSFEMGRkowfd31XjlyOQ==,type:str]
  buzz_access_key: ENC[AES256_GCM,data:O/8t98uKvgwsCmZv0QdhMApgGMnolVZgzbQ=,iv:E+R96kg3sa9EWgsDl98AEa0e6po6Tiy7eshRYCGIu4k=,tag:1p9qjg6GITqLwqlrkLu4/g==,type:str]
  buzz_secret_key: ENC[AES256_GCM,data:wgOeMp7m4YUbyjMwXGmsd2pJURk+MX3rfcQeAh9fAPnBqdjSUzKQkFxsn3VXWORd+kk4GUlCfhU+EiGIyrafDQ==,iv:3+L3TLCPJ5ZjnX5IWrNlx8MR2QTQuskEg9CKBbwpYCA=,tag:3ufDCqdk/7y/GOW6xNEU7Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRmRaN044NkIwSEdZOGp2
        N1FpZURkZTExZVQ3bnN3TFBGVWxpSUllZ0djCkRrZTBKSEMrRkREb204WjRYY2lP
        VkhEWVViMnFUZ2tOam5ZMTYvakdLYlkKLS0tIEozVFB6T01Vb2d5TkRYaHFJTC91
        emt5VlBZWGFwc09vS0VZaUI4bmpiOWcKWzRJi9uLi7hLDenlOFObuI+/TxSRi1/v
        k0Hh6s6cCD3LFvOWL4YhPtv+1D9RjhH+cbAQo2wwtxnmqUsSFjEMSg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-29T21:06:24Z"
  mac: ENC[AES256_GCM,data:9Rt2w4VMME+UqWBG7B2FafogNdzBBfct1SeQe2ci4xywio02IpMTwNyDkp0YTdictlBk6szocqubd18Qgi0b2hRHW2N7vqOYvmwjFMJ7QHDKc5JUEFWur1Kyib//wWXcRGhzhpTmfT6WwJnMzLf+PyO1b5yy/zv4eAixObJ1ITg=,iv:PGQhe9prxk6Qjg5SrdJYvTL3zr7/J5baWx7Ou2gmqlo=,tag:QWBJG2o4NAwp+rfS2WHyAA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
