---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: minio
spec:
  interval: 1h
  approvePlan: auto
  destroyResourcesOnDeletion: false
  path: ./terraform/minio
  serviceAccountName: tf-runner
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  vars:
    - name: minio_server
      value: minio.storage.svc.cluster.local:9000
    - name: minio_insecure
      value: "false"
  runnerPodTemplate:
    spec:
      volumes:
        - name: ca-bundle
          configMap:
            name: internal-ca-bundle
      volumeMounts:
        - name: ca-bundle
          mountPath: /etc/ssl/certs/internal-ca.crt
          subPath: ca.crt
      env:
        - name: SSL_CERT_FILE
          value: /etc/ssl/certs/internal-ca.crt
  varsFrom:
    - kind: Secret
      name: minio-terraform-secrets
  writeOutputsToSecret:
    name: minio-terraform-outputs
