---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  labels:
    recurring-job-group.longhorn.io/backup-12h: enabled
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-12h
