---
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secrets
type: Opaque
stringData:
  acl: ENC[AES256_GCM,data:1esW/0rqCa5bjxfOHM2Hqufv6gdISXG6fuc+qfmxtPzl3X0FcVWONOUm2Bh4gziRcxK+zUuKyr9PF9V/0/5t0eAsLZBJX2KhLrN/GU0+d3tYyFRNBVG+t4EjwkvdCp+bL7v5HOwbr/LeTSltDOJUqN6Kb98M5ZqgBPnoRhg5/+sUyQSm9QRGvVGBaLu3+zFO9ka+lUjpZ481WnpRb67m6S8TsVTm3J2kVr3NTQqmwpfWHT6ZOw==,iv:WIBoCHrHciviPPv6TBpowcWHHsOHVPSNXJsCYB7h2iM=,tag:4nvzMJS2NVFL7B3f0taO4Q==,type:str]
  passwd: ENC[AES256_GCM,data:WoZj6t3HQbt17MuFVg3Z034ZN1CbGGuz2v733pYV/oj9iICDPgxMiF3dzTJ5TVYnxpiKNn5fPaS8KSLJfWTwx5KA9pwQN/URkt6RGQXt0xa9JrNdaogG0XS18LFUj8fmKWKgkp/KDi0gO/WikTISZlj39Z2qWIJgKNgQgx2ZU33PJltcy/z4Y9onzVM0lYsYHorKn/WAqCRvZgPuyFrAYs0PMCm6U2/UQaQP0O2OMH5hjvBZLOa9GyR22TP7NlpLLL7jP7Am84tdF1vLwQhW0f528Fzf/3fTqJK/2pDYghI4uxkZGZRZeKFUAJ26I+75JE9jQE7GrUgZNPGBNXw5ooM22aB8vdcWngS25Rd3nY6+fwggLkTScyPQSAqzhXmMNFy+Ra/GPltCpCVqokjMlMFL/mQHq8mYgpxWzcogokh3jswEdvH9tC74Pbmq0MEVSU6NB9CLVIlTSxOV8mrXdZen5tFAhUcM2z/hMYRGZ5SdInRt4lAArD54nQlozOhDl9OBAMeFFGS5SclIK5xpMKRSJnRQwW2sIqnXDEaolZuVe2Nj17jG7a9S0iB3AknZ8TPUfp4n+2Jl20pNBGaA4LYYjsAgnXZqgQH+5b9ecss8y8IqSyR06tsa,iv:KbIuGBD07bOclp37ZUSPYhgE1k3KogNmgUAYxtN5twQ=,tag:HxavVITzjVooPnZPIRiFKA==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDOCtmcmIwWjZZZzdaSldH
        eU5PNWdqcnRYUTB4MFd2anVCc2tXZXREWXhzCjBwdUdyK1FpL21IUGkxTEhmQWZ1
        UTZjbzY3bXBWZ0hYbytEUHp5VU1vcHMKLS0tIHkrbms1WlIvNHAvMFAvMTdmRDJQ
        VFdhSkxmbVBYeXZxdUVUOFlVUC9kbXMKvCbldl324nUyO0ukxgb020hBK26r/PLd
        7wMbR/7YEyv7F2LoHvNIZ7oXuh7HgqrekJ/m9BPTyYi0OLwDqoRvrg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-28T18:44:11Z"
  mac: ENC[AES256_GCM,data:CQ57mjzH8rO3WU4+TyFYTBSGCw2P+phBsSAHU7iLJQ++bLulejOSmTWvAx/k0j05i/eUbMyRsvJCP+ZnmaU6mARVCnXzqf1Hw1uicwPfrf7WehKXD9jWatgClR8Gb4JVBMO9wZpa65Q7bvVXxlaL2Vno9NmklXB5N47HwioCDWo=,iv:GtiOO3IWTOBZu67fKny0M2hOWn7MKQ1HQk3aSRGpe3s=,tag:58drjrqzvvtkZyNFil6A3w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
