---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-racknas
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.0.151
  share: /volume1/media
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
