apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
type: Opaque
stringData:
  admin_user: ENC[AES256_GCM,data:85ivbyU=,iv:JcwWeRltOQW560InD4qGxrW1KUWkt8n3XI+vWsmBLfo=,tag:70dWisTFfyaOuTuk69YTNQ==,type:str]
  admin_password: ENC[AES256_GCM,data:hm7JDavFhirm6qL8kipOFaRYxamErnnvayPcG0IXDoj5ZSvK/NIJ7FjS7lJhnq0S,iv:ihNPrQG4K/T2j6/VBEi1pJo2iku0tpYTbuGx+lJ+tZM=,tag:kEb4VZksAuvamh/brJT/DA==,type:str]
  client_secret: ENC[AES256_GCM,data:mRqcfVJxUbiYM86lRaNJEg+dnc4HHcOausA6+zrdovsM8ILlNO9rRCSwsQ0rt/+q2QcnV+Fhv+pUKghW4EgjhgjMi4OjbXUzFUUCAANnkuehgYrhowdJLfuwOxUFZl0zRlP4I58rBk3bgxMWxCUCg2C8d2okP3vvtxq5UhuxiD0=,iv:+lpRDOdNkYRqP787nsPGR3088h5lEgZgYTenoj5W3es=,tag:KO7ysTKwt6SwNWmEdYmNWw==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZW84ekRRQ3V0N2V1QnBt
        MlZQQkpaL1NyVHVadVYxYlZtOFpwdEJWSHg4Cm1EWUhDZE1HRHJBU3pZY0x4VmxT
        ZDdkeUZnN2h5OE0rRDgwcU43RTkyZzQKLS0tIFg5UDRxcjI5UWdLL2s0L3Zybld5
        Nk1kWHgvSk05RTJsaWZPcGhiVTgrcUUKWnTpKu+7iN8D7VnJPafZwPBk46VURAgR
        gCogFjPhPQLbGmsUdIdQgClm7zYVco89R5jNDOrCteM8xHaZnOEmZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-05T04:25:50Z"
  mac: ENC[AES256_GCM,data:l4GjoNeHB5XWx78f6/YU/a2rydUB5BzIfAI2xF8TRCj+jVb5fvK/9a/JwfPXHkZL2FEKiwt0EbIUlGhCOf40ffbV+msAZln6CanFapb+qjU5khenWKOG/RSfOlr+rEigLTK3HVX5ML6tsQ+uv7ItQdCW8i8alyzh08z5YYD9DL0=,iv:0T/DcBEURLTq5XbgLgZuBUAbg/azUTeXmpilTGJmQqQ=,tag:GOldLINsCSuyd1kqL03YKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
