apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
type: Opaque
stringData:
  admin_user: ENC[AES256_GCM,data:85ivbyU=,iv:JcwWeRltOQW560InD4qGxrW1KUWkt8n3XI+vWsmBLfo=,tag:70dWisTFfyaOuTuk69YTNQ==,type:str]
  admin_password: ENC[AES256_GCM,data:hm7JDavFhirm6qL8kipOFaRYxamErnnvayPcG0IXDoj5ZSvK/NIJ7FjS7lJhnq0S,iv:ihNPrQG4K/T2j6/VBEi1pJo2iku0tpYTbuGx+lJ+tZM=,tag:kEb4VZksAuvamh/brJT/DA==,type:str]
  client_secret: ENC[AES256_GCM,data:fBg1cQ7FCS88,iv:sRXoj/2HX7K3fQs09wC77vmjc/08uUXCQtbKkWjKQGU=,tag:jl7e2+xLwQQbXHC2eS8uAQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZW84ekRRQ3V0N2V1QnBt
        MlZQQkpaL1NyVHVadVYxYlZtOFpwdEJWSHg4Cm1EWUhDZE1HRHJBU3pZY0x4VmxT
        ZDdkeUZnN2h5OE0rRDgwcU43RTkyZzQKLS0tIFg5UDRxcjI5UWdLL2s0L3Zybld5
        Nk1kWHgvSk05RTJsaWZPcGhiVTgrcUUKWnTpKu+7iN8D7VnJPafZwPBk46VURAgR
        gCogFjPhPQLbGmsUdIdQgClm7zYVco89R5jNDOrCteM8xHaZnOEmZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-05T02:57:21Z"
  mac: ENC[AES256_GCM,data:/1I0actyOq++CXRTsPDsurNomkkDrn/mugXnMRbO1QuZGRX4a+4eVoZ/Pnz8+yYKgeVAUdimXG234RIU8RXjAsZFDpaa0rlL0kWJGigntE6U45SHmoVynEeorIEpoOJh8K7nenZkSCJKNdIxzUChjUjIMkEBjq+5CId6fB+15tA=,iv:UEHAFYyRfrwaqC+tzumCs3Wno7tq1ZYRjcgGf4neJV0=,tag:P+QKs6vFVvLeQQw1ax4vig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
