---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: racknas-photos
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: racknas-photos
  resources:
    requests:
      storage: 50Ti
