---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
spec:
  chartRef:
    kind: OCIRepository
    name: opentelemetry-operator
  interval: 1h
  values:
    manager:
      image:
        repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
        tag: v0.154.0
      collectorImage:
        repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
        tag: 0.157.0@sha256:f2f01157055a9b2aab9df7118e1f1c9abf345e99b23bc7a2bc791db374a7d0f6
    admissionWebhooks:
      certManager:
        enabled: true
    crds:
      create: true
