apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:PyRkZ5Wo3V1p2Hil7N3WBQ==,iv:T99FhHHLjQ/J976BnYH7S1DGGdw3FCM7nC/phmehHCc=,tag:FN6w7WqT0GbBFEv9vme86w==,type:str]
  OLD_SECRET_DOMAIN: ENC[AES256_GCM,data:J+E+WvUxmzSlE5l3eMw3GKY=,iv:noiEX8a9DPVGsH66E67opLjD+hjPJV/+RMETgCUOvfE=,tag:YWUZ5CREQ+bjTe4UeVYYdA==,type:str]
  SECRET_AWS_REGION: ENC[AES256_GCM,data:pwMcRSmSWLUY,iv:8JLB1+6KVv8spKv+4Kx3kXOfKUIG9eE6QoEw4j8tlKU=,tag:+sraaebXVpio1LQYAf6XyQ==,type:str]
  CERTMANAGER_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:kKiJVOmzhSXqvzSWJC0ahF6h2WQ=,iv:JxJflY0D41p7J1GSWi+iG1j+TcxUbk1vCkrvlQuqEQQ=,tag:4LfMObrNriBgAyMuamdefw==,type:str]
  CERTMANAGER_AWS_SECRET_KEY: ENC[AES256_GCM,data:O6sCtxZp84EtDnDQnbnWGu2Waz1jH1IqF0yoGiMwRmP/sgJiv29eMQ==,iv:7UWwo4lT8vjJgz13TDcWE72Z/msn4O/PpIIFkw34ZZU=,tag:z902TJge9wuCJHjOFiM1Tg==,type:str]
  EXTERNALDNS_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VkLrFFV8690umw1yGuL4W13NQBk=,iv:oKn/i8SntvqPFGywroTPPKfuJ3cZgdqQqEwbAiW5WtY=,tag:3hO7BcNQ4Rwute+DBXlVMA==,type:str]
  EXTERNALDNS_AWS_SECRET_KEY: ENC[AES256_GCM,data:5XRGBYEzNXcTVFCT2TsQBd7xAm3vNq9x4Cq+yCwywmtVAZK0iX80eg==,iv:GNWNapIoMj7P9B3+jQA8/CTdzQgIc+X0fa4o48wn6as=,tag:EsHNVHk/ug9MgFymCUXoRQ==,type:str]
  EMAIL_HOST: ENC[AES256_GCM,data:7BGpAjkY55cfJysK6DmQlhKdgqW6fx31SPmTNw2lZpD1wg==,iv:p5dpsEzkXKom7VO9eGRmg8dAyogN5DRjyv7Xl3DjLl4=,tag:TNfVhZEfeIfO0SuqfG/+Xg==,type:str]
  EMAIL_USERNAME: ENC[AES256_GCM,data:R7lYdoUxG898iP//77be/bnhxN4=,iv:TCqBFDhhrpHrthkLGw8maU3cLAjum/7HvfJDZ3Q4qvA=,tag:MxJIgm5vKlJO/KLB4sb3sg==,type:str]
  EMAIL_PASSWORD: ENC[AES256_GCM,data:rmFqhgJxXIuktSNoTtYURmuKhMstU2zopwBv8KIXYp9wcN1N5C1KdRSVTO8=,iv:9L9UOJ3hQ3lNmHxhpfw8Bm5SnCnwEf3KRz5Nzpgfnp4=,tag:oY+zLp3Ll9C0mgaGLVkjwg==,type:str]
  EMAIL_FROM: ENC[AES256_GCM,data:Hes6x6rSniG++hVoOy40a6b+pj3J+KZw,iv:5GoZpfG3HXlJNKYV/rT/YdbgqN4iYtDsX+aRVO9PP7E=,tag:Rcsnw74cWTsmE7cpx1pO+w==,type:str]
  AWS_LOGIN_ALIAS: ENC[AES256_GCM,data:MsF0DqyoIWw=,iv:NQDv2E6e7kPWWSLaXEhWl0bEXnGP4xrnYRuH9LQbwoc=,tag:klIREe9nb874DOpoOqjJQg==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:0LUtrP5t9k8z45b4/OrC,iv:Wi9B/tN+BtD9A5ZZkuBADRHhion8W49dx7dlj2Xm1X4=,tag:BGXQEegpJoeiAPVc5zLhxw==,type:str]
  HTTP_PROXY: ENC[AES256_GCM,data:+R4dmYsCJ1irM6YHkjYwukqu5bMi7TrM4XQbaR1HEovMinGQetamX3ku4P1lT7YAyeYxWFc=,iv:immvBTAKr+LQWTZ6JUVSBg9+VpKULgeQg84vaq6DCbU=,tag:Q5dFIwQ4d7TrBfNJA9cX4Q==,type:str]
  HTTPS_PROXY: ENC[AES256_GCM,data:GIUN2HGnJJHIURo779tz0FSA5eo6L/JVR0FJ+Z3SWT9L5QcXwZwfOHPFCKlgJ+hfZ7GRUtI=,iv:V3cw507wRAen2IohlCkxD73jVW6Dc3Wd+qzt/8g6x60=,tag:dARTZmAeUqcMGAp/o4Kubw==,type:str]
  NO_PROXY: ENC[AES256_GCM,data:qAI/Ke4D4gn1eqNOBZyczOwCM0y4XPHySqOZGzIQbXXu0XiKatMRqtfrW3OWA3jUK7e8PxtXZYpLILIk9f2Su7J26UqiM5g=,iv:0RUmenCIxRZp2f/cdmKAcXP7xIFqvqXfgRLf5FWsXFM=,tag:RMJpdT9SErrZVC6W8ROkEA==,type:str]
  ADGUARD_LB_PRIMARY: ENC[AES256_GCM,data:7v1XdvdGUzbywuYL,iv:GfJAD1z6MMeZvk8blC71t2Ci0THjUVMphOhQbGK/cEg=,tag:uwvxe1yYnDDYEbpNTcW9dA==,type:str]
  ADGUARD_LB_SECONDARY: ENC[AES256_GCM,data:JXRCzlHzNIKlwWI7,iv:/a+nkMHJjFPmjW02+zMu74v4hAxJvSvegjc+9vX9bCI=,tag:JicgltFXdhXUDtNuq/TvDA==,type:str]
  ADGUARD_BOOTSTRAP_DNS1: ENC[AES256_GCM,data:ztKIFOrczw==,iv:3psnlzPR5xAJm0RcTA6hqtilM8pUUiq6ShjZK+6gzn4=,tag:AbqeDvg6XQw7iDIyvsLZhQ==,type:str]
  ADGUARD_BOOTSTRAP_DNS2: ENC[AES256_GCM,data:UW4wpMzZLzqb/V8XvL6V,iv:6XFvsbgCiZi2zmGSAhYh1JQ8Ek3i6W8BgRM9kDaTnPg=,tag:ATluCgF/9bZnneRA8lESiA==,type:str]
  PROXY_LB: ENC[AES256_GCM,data:wmYKiJao7nedNJZT,iv:rHIc6f6gRKA59mq0ly+1v+o2JlXSz1cORPOiwSYP7S8=,tag:bM5IJQD63Rh6VOGuHMYTLw==,type:str]
  CNPG_LB: ENC[AES256_GCM,data:KV9DALNcVfpVuRLt,iv:aeydVMXn+owcSgVbPghEbGofj15TSesbckQ+w+7LDqk=,tag:NcqdLrd8R3NnNs/LLXf0WA==,type:str]
  NTPD_LB: ENC[AES256_GCM,data:sZ838z3VTpCvzEl8,iv:b59tHufIg7yXoRykicszg2slwTKFvyQ8BS1qZv55Rgg=,tag:0FC/hHf6DvAsp5B34G+LhA==,type:str]
  HOME_ASSISTANT_LB: ENC[AES256_GCM,data:tsbswpimuddeiU3+,iv:v9VPE5KaGY2Bje7VQw+oHgxrIof0q6nGASOA18xuTew=,tag:t3O1am/vBbiSTeUF9Qy/wg==,type:str]
  MOSQUITTO_LB: ENC[AES256_GCM,data:gS6oPtfXti2s8eq1,iv:z6/yK4jbOWi+JDKJ7z5/iyRFKhvpPfV5Byr4HL6LMOU=,tag:mR34JhgXTZadrUEAObaA2Q==,type:str]
  CLUSTER_GATEWAY_INTERNAL_ADDR: ENC[AES256_GCM,data:sGaASmXfxpE/GC8e,iv:rMjADmaksVU8ZbfasOtdCbpVV3pLkLN2IoY6ZuukXd4=,tag:9RMv+rkrLNDZvmTLQYI0Lw==,type:str]
  RACKNAS_ADDR: ENC[AES256_GCM,data:5yaS3trsiFXaSExEZg==,iv:iav3cQ7u9wgXDPt1muECRX0ku59k3XE3AIfV3iPv0Zk=,tag:ztowZ2vYhLHoVOQLnIdC3w==,type:str]
  DERPNAS_ADDR: ENC[AES256_GCM,data:XcqHYcxh1AX9CpxDYw==,iv:S0bzPI85PxYeKa+L3Ki9qcfVGE2RN0yK17B73sa+Md0=,tag:TDRpXSPWHE01nXmoA6DkKA==,type:str]
  UDMP_ADDR: ENC[AES256_GCM,data:D8PnFJWbZI0xoJw=,iv:bjZvxDIYiMxEI5kBiVL1w0rUKmikQGwnWsZRhJS3LVw=,tag:kixecjFLwpt377ha0AF9fQ==,type:str]
  POOL_ADDR: ENC[AES256_GCM,data:xpxLgRJxJur1xnkQEB4=,iv:vw4dBv9yhPSxKv27T38u0AcWbH3s2M4ur+6pXde6oAc=,tag:NtJfntbvwmzAo1LDEuMvsA==,type:str]
  FLOOFEATER_ADDR: ENC[AES256_GCM,data:nN/wggLEy5xZQhNpXOA=,iv:/Tf/F9tDl7jaU3l2mGb3QE2SeRp0/fnryFSzcEP2WaI=,tag:NgxUwvPyn5IZs5O3hRrD5w==,type:str]
  ROSIE_ADDR: ENC[AES256_GCM,data:2FDGHSQrpuaOkslwu+o=,iv:oEkFkozpGH3wFjnyPtJCBwVy61cI2OBcIN6VpZ3o3qI=,tag:ST7OS5INBvp7cfp6E3A6wA==,type:str]
  HDHOMERUN_ADDR: ENC[AES256_GCM,data:WWcw4QLV490cE6Qfyw==,iv:wvlCPkQ8TTzm/2cmDbkiVItrlbZjAWyzal1ncqb8kRU=,tag:O4Z8GX7goOGzMPAxJMVyXQ==,type:str]
  HDRSAMSUNG55_ADDR: ENC[AES256_GCM,data:+NT+DIubbGtuq2N30kY=,iv:+fKvvxe7XQdLImBBVssiAySjCM9atrH+jaAaw6YJyJI=,tag:1JZFji4xHWWBHJHccRMEWQ==,type:str]
  OCTOPI_ADDR: ENC[AES256_GCM,data:BIbF6EZP/6y2c8VSKI0=,iv:YNU/nEd2eHXSAn+LMDCaJStVykkax+GL91Imt1O41vk=,tag:FaVxPVtPfoBGhj32xUY0QQ==,type:str]
  OLLAMA_ADDR: ENC[AES256_GCM,data:cnX+gvU+PiQSnDWQ,iv:fPdjEElATvBFg7L6rCy4derxnDJEeXNCYFVkhlOF5D4=,tag:7WJGzt0uLeJRbui9ZGauIg==,type:str]
  VALETUDO_AUTH: ENC[AES256_GCM,data:sGTJsmQ1GXG37XSk+0hCrsSvwpkrZVCtuxmeZFSsPHVMSQUWzI+TeLbeTnRhlkLkqvwoQgJw0wM=,iv:rA2W0xJmDIDmOsAxIHKtsZYFJwZPshkUVNrniUQCLb8=,tag:qeIgfswBaEUWfG7E6d2ftA==,type:str]
  BACKUP_DESTINATION_PATH_AUTHENTIK: ENC[AES256_GCM,data:kH7maoQ9KABTXmCDzs0HZAk4Um9VVYuegiIES2k=,iv:Ftbon1A/hR0o8KhC2Aap5mqIQvJJLW4NrgdDinvvKrM=,tag:kayD+h//WM7cBz9YWuYRUw==,type:str]
  BACKUP_DESTINATION_PATH_MAIN: ENC[AES256_GCM,data:saEXNsr8Pd26BCzUwDhh0Gue4/CnM0p7,iv:jiPC4o8xrToxR+9Lq7e4cEZ2XGVIb1DiEXbn5qKmGfM=,tag:fJTwD+/U/isAKQuf2WkSvA==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1T3ZQM0Q3N0JrSldNaDRi
        bTIzaHVyN1R2NWV0ckg1aElaMWtDSDc3NUdvCnNpREE4c3B5azZrclB4NXVEdHly
        eVd5dk9uclJvbDROamRJeUxNOHkwRjAKLS0tIEIweGY0dE0xbjdaaDdXM2c0Z09k
        QVErZlBFZitjdnM0ZmFJdWsxdUNPdFkKHhYt0Bx2svDjYFXbPKt7qbwD4eY6oTOw
        AJpedsy4z4fOGWkmn1jH7ZMsJWx2hGfAed8O5V20KArujauCyYgAaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T03:01:58Z"
  mac: ENC[AES256_GCM,data:NExUKCSty+w/XUjecO+ZINt5cGBiC4eN83HGAFlubK/0PAXXXjQsXP7v5gLxRfiUG5pMLhjdPgbrwfwOOGUG9d5EH3vvwqDVHVco+o89mvtleqzWzu79BmOBjX3cv1043X2GKM3Yed80zExdfvPZbu8QD5ZmcZxKQtsQ3MoA6kc=,iv:sjKH83FPLQeSKyJN+BwO+779qZVUKOw2kAVqGVp1o34=,tag:wdHIQIxHV0LFTBtRAdT+zA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
