apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:pRvyvSHJwqOhroWspOAVyA==,iv:JGdqrdWFAizDfynn2+8TcFWWPgUSHAdqJyifZZrZcnc=,tag:QSY97MNAAFaJtCrXziCEEA==,type:str]
  OLD_SECRET_DOMAIN: ENC[AES256_GCM,data:GMTlGchIfbuI6LvO2WLRGzU=,iv:ZTxm5HQAOvqvX3w4WmtpOqy+QCZeiUSEKCyhPNKVzLk=,tag:m7w61w6PDCo39Yi08i4wVA==,type:str]
  SECRET_AWS_REGION: ENC[AES256_GCM,data:nyfauwDb2d81,iv:s6ly23NX8TdKL1+JsBIPdKuSsC4uyeWALmEcP523Qf4=,tag:q+osHmoT4YwjAG/LEK9N5g==,type:str]
  CERTMANAGER_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:L5ii9jXv9z3ADsZ+1u0Rd7FKix4=,iv:4cAr/tYOL/6b4B88Pfukpfavvk6+telvn8FzV5l987Y=,tag:1VEBCpoI5IRNy8MNpE/Yyg==,type:str]
  CERTMANAGER_AWS_SECRET_KEY: ENC[AES256_GCM,data:P5uQeEd6HFfTntWGqW5uqUPKaR1fkkiyHx8lyVWzzzK4ecUEbCTFkQ==,iv:o5NlChjAQWexfigNSprfk6JL9Ba8N6S0To10HIQ5Cq4=,tag:jtSOb9FwA5J4D8dk1Fme1A==,type:str]
  EXTERNALDNS_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/M3KsBfbKeLZZHyDgcOZpRPlg78=,iv:uD+4nscdmYN8KjJ7/4lmKCEW/QJ7Y8sKWpXPT2FPFRg=,tag:oJcc63X5zlIlaNSstI/utA==,type:str]
  EXTERNALDNS_AWS_SECRET_KEY: ENC[AES256_GCM,data:Qp1Kj82QA66oT0P0vTFuZ0O4XbHZLz8Wu53SD9YPP4ACMGxvB2SqDw==,iv:Cn+8rtzDDbS/0eSXsD33Mws6bClTC24xGk0LszJpCbk=,tag:+mttZPld32oMZNBLUfRd9Q==,type:str]
  EMAIL_HOST: ENC[AES256_GCM,data:KEp/y8XG+lCPbYlk8krefh8kr8DQCREmHRF0OsSJW7ECuw==,iv:4tjs7Baud88Pd52KrYGQAxKY8lu3oglamNmc7QufKx0=,tag:9ovHYmXaLOlABqZ7KV3YDg==,type:str]
  EMAIL_USERNAME: ENC[AES256_GCM,data:B9tM0sdfqonUqBAhnpBOys1OhXs=,iv:guaGLHuG9yeMj7/vXFx95hHaDbva8wXnz6dFjVXAO+Y=,tag:Ii07z06DeJ6nFzYtNdnVHA==,type:str]
  EMAIL_PASSWORD: ENC[AES256_GCM,data:8Uu6y7zypk8XoPu8GpTsJakHdzFslBLGhL9TIN5nRK7BLiBp4bH3g1JX+Ik=,iv:fRAZqF7v5+riCgFdw1kPTtY7TfAq86PCMxv0Iijd5Zw=,tag:xwdZn9poJoUjBFr6fcWaUg==,type:str]
  EMAIL_FROM: ENC[AES256_GCM,data:7HnJwR51MppVAWtQSjwGnDFO2kYCBkSf,iv:dlogwAzEkg2/yBFqpeh69RTvBVU/rjUT8dPjEvsCUMc=,tag:cQYOwpnzy3oUxizczlek8A==,type:str]
  AWS_LOGIN_ALIAS: ENC[AES256_GCM,data:/V7mivittP0=,iv:U1iV4FRHLWYP7IyhxzSiiz7U2MaRAE9Ca3pjq+JgKBA=,tag:lo2guaCU4fHnYcNXXVm7DA==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:X+M7dZcpRY9wqqEeqJas,iv:VRcniqTYBRsvvMvrjCj1h/eOed3NYSG9wifk6goex3s=,tag:vtXLRyYyQGeBwhX9BudFmQ==,type:str]
  HTTP_PROXY: ENC[AES256_GCM,data:ESIplo+j1QFstwn1CWSZiufbGlwoFuJZsG1EnulGpUGNvziur4zaHzJoKIRN1iGJJ11Dg0U=,iv:BoSLxvl0ldQdx9DGeYQXikuDkv4S6UCeTymBKpEQNV4=,tag:vpCXuZNIzgwGzSCFW82V3Q==,type:str]
  HTTPS_PROXY: ENC[AES256_GCM,data:aprU1z3rWztlGWbrYtvbD2gkIgbEul6IQaSsuISd8G7NZXtIk4eRTi489NWdNEDJl/txcs8=,iv:n/oakWls+o4c5Up2wVe82/jW9BtEO7/DJyYw4x3RbPk=,tag:DCTcW0jdkcMmYDd4H4n2ZA==,type:str]
  NO_PROXY: ENC[AES256_GCM,data:eMS040xLk1OUqNlvbns+eL/DkhctdzNBVu43D7xXkmzW7nwKqh3m9ddI9uKwa6vly7FtHgpEuGVNrKwE8vYqTEmODgtV6FQ=,iv:MhIdZ2Vz8OvzlnWQIfdh0IlvB1T83pR826F9I01bI7A=,tag:x8g59T0nX7W0NR7MpU6YPw==,type:str]
  ADGUARD_LB_PRIMARY: ENC[AES256_GCM,data:CwB+h6tI2ulSDNDx,iv:8PaZdoD3Syqhv7fD6pJ+7Qh7z5rfzLdFAoUS9G7mBrM=,tag:VBRerPzHZNxmvC6kIyJgfA==,type:str]
  ADGUARD_LB_SECONDARY: ENC[AES256_GCM,data:MKiiH9f4aoly9U1J,iv:LUeRXA+6/GgyZmyhvLxB8jDy4JQx06eQW7x+LNrUi/A=,tag:0Re8JfQW10g6ARlaSvuO/g==,type:str]
  ADGUARD_BOOTSTRAP_DNS1: ENC[AES256_GCM,data:f4eAbmjInw==,iv:WtihdxJ1P/YmRmkyjMMgoOa+YwCFOaCrmW/xj9oQ+mw=,tag:Iei4QuK1C07uGI95Di11Zw==,type:str]
  ADGUARD_BOOTSTRAP_DNS2: ENC[AES256_GCM,data:uvlRANHoFhtwQan+TqDU,iv:JLgwz33Q5QcSunMKBxJUP4pAhpnay/E+GORiWYq3WuE=,tag:mW6fouywEW26F+cwqFh8XA==,type:str]
  PROXY_LB: ENC[AES256_GCM,data:gNYZoRIE9M2pGTCL,iv:hYOz39OB8sbtHP/VitJt/saGmx3zn+jjZuA4Mibz8rk=,tag:NxCxMMQiTkOyLkGwRQOIHQ==,type:str]
  CNPG_LB: ENC[AES256_GCM,data:oI/3fslC3oRyBelc,iv:pqKbVQ/ybMLpxoY4H8zLpeFOzx5U8oewg/XdvcUEmeo=,tag:qdlQ9pmIzNSXGATZ76NzAQ==,type:str]
  NTPD_LB: ENC[AES256_GCM,data:Ks2By3XF04nRrMgC,iv:Z7o2upegyEadzglTelZuJNKGOKKeEScGzH+ePFNAOkg=,tag:/ambRdciCt93j0Bo42DLTA==,type:str]
  HOME_ASSISTANT_LB: ENC[AES256_GCM,data:VaQGecBrt3DnBSMg,iv:vKwHQujKvXQDBgBRkaBdmGvAYEGJQWiVe2bz6MluZ1I=,tag:blAWYp4yZlytHUTO06l/ug==,type:str]
  MOSQUITTO_LB: ENC[AES256_GCM,data:hue+l4C0/qYXXLE3,iv:AZnPVDqtSMVJXhW1w94XPCW5vMiL3CVxduwjM/o9NYk=,tag:cX7ZuE2vsIlWSbxJljIF7A==,type:str]
  CLUSTER_GATEWAY_INTERNAL_ADDR: ENC[AES256_GCM,data:BZtYCPMDDAjR9we8,iv:ZIPJizNWoUWm2FZBncjZsQDdjvif9ceBEg7CBFUYO+M=,tag:NRpF8rnraYNFAjjmuPZjmg==,type:str]
  RACKNAS_ADDR: ENC[AES256_GCM,data:GOJD1l/rs9lTclnEAQ==,iv:LDbhIz1bgHwAfW5PJPBEBH9CNWkL8ke3CalAV225/ao=,tag:4LND+FXGohNjvbRlnnrjYA==,type:str]
  DERPNAS_ADDR: ENC[AES256_GCM,data:KWAB8bLWfCV+kmfKkw==,iv:yW2wt+pXJ8946IETmHwHA/gs9PbtIOmXfTlej/RMgZg=,tag:7TCVtUj2P8czaV+z7zM8kg==,type:str]
  UDMP_ADDR: ENC[AES256_GCM,data:cRNltWGUUQlrKmw=,iv:DOl+DaIKEOjSfTda1ak0RSPfr3PAPLBjWs5y68MQ3Uc=,tag:offTBHO704asuYaFmGRsCA==,type:str]
  POOL_ADDR: ENC[AES256_GCM,data:zlcOh1EwayOSlOrYiCk=,iv:Gct+tUvj3lrGQ9S+BWozVfXpzBXoL3NrouF6oHnr1H0=,tag:CIvt9Z+4i24m3pIxPq7OQA==,type:str]
  FLOOFEATER_ADDR: ENC[AES256_GCM,data:D1zHeBYc+Q0jeBWhifc=,iv:E54JILKbGQxa1ZjspwJkEvRANH9CS9T3XYZDJfQ/v1c=,tag:Im62lJ+alfx2fGbApUTFIg==,type:str]
  ROSIE_ADDR: ENC[AES256_GCM,data:WFCHzlmgoRJjg3BMbFE=,iv:OE7qGgjHrxzAhU1Qm80AMb1aHdgP12L0kfwlSoY652w=,tag:M7Ghk9cmfITEynPNtLDspg==,type:str]
  HDHOMERUN_ADDR: ENC[AES256_GCM,data:hpjsqg2TsOIrzkMMIw==,iv:HxPnIB9hWNKoPfFvLSu3rPwLI/yF6pCcYE1X2fqVBR0=,tag:WOLc3NRQBagZ/kU5CNna4g==,type:str]
  HDRSAMSUNG55_ADDR: ENC[AES256_GCM,data:uA+gCsbKHyDWVIPM6ug=,iv:SE8TXDbVQNgqHemzttwT0We76nMyeZssBHjFWxncWa4=,tag:yAbjVBmuz0cbsTmxIDpyFQ==,type:str]
  OCTOPI_ADDR: ENC[AES256_GCM,data:Dtaqs371VfnRBtBMKQ8=,iv:sAwFQ5MdJxTqQ2p/MpIFv3/veGl4BUPwxHHTEd2JSjQ=,tag:z8E4H/jmcLbnwyi2AOEp6A==,type:str]
  VALETUDO_AUTH: ENC[AES256_GCM,data:nslWi/wNsasvgulk+WB4EOvEruypK68PqtfxJC7AnAEJSZbMnWBWONYZf9V+bWoAF+VzumD8VtE=,iv:OlcuC8vrBXbYAIAP9VXMuVSX+UffSOwCV571kjosOVs=,tag:/BajOXUya8DCtBk53YdKdQ==,type:str]
  BACKUP_DESTINATION_PATH_AUTHENTIK: ENC[AES256_GCM,data:w5bPG7HNV0JfZOS0uzN0ARBYOGpVgAJDw4g+p/E=,iv:+lT43P9VrudCQjbxVmcQjPxK9QX+U5BY+4l8+9dNtVc=,tag:mp+NCM0Q69rlEcdX77QInA==,type:str]
  BACKUP_DESTINATION_PATH_MAIN: ENC[AES256_GCM,data:zKqftPq3NI5GVXw8opyn3bWohQVhyy0g,iv:K62mGdH8cGjIuSTSc5SI2y38NPfs0uYD/217ZzcxE84=,tag:B/0eemerdxMeh+ShX5ARAA==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4b2oyMVdoSWRJUXBYZVJE
        QTFpdlRXS1NqSFB4ZE1KT3NOMGkrVm04dFNnCmlXblIyWm1DeUtuZk1oQm5qYWsv
        MndqNkxsU201WDF2MGxMN3o3QVRRWW8KLS0tIG9mNmQ4Z2pFQkNIT3pHM0VabGFY
        YkYwRFVIc1huSXprODF2eSt0UzRKc2sKtA7pCa7czSai5/cTLXC/RTQkkV60AsRW
        W2lNQ71XqCraLxm37XbLs0LLLFEPx8BmATd20nOWjoW44QwhXRGDVQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T19:35:57Z"
  mac: ENC[AES256_GCM,data:j0FXgpMckh3TUsgWCEFLRNuVeas6wNCiXtvM+DM7EzWOodVN+1nFqI0bdkcWsvZDPhlZd8+QojuHn1mHS4eObu+xMWsJnZdmAVm5mY8TFJqdA8FEkLB642ugzDUFoyff2fYYfVeykLnek2ygTancSb3dCWyoRU6TKOsJWA8dTwk=,iv:cxgQc5kczfHJMmIj7MiyN/bTw/0jdcLdc4OqC64f+cU=,tag:7seRW7BJ/Zbq5KUhzr6F6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
