apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:w/7LzZB8l8gyk7JcDbPvbw==,iv:fxz9fqnLPZkhOvrimecRy1HWm426SMYCdzCiNa4o4n0=,tag:dPQkedI78M8uY21rFHVq9A==,type:str]
  OLD_SECRET_DOMAIN: ENC[AES256_GCM,data:ZFfeU++bumm9kEBJgStf4rs=,iv:0qspRFWhujRgFkrmpKQMlhMeVcHFs9Tu2IKZCrSx9gQ=,tag:bPRHI9O/bkeKJ5Z5jKP6Kw==,type:str]
  SECRET_AWS_REGION: ENC[AES256_GCM,data:e4/6rUuoTFg+,iv:TmdijOUqVh5k27FhZD8XK2LEVfZThZEOUzkgwwasDWw=,tag:vSKh2NG0QxsBpqXh+xZUuA==,type:str]
  CERTMANAGER_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:hUT9LL7BG3ahzTofrN40fLFm/VY=,iv:/orUL6Q96R9ai4TU4l0gzkzC26QcCu8HV0sN69P5s1s=,tag:bcphlLqDzCzjKQ19MVv1iA==,type:str]
  CERTMANAGER_AWS_SECRET_KEY: ENC[AES256_GCM,data:9PAjM4io2vySIAv2WRi3zz1nFchejzFCwh+ZQbCy1ld/EiX22uUEcA==,iv:VJVF4zQeckpk3nQUm/GYWbim2Kh6FWxoJkEm8cDpFCY=,tag:SVu0xJPsq+a+FJvGvjSMXg==,type:str]
  EXTERNALDNS_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:gXBdtuufsw8VHCHXhPk8ifVy6Tk=,iv:LCEDt1Dop1pgzV+1l3guGJRIxWHcLB08NUpBGgtCR4E=,tag:xw0753XIvtACHY/qpo09EA==,type:str]
  EXTERNALDNS_AWS_SECRET_KEY: ENC[AES256_GCM,data:cha0OEMijiq32AxWrQldd0mTKhG5nPu3SJZ3lzj95ShRGgHy4eJhtA==,iv:2SdK+LjeJq5cHhEwbNcXoaIbksn1iD7Yy2iHtzm8k64=,tag:q/zG5i5U21SlI2UN0d8Lkg==,type:str]
  EMAIL_HOST: ENC[AES256_GCM,data:aNaw1O8P9tGiqvDWcV0Jwc6IPH2wKWW/WI9vKM5nM/e3CA==,iv:aHVaG4QBgG8xolnw3IP5QKV/0PlpVBUbWxHsnGrxa0g=,tag:4B60oVjHeNPGaK6ntQzWkw==,type:str]
  EMAIL_USERNAME: ENC[AES256_GCM,data:Bbbm38wUGNXwRX2wip5VFF+INjQ=,iv:O21ltbJzu4FXMt+LfomF4juKHnd8L/ZygeyqSlPZ+4I=,tag:eYAGlymJO1nMBUuxP6uexw==,type:str]
  EMAIL_PASSWORD: ENC[AES256_GCM,data:P+d76gIGjsicDnO95pEn6bOkXyNLl5+93eqQO3XUnVjj8Zn7HZad1VZFLE0=,iv:P+t4q8xq4wE9Jn4Q/v4D5MQ7kIQzsLCj865gpDw/5Gs=,tag:4VFfwJub9oOMGFubLwmmbw==,type:str]
  EMAIL_FROM: ENC[AES256_GCM,data:mLS3GOD3MwlwMz5LsEcoe7NsySv5qGuB,iv:V5LZSYEnMPqTiFbhPC/3gxLlSKRzNBCx1OuqWadM8sU=,tag:sym8G+JnpwEq4Z5JfymaSQ==,type:str]
  AWS_LOGIN_ALIAS: ENC[AES256_GCM,data:oXkKicAsj8U=,iv:iW6SZl3PbaV5R9JfdXUwaYqi6HCIp9RdujmWxnfT3vM=,tag:kzWkbkcmu0bTKGZiuW+4Vw==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:GRPHzXDYluoV7Rwn4GJn,iv:IMaIhp+4tb4u6htQ9sNrgAD2yxAMIpZRj0ZKMZrNRtE=,tag:CRCXHdXx+9UpBg9Y089odw==,type:str]
  HTTP_PROXY: ENC[AES256_GCM,data:YkCtVCPpq6i3EPDzp32yitiCHNERfcPxu0tlBWmfK6M78Nyi/YMu4ILFSfdSjar2BOffEn8=,iv:JNJa2sP2J+zmaFTUQ1NfgDrG5+DNuKWPBZn/+O+qZrc=,tag:xU7lAhdCDPBfqRHoEPFGbA==,type:str]
  HTTPS_PROXY: ENC[AES256_GCM,data:SlOm+EZcxTQizZ1En2u832ISFfS22ZD4KeWyrCVMwQjZcalKX+phUcHuAxlAudrCYSTR+4k=,iv:ypWNxCNh2wpffSS6U825I22FUfE+/hvZaj64+m35ubk=,tag:9kYS/dy/fg+5ZLF75YSdXg==,type:str]
  NO_PROXY: ENC[AES256_GCM,data:GWLGtk76PezlbKMRJXj5LVOWQQvPABhYtKkZEy6SWQgS4EN8h7zjoLBxF+7tbNT9sxnIMllVmwAvLogtvutq3Ygvq/WiRRo=,iv:ABZ5N2EuR/EOlIOgEMyKIZDeFEGAqjZ2PJZ9OFu9Bc8=,tag:oeWmrrr1mHlYT+yQ484f3Q==,type:str]
  ADGUARD_LB_PRIMARY: ENC[AES256_GCM,data:hdpNk1nkr7BIcxpi,iv:UegatFAnS3Kht7gBQut6qJJR4rmqhXZXT9E8qkrwIM4=,tag:Tm1VerN3Lvx9EX+L5aH2gA==,type:str]
  ADGUARD_LB_SECONDARY: ENC[AES256_GCM,data:ucLGBeGInx6GW6Ij,iv:YhIdc5qbEzDkmjGV8ZJYF07XriHLcRnS6fX0HhJH7oM=,tag:0GtAhkRdqa10tNYuU2gNrw==,type:str]
  ADGUARD_BOOTSTRAP_DNS1: ENC[AES256_GCM,data:+4Vy0mNhMQ==,iv:rYsvyn0DNJzEuRR78q4esyJWyeXo6upZpIKCu8WuFzk=,tag:Pc2civvNW0cPrGnfC+3LJw==,type:str]
  ADGUARD_BOOTSTRAP_DNS2: ENC[AES256_GCM,data:LidZiTi+B/z4zR+6Jmp3,iv:/OR6dEAErlE52aGiD5WEOz/QbrEDhoYtgajcH1toV28=,tag:bdyBtmtYNibNN50LdmCyuw==,type:str]
  PROXY_LB: ENC[AES256_GCM,data:r1Ee4xJ6FnYfmObs,iv:57PEaVNkc/zh8hRGS/LLtSUE7m6Ju/w8Bt05akTWMns=,tag:H4DCnOg8S0GmHd2+MVMeNA==,type:str]
  CNPG_LB: ENC[AES256_GCM,data:1RQiqJxohFEzdWz4,iv:Cx9fO3Vvpl64Qi0Y2k3TrhvIlOjksfdegJ2AHNQzzio=,tag:Z/8zegvzKrNiebxIGjqLKQ==,type:str]
  NTPD_LB: ENC[AES256_GCM,data:v8EFf0PP7aHfElqy,iv:S9yuyIwDymnAxnkTNTunTZXQQztnDtFI+EmmgFXiTHY=,tag:8j3Rrs1Bg9xUCJxTBcZbRQ==,type:str]
  HOME_ASSISTANT_LB: ENC[AES256_GCM,data:66yi5cjYxexsd3Nh,iv:I397aeK8dXdpYcYJqr2tajEMxywjbekR9aa0rpSlBKg=,tag:udAEQxsLJ0NgI8YkUyxskA==,type:str]
  MOSQUITTO_LB: ENC[AES256_GCM,data:b4/QNzDaQogPXu9P,iv:rzqe//haWjngXgpRfAgmWqRSprZJbUbJ5gDvIXzbjWE=,tag:JrubOewvdGOECtq+UEKwkQ==,type:str]
  CLUSTER_GATEWAY_INTERNAL_ADDR: ENC[AES256_GCM,data:ELJRrSiYKCYJvAp2,iv:nTB3RRcCHeyja7ULprwQNxM+wD0tuOm7bGcuNbza6+s=,tag:q8bWjzdTPXxincWk07ao/w==,type:str]
  RACKNAS_ADDR: ENC[AES256_GCM,data:M/04iLCnwtBdLun3kg==,iv:6Kg74pR+uamgA8YppQ5v/moBzHM4nOTFyvByMf6U0i4=,tag:7BWwiLGgk41Riv2/z5vHpQ==,type:str]
  DERPNAS_ADDR: ENC[AES256_GCM,data:uNmnBwsWXL+x3z84ng==,iv:KrAIEx/obhgW47hGEgD8B3yFDcMsMIj9vnP8gmtuKrI=,tag:fCKDKFGyLJBJV/zAFMzVgw==,type:str]
  UDMP_ADDR: ENC[AES256_GCM,data:36sSqPlPDVQ+CsI=,iv:HlF74HwW9O+qYrMDXX0ujCSXyok+qt2zIRh+ezmW9vc=,tag:KsO5d3HqXlUIuW7cMYm/pQ==,type:str]
  POOL_ADDR: ENC[AES256_GCM,data:vZQRBB/K2PSgOruJuws=,iv:L+FOJoyduvHuxTC4N5vyz6OXFoS87eVIC091UBgMM7k=,tag:faKE+EMDdus2XyD6RNm29w==,type:str]
  FLOOFEATER_ADDR: ENC[AES256_GCM,data:JZb9qQQ9vz4RqxgyoiU=,iv:NlXtO95mM0qJDeQRfOLb13KL200KAMKrskypDglyRJ4=,tag:rUo/YjX2gcL4cOSCuDxyAg==,type:str]
  ROSIE_ADDR: ENC[AES256_GCM,data:f3HTj+qVSOPl3RUZY2A=,iv:TegH1k3dvlgI3bxFW5winL4YtsPfYVSfbp7R6jVrGPE=,tag:onp3xqeJUQcLGrwIAVqOIQ==,type:str]
  HDHOMERUN_ADDR: ENC[AES256_GCM,data:ONE7Ld5TPjKStt6QvA==,iv:fACYsiibfKZTLfDf5v+2bEA15Fhnh/Pk8ox2bPi4d9w=,tag:DXdl0bV4GzO6CrGRfnCVqA==,type:str]
  HDRSAMSUNG55_ADDR: ENC[AES256_GCM,data:+YO6mY7s3x1p/T9IL/8=,iv:BL84xXcjVcjmFsCOYFQZdneP8EX3fCRv5Bp6WaTtbzg=,tag:QTfUUDXn/f+1gatcmnoWiw==,type:str]
  OCTOPI_ADDR: ENC[AES256_GCM,data:jO2mXhLSSZcsMVxphco=,iv:LgzKb3LAU+klZ4SFJqEchJtITnGkGQftoqZzOrkivOY=,tag:d9wLYVLvb17D4euZcGyyPA==,type:str]
  OLLAMA_ADDR: ENC[AES256_GCM,data:geHtcUhmbJqDqAAb,iv:LpdTmgVd8lkPaFLPWy6xwX2eNlEgsU0LGNqNoAe6tgE=,tag:wwjhBCEUY6Jb5ePAwrN/LQ==,type:str]
  LMSTUDIO_ADDR: ENC[AES256_GCM,data:mFbD/tL+RC+apT4w,iv:pZisL5YWRuReDpKXKe1UTLt5aZtfbW6VWvLbYtlaGl0=,tag:pB+m+HQT39X780DcOripkQ==,type:str]
  VALETUDO_AUTH: ENC[AES256_GCM,data:8KF3KMzEzwzTPHmX89vxH6SIBJyRdR0ltcnryhqlehkp+p52ylM+FXfo75DCYeXLVeO+t+Liip0=,iv:sjmniKfOeV6WwjTN2mpVTrvDAp8UPHmQL16c2Sxa/5A=,tag:eQab6/YqUk+uwqb1Kl0wfg==,type:str]
  BACKUP_DESTINATION_PATH_AUTHENTIK: ENC[AES256_GCM,data:nwaGaR3lxXqbzLcZ87HhtXVbdHuzh7FJqADqPlM=,iv:P+ovAnQ8bA6rcREQV0N6DoT7p//l0VsegfMt3amdIGQ=,tag:GrOoKTrHDZkzzOl8YRGuOg==,type:str]
  BACKUP_DESTINATION_PATH_MAIN: ENC[AES256_GCM,data:lyTo32uE0saQZba350YZXtku78bc3sFl,iv:5wnIk+Aal3e1CH5CZhMqWmILQNJ0LhjBkmrceSLVbGI=,tag:B6jPQlMlx5740vDtSKnE3A==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQnFzQWVmM1czMEY3Zkt5
        Q0tkSmJ3Q1pHQkJPMEJWNmlpdUM0cXdzS0FZCmw2UUJ5d3hwb1pWazZxcE9QUTc3
        WXRMWGJzRlI4SlJGNHRZTVltaEJnc0EKLS0tIHJDdkk5N0NXQ2xJNlRWbjhPZmVE
        NVdycWFpeWE0NlFyYlMyZGxNd0diS3cKgGWkYbIBzY7rRtxjKwJtPZ6THtQsi+y3
        G1gDsBLNE6Hz1Ix32MIfZkGaUNK+kDYd2mtTr+xbAhQ6Q1Nmbekz6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-06T05:27:49Z"
  mac: ENC[AES256_GCM,data:DCFDhaEA6eMOeH0zusX05VEdFBGhnbr9Ox2ZM3/3t2inZVPJIfVH0g38ri8r8ybA+bRYXopEyOIy0Npo4MsTPpbLDQZ6OAmAgIpn0kMiXx9Pwd4g0kbkzm3Ds84Fgeq/HczYCKw/IfUpzCpGYuHfWFcvvpg5ke6m8x/59lQcH/E=,iv:sq6e0zrmv0942cjjRylJdYMc4hNyoX2nNRSidsLPtsQ=,tag:acAA6gNiSYn4Yky6JMRpHQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
