# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-5.0.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recyclarr
spec:
  chartRef:
    kind: OCIRepository
    name: recyclarr
  interval: 1h
  values:
    global:
      createDefaultServiceAccount: false
    controllers:
      recyclarr:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
        initContainers:
          init-config:
            image:
              repository: docker.io/library/alpine
              tag: 3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
              pullPolicy: IfNotPresent
            command:
              - /bin/sh
              - -c
              - cp /tmp/config/recyclarr.yml /config/recyclarr.yml
        containers:
          app:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 8.6.0@sha256:3c38ceeb54438dd8327e4e65c9b48ba601a6d20fff833342d93c9b0bc4b1930b
            env:
              TZ: ${TIMEZONE}
              http_proxy: ${HTTP_PROXY}
              https_proxy: ${HTTPS_PROXY}
              no_proxy: ${NO_PROXY}
            envFrom:
              - secretRef:
                  name: recyclarr-secrets
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 256Mi
    service:
      app:
        enabled: false
    persistence:
      config-file:
        type: configMap
        name: recyclarr-configmap
        globalMounts:
          - path: /tmp/config
      config:
        type: persistentVolumeClaim
        existingClaim: recyclarr-config
        globalMounts:
          - path: /config
