---
apiVersion: v1
kind: Service
metadata:
  name: gateway-talos-logs
  annotations:
    metallb.io/loadBalancerIPs: ${OTEL_GATEWAY_TALOS_LB}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: opentelemetry-gateway
  ports:
    - name: udp-json
      port: 5044
      protocol: UDP
      targetPort: 5044
