---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium-l2.yaml
  - ./helmvalues.yaml
  - ./helmrelease.yaml
  - ./networkpolicy-hubble-relay.yaml
  - ./networkpolicy-hubble-ui.yaml
