apiVersion: v1
kind: Secret
metadata:
  name: buzz-secrets
  namespace: buzz
stringData:
  BUZZ_RELAY_PRIVATE_KEY: ENC[AES256_GCM,data:8TxPRIQ4xHi2Wzq8s8VaH2MlGs96HroK84u0hPr2DauR+1E/sQwi7Ttc8gXfrYCcY6bbi16jM8RlvXayE+GOSQ==,iv:OxACmzOIoK+51IMYDQxPd9xGuB4Xb0wYPl2pcXXOZDA=,tag:ttd54At8bZEXGleICZ2bdQ==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:mPWdFeXLLtoPjn8ps6HHaMm/CaCcljF+QQrwaaJWVBbelBQTkljDyRDcZ1uKZtJtDVLIQkBOBSMND5AZpGL2UEjau3USt4gQef35L6GH2AGRsIkpDW5/fK91nKz/PcwqO7Ou/TWsYjxK6XmsYEexgMczdMwod4Ib2e1QfdKI3zq5,iv:D+DF+fclV+BX0Zx9I80Plhhj4D3MgMFd2iet3yG5bIQ=,tag:IXEc1akboVXX5BXFiBGGgg==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:NcR+fXOx3iuhq/DIWhutLU5YCt5RURWg98RlzqHYmKhd8QS09gneu/5L+mw4Y1U6cusiOvcaJjW6rqHkSFP0EZV5BkJOBpCnZuQ1gBHZbFStQ34K0d25xb942MBSgaeTrptfOXx/Qb0nWDBN+McG3AD8Gg==,iv:WDWG8ppcPnQRjDcUxESvEobJF9YS7/pktjMyuLBozc4=,tag:S9suj0IrOSY4k1Q62l23Ag==,type:str]
  BUZZ_S3_ACCESS_KEY: ENC[AES256_GCM,data:S1VV9TEf4bU2am8Ufg54Wqc9NBj1Vst6ns4=,iv:W/TGLAwcY7ozmBsRoBEvplDsTz14Ew/e8ORaVo2N13w=,tag:2FcG7VpN/ljyHm0IdmecEA==,type:str]
  BUZZ_S3_SECRET_KEY: ENC[AES256_GCM,data:4Wc7Jb68yg1soETSp+z4CyU9/fZSGGQKnn4kOsmS8oQ/UX0TncClRvZLK2CCP1UB/5GPTOViLv1a/3RJY0WO8Q==,iv:/snx1conVkDdVbZ8L9S4q0UvPFfEScBNvSKUCmVct7k=,tag:D/MbkPlxxL9LGAMntASMtw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdGFKckRYeXk3N3lQWWg5
        d3dRZkJaOFVCU0ZjUEVVOTdneWwzZ1I2eVdRCnBtRjJsQUpHK2FCM2ppUXZ3cG9K
        ZHhWNmgrVEk0SWFEOW1rMy9PNFZVaVUKLS0tIEN3ZFI0Z2JMelFzbkhKbjNUcE9M
        YnE2T295TlBIVStLcy83d3NTZ28zYlkKEKcaQDDuVdrXyEamIA+v1CZgJFoLNGns
        Dwr/BWoypHbyP3gKYDw8/NAVh2SH65JU08epz8soPNY5wGUlncoQfg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-29T17:17:36Z"
  mac: ENC[AES256_GCM,data:XYv7kOT2EK22lZgg7pD1nMwgiLRXyhwamhb2Eln2siGpRyWzbPnZrFk2wmoZN4J61U5frQds79EA0gjOJDMpcjP5nXknCWgv9IeAFyA6LK7gcjX2twlSlwugF/uvtx1j7NB21gu7LLwzXjGvlmB6XchEp7f1mHPd0KRJIbL078s=,iv:O/Hg3oXkMEmUKn995p3dw4LFf0nY96d9HIonlgps318=,tag:04cdEfa9+3TzQ+cTU6ob+g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
