apiVersion: v1
kind: Secret
metadata:
  name: buzz-secrets
  namespace: buzz
stringData:
  BUZZ_RELAY_PRIVATE_KEY: ENC[AES256_GCM,data:8TxPRIQ4xHi2Wzq8s8VaH2MlGs96HroK84u0hPr2DauR+1E/sQwi7Ttc8gXfrYCcY6bbi16jM8RlvXayE+GOSQ==,iv:OxACmzOIoK+51IMYDQxPd9xGuB4Xb0wYPl2pcXXOZDA=,tag:ttd54At8bZEXGleICZ2bdQ==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:mPWdFeXLLtoPjn8ps6HHaMm/CaCcljF+QQrwaaJWVBbelBQTkljDyRDcZ1uKZtJtDVLIQkBOBSMND5AZpGL2UEjau3USt4gQef35L6GH2AGRsIkpDW5/fK91nKz/PcwqO7Ou/TWsYjxK6XmsYEexgMczdMwod4Ib2e1QfdKI3zq5,iv:D+DF+fclV+BX0Zx9I80Plhhj4D3MgMFd2iet3yG5bIQ=,tag:IXEc1akboVXX5BXFiBGGgg==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:NcR+fXOx3iuhq/DIWhutLU5YCt5RURWg98RlzqHYmKhd8QS09gneu/5L+mw4Y1U6cusiOvcaJjW6rqHkSFP0EZV5BkJOBpCnZuQ1gBHZbFStQ34K0d25xb942MBSgaeTrptfOXx/Qb0nWDBN+McG3AD8Gg==,iv:WDWG8ppcPnQRjDcUxESvEobJF9YS7/pktjMyuLBozc4=,tag:S9suj0IrOSY4k1Q62l23Ag==,type:str]
  BUZZ_S3_ACCESS_KEY: ENC[AES256_GCM,data:F0gTzE6HWov2ekTYUMub1KFqTqk=,iv:hY4ZCffSTn+ASU+NCkWzkKrhdO0iW4bjABs+lzv6/t4=,tag:acfHeNE9s/zuC0wk3UE+kQ==,type:str]
  BUZZ_S3_SECRET_KEY: ENC[AES256_GCM,data:c2Nybd14kVqCZEbF+esLGIBeZm55ZUA8TchxQUSy76hWnkyc06ZQRg==,iv:3jaCpC1YgpcTd9OJj0db5LP8QYY0SvK9BXJkJ3hD6Ew=,tag:2T5Mzg8YVCrudW+iAoA8xw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdGFKckRYeXk3N3lQWWg5
        d3dRZkJaOFVCU0ZjUEVVOTdneWwzZ1I2eVdRCnBtRjJsQUpHK2FCM2ppUXZ3cG9K
        ZHhWNmgrVEk0SWFEOW1rMy9PNFZVaVUKLS0tIEN3ZFI0Z2JMelFzbkhKbjNUcE9M
        YnE2T295TlBIVStLcy83d3NTZ28zYlkKEKcaQDDuVdrXyEamIA+v1CZgJFoLNGns
        Dwr/BWoypHbyP3gKYDw8/NAVh2SH65JU08epz8soPNY5wGUlncoQfg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T12:28:42Z"
  mac: ENC[AES256_GCM,data:mwd1j+jU/eyE130Kosf0uiqS8xD8/ZlbenjFZKpKH2cLWm7Jc1P9mD1A+KNG5nkQk7xBX81pH9PFu/p3ehtgojuTaa+nsKFrfSplaf8KLZLmnCdcgyBqcyEQwhyYwV4Fr+YJBOb+1ZlmdBNGJUtkmr1okXc5d79HkA092QwtBas=,iv:DpM7j3Y9S/JcNIMgA9VaacstMy0Sy/WHdMz7e3abZ5I=,tag:CQ4nRQZ2rfOjSkUy/G2SQQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
