apiVersion: v1
kind: Secret
metadata:
  name: buzz-secrets
  namespace: buzz
stringData:
  BUZZ_RELAY_PRIVATE_KEY: ENC[AES256_GCM,data:8TxPRIQ4xHi2Wzq8s8VaH2MlGs96HroK84u0hPr2DauR+1E/sQwi7Ttc8gXfrYCcY6bbi16jM8RlvXayE+GOSQ==,iv:OxACmzOIoK+51IMYDQxPd9xGuB4Xb0wYPl2pcXXOZDA=,tag:ttd54At8bZEXGleICZ2bdQ==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:mPWdFeXLLtoPjn8ps6HHaMm/CaCcljF+QQrwaaJWVBbelBQTkljDyRDcZ1uKZtJtDVLIQkBOBSMND5AZpGL2UEjau3USt4gQef35L6GH2AGRsIkpDW5/fK91nKz/PcwqO7Ou/TWsYjxK6XmsYEexgMczdMwod4Ib2e1QfdKI3zq5,iv:D+DF+fclV+BX0Zx9I80Plhhj4D3MgMFd2iet3yG5bIQ=,tag:IXEc1akboVXX5BXFiBGGgg==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:uPoso6c9YMSC/kbLH4WRpy0Ae5YUjOyv3nGa9pfTrXhe3us/StLscoF8k3TafL434elCv7bbH2rmFxZEJrbsQl/6tajGHVTzfgPNc9HMoWuPfBD38AsLxSDjWCn2pewtfBrifl+Ygdha2gWkXZ5hhb/LHKC6yso=,iv:BUbSzZV3iHV/+N43qkWX9248PKJKsrnd9xDn91RFY/Y=,tag:JuIU6b59dJzFjlqnP8wQfw==,type:str]
  BUZZ_S3_ACCESS_KEY: ENC[AES256_GCM,data:UPlw8sy6B0nMpgqMMbu8YbKYc4s=,iv:wZPonD5DEZtyDLqXuHL9Kppbdt9Jc1Q/lf1CzNrm8FI=,tag:Dd8uBE6reM8bUKF23XpLCw==,type:str]
  BUZZ_S3_SECRET_KEY: ENC[AES256_GCM,data:Lm0YVgs1fsroLe11sZT+rtMLp8n4I/fM6jCMSNmaV8dHFCs0QU/+Jg==,iv:uBe/qi9Ocaa3iNsSuM2DiY6OPAzxaN4LxExu4Z5Gavo=,tag:dF+puLnzMY3cCDkaoF9H+A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdGFKckRYeXk3N3lQWWg5
        d3dRZkJaOFVCU0ZjUEVVOTdneWwzZ1I2eVdRCnBtRjJsQUpHK2FCM2ppUXZ3cG9K
        ZHhWNmgrVEk0SWFEOW1rMy9PNFZVaVUKLS0tIEN3ZFI0Z2JMelFzbkhKbjNUcE9M
        YnE2T295TlBIVStLcy83d3NTZ28zYlkKEKcaQDDuVdrXyEamIA+v1CZgJFoLNGns
        Dwr/BWoypHbyP3gKYDw8/NAVh2SH65JU08epz8soPNY5wGUlncoQfg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T12:45:09Z"
  mac: ENC[AES256_GCM,data:J+4olMriY+nqT+S4OcHISCbo1u9q5WbilqyqDIuwU560YDmdVmx8y9C4CvMqoz9dfvQQBUYre8deRrZ9yoVeupMP+ZC0CpOe/ml724pMZb3jKdjga8gD6feDgZWHPkru628oUTjxE7btEWtni6uO4ZM1EZn0Dzk1EDAgMAbEhcs=,iv:cUxexRalDZcqCALnkalvvxwGQlWC0JkxOkQ9ia1TeTA=,tag:o9mRDJKV7tgCF4AlQFQj6A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
