# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome
spec:
  chartRef:
    kind: OCIRepository
    name: esphome
  interval: 1h
  values:
    controllers:
      esphome:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/esphome
              tag: 2026.2.2@sha256:84d248412dd4421415cc4d4710096974d9ed9c573a4e9bf2fe8b245d2d406b7a
            env:
              TZ: ${TIMEZONE}
              ESPHOME_DASHBOARD_USE_PING: "true"
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 3072Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
          codeserver:
            dependsOn: app
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.109.5@sha256:f9ccfeb5a3de80d16342a6a842519c481522d80aafe65fb24a16393235a34f71
            args:
              - --user-data-dir
              - /config/.vscode
              - --auth
              - none
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
    defaultPodOptions:
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        runAsNonRoot: true
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: esphome
        ports:
          http:
            port: 6052
      codeserver:
        controller: esphome
        ports:
          http:
            port: 8080
    route:
      app:
        hostnames: ["{{.Release.Name}}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: gateway
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 6052
      codeserver:
        hostnames: ["{{.Release.Name}}-code.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: gateway
            sectionName: https
        rules:
          - backendRefs:
              - identifier: codeserver
                port: 8080
    persistence:
      config:
        existingClaim: esphome-config
        globalMounts:
          - path: /config
      cache:
        existingClaim: esphome-cache
        globalMounts:
          - path: /cache
