apiVersion: v1
kind: Secret
metadata:
  name: esphome-coder-env-secrets
stringData:
  CLAUDE_CODE_OAUTH_TOKEN: ENC[AES256_GCM,data:G2pgUFHELXq4aCR0ly408lUbdm2Zp6WyfEkNWBDInjSoghMFi+TkIx6kksDOYdztWAItWexlPPy3bemF5SRExxdoyhfvnZSjlLLkkxoHCgUT3dsHsLbiDKmFbcO7OL3FOaiU51hflbtTsZEI,iv:+AMnZEpYRA/vF0vjln8rivnBUZ8UDkVD/T5GzQUE6Ec=,tag:2TVfwF9/o47LQWp/ubdBDg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOFJFRzBFZUEyQzVjOHR4
        OGtNRVNDOUNNakVIMExmay9Db2pjd1k0VUFZClhNclZmaXU3MzFwMGNRUTdkQk51
        NFp3ZEZMbHd1VFRZamRaK1RuNEJBbkkKLS0tIGZLWXgwRHkrR2dmYnZZdTJWV01m
        cmJ6YXZDamFRV2U0TFZ5anNEQ0IvcUUKTlRZvFfZFe44QjG8qqcV2ObQOneRtGZe
        TG5uBgfL089ByVuCBh2PA1gB7tcYrZgAdAQXVPkh+YpDaQuyJYsDWw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-17T15:26:43Z"
  mac: ENC[AES256_GCM,data:RyJ1eJdXlR5CXvy3hGNMLcDGuk71lPoE73W0BGMok479/gmVcrIqT2Zu0sxTqS8W4OC5jmzSxKycwt9Gg2X9q7jPnRngg96hK1GV7/Hmkn+XAQuwlhpTcBiYjLj0IGaLiIURjjYaXoq4eP/PuZtZxNvlKjY39jnsanVRNCi8Cm4=,iv:YzSKQo6GeJgexlnElRT7DqtEPiXdMWueENIFczMlCXM=,tag:6yMEMSKL3q100CnCbyAhIQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
