---
apiVersion: v1alpha1
kind: KubeNodeConfig
labels:
  node.longhorn.io/create-default-disk: "true"
---
apiVersion: v1alpha1
kind: SysctlConfig
params:
  vm.nr_hugepages: "1024"
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: nvme_tcp
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: vfio_pci
---
apiVersion: v1alpha1
kind: KernelModuleConfig
name: uio_pci_generic
