# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-5.0.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr-trailers
spec:
  chartRef:
    kind: OCIRepository
    name: radarr-trailers
  interval: 1h
  values:
    global:
      createDefaultServiceAccount: false
    controllers:
      radarr-trailers:
        type: cronjob
        cronjob:
          schedule: "10 0,8,16 * * *"
          ttlSecondsAfterFinished: 86400
        pod:
          restartPolicy: OnFailure
        containers:
          app:
            image:
              repository: jauderho/yt-dlp
              tag: 2026.06.09@sha256:8e0091833667d432616f6557e0213e7c221c0db2eec0462b2d98c56ad5f7f9b6
            command:
              - /bin/sh
              - /scripts/get_trailers.sh
            envFrom:
              - secretRef:
                  name: radarr-trailers-secrets
            env:
              TZ: ${TIMEZONE}
              http_proxy: ${HTTP_PROXY}
              https_proxy: ${HTTPS_PROXY}
              no_proxy: ${NO_PROXY}
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 1Gi
    service:
      app:
        enabled: false
    persistence:
      cache:
        type: emptyDir
        medium: Memory
        sizeLimit: 4Gi
        globalMounts:
          - path: /cache
      library:
        existingClaim: racknas-downloads
        globalMounts:
          - path: /library/Movies
            subPath: Movies
          - path: /library/Movies-Anime
            subPath: Movies-Anime
          - path: /library/Movies-Remux
            subPath: Movies-Remux
      scripts:
        type: configMap
        name: radarr-trailers-configmap
        defaultMode: 0775
        globalMounts:
          - path: /scripts/get_trailers.sh
            subPath: get_trailers.sh
            readOnly: true
