---
apiVersion: v1
kind: Secret
metadata:
  name: "${SECRET_DOMAIN/./-}-production-tls"
  namespace: auth
  annotations:
    replicator.v1.mittwald.de/replicate-from: "ingress/${SECRET_DOMAIN/./-}-production-tls"
type: kubernetes.io/tls
data:
  tls.key: ""
  tls.crt: ""
