---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: longhorn
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  # community mirror until upstream publishes OCI; mirror prunes 6mo after upstream support
  url: oci://ghcr.io/home-operations/charts-mirror/longhorn
  ref:
    tag: 1.13.0
    digest: sha256:690516dfca45aa5244622ff383845c38777c2f718257ba1bcad0141aab3a5e05
