# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-5.1.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-redis
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    global:
      createDefaultServiceAccount: false
    controllers:
      immich-redis:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: valkey/valkey
              tag: 9.1.2-alpine@sha256:a0dbf4c1d5708782907c10e2c72deff317518518b5288a58416981d9db95d30b
            env:
              TZ: ${TIMEZONE}
            command:
              - valkey-server
              - --bind
              - "0.0.0.0"
              - --aclfile
              - /etc/redis/users.acl
              - --save
              - "60"
              - "1"
              - --loglevel
              - warning
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - valkey-cli
                      - ping
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 512Mi
    service:
      app:
        controller: immich-redis
        ports:
          http:
            port: 6379
    persistence:
      data:
        existingClaim: immich-redis-data
        globalMounts:
          - path: /data
      acl-config:
        type: secret
        name: immich-redis-acl
        globalMounts:
          - path: /etc/redis/users.acl
            subPath: users.acl
            readOnly: true
