# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-5.0.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dispatcharr
spec:
  chartRef:
    kind: OCIRepository
    name: dispatcharr
  interval: 1h
  values:
    global:
      createDefaultServiceAccount: false
    controllers:
      dispatcharr:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/dispatcharr/dispatcharr
              tag: 0.28.1@sha256:38ec7bdd8d4f784b442dd88a2a21165fddb60567b3dfca062adec82c0428432e
            env:
              TZ: ${TIMEZONE}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health/
                    port: &port 9191
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 6
              readiness: *probes
              startup:
                enabled: false
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 2Gi
    defaultPodOptions:
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: dispatcharr-gpu
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: intel.feature.node.kubernetes.io/gpu
                    operator: In
                    values:
                      - arc
            - weight: 50
              preference:
                matchExpressions:
                  - key: intel.feature.node.kubernetes.io/gpu
                    operator: In
                    values:
                      - xe-igpu
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: intel.feature.node.kubernetes.io/gpu
                    operator: In
                    values:
                      - arc
                      - xe-igpu
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["{{.Release.Name}}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: gateway
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      data:
        existingClaim: dispatcharr-data
        globalMounts:
          - path: /data
