apiVersion: v1
kind: Secret
metadata:
  name: lubelogger-secrets
type: Opaque
stringData:
  POSTGRES_CONNECTION: ENC[AES256_GCM,data:vaJ9SIABDk134IjwXna1sO3IzfAOZi/BrnioWamr2I/QRC4/Pc12xWHMWhvkE5R7uKM8NDy8Cqlvu7+LoIx8R/C4WQs3iit4Eh0YU49eFctE/+lGfC0QklHzs+kCHYB+q72gY9ccY1a+z0lFhjmHYFuVWIb8Ib38oBnsombGZ56IRBCIW660MF3zq0+E9CbfpflhRfgS4r7gpal6nPybspFNjg==,iv:OLdxe46OE3q9KHKwG4DtyWU/D1+8y4KOoF9mUtruQQk=,tag:5ayxWW1o90psJrH8PcAbVQ==,type:str]
  UseDarkMode: ENC[AES256_GCM,data:t9iyQg==,iv:/btLiZBHocqtFEIb7lcsMlw+eJGWaNpjN+hPFBwSqJQ=,tag:6xyRfZqqnrjCDkYMsbxlrQ==,type:str]
  UserNameHash: ENC[AES256_GCM,data:l8QJTVlnQjXLe69qY4oF02K9DUFuYeJ1WpEUBYmvXEGGYeTIbY6yHg7VRrGxJpHGvQHufh7iX3sZhfIydGK2sQ==,iv:+24BWD4IaEq5HhgJ3QDRhW6t+Swj/qvc7ijZpzzBdHI=,tag:EAcZTKtaJxoRBvG4FvHG8g==,type:str]
  UserPasswordHash: ENC[AES256_GCM,data:RZSwXWYmC4kWbGI+lcfhJNEjYHQLdDVRtD5s4PDiK7rTE3udGm094eGIbApXm96nWvWa/QgvwEjDnPFqORbcSg==,iv:1jvQdoQgUdySycc2ZV7WmvfeJtj2nRF3sVLBLz++UpA=,tag:q2zV+V7/YO+pOxqLKgRujA==,type:str]
  MailConfig__EmailServer: ENC[AES256_GCM,data:A2rsYpRyT63AsTf769UA6zBwNnHnoxxiHShrDIwB1ZFY3Q==,iv:+58Byg/NDKJoY0xyQwknwoRc/d7jQYd6SVvHWNtNq6M=,tag:7pl4YPRyHn331fcXp3ny6A==,type:str]
  MailConfig__Port: ENC[AES256_GCM,data:MY3U,iv:v1LjNaMMAUcd+JHfbjL6Crm0S1/F6QS2lxW8dYuUNCw=,tag:/C47ofr5hFp0zbbQhrTE6g==,type:str]
  MailConfig__Username: ENC[AES256_GCM,data:p4HxotLaeEgSJxGvRl7FUu2Bnp0=,iv:nq+zta43Qh8UYg0JTNe1Ax9z6Ap2ORDqzXBMAq6gLb4=,tag:Y00o+4/F9acIoZYl0HE2ZQ==,type:str]
  MailConfig__Password: ENC[AES256_GCM,data:Ml06B1EJ0Kpv1LsWRri+kTEVAtq50u+QcGwYcI7618fx90YcZiZlJCKmb3A=,iv:E/aH1AIf3nLBmHpQhCG9R3fUHusEARixnWVLMHYdaJQ=,tag:MUjn3/cLEVxbgR0vo1CC6Q==,type:str]
  MailConfig__EmailFrom: ENC[AES256_GCM,data:22sxAHA4U+yhrA7ZdK42Qw6Vt+I81EyfOH+3+rx8AZNQNHM=,iv:VNiYxoErCRfsN2l9km5bof+2pB3BqRq0VcYYoqr8Wic=,tag:G3YXl1oGubg8KrHzNB8tjg==,type:str]
  OpenIDConfig__ClientId: ENC[AES256_GCM,data:Zn+/H1ux2zPytQ==,iv:ZfMJ5f5cVOmk0d/YOt2yKESTjG8u21RB9kQK7pW8bzw=,tag:PaXOOdqP8eVD+p74kVqQEA==,type:str]
  OpenIDConfig__ClientSecret: ENC[AES256_GCM,data:MAKFHJMkDj2TnSjko9q+cdxHHMhl5eKDQCGFk94mBh388gNCQWWoKdyankhwVAVadM1ZAx5Kq0KWR5zpy9szUjRgfajcUj5oViVKfC4W1ruEzouSg7HDjRNp8KADmglZXJV4IEl8/5yzj4mzle2kTdoBvDACcyLzsZCfhEnYGRA=,iv:auwxfZUXx8SJpDsOOBCDDEcxeALtXvlCWgi8qv+LM3g=,tag:O70+J0G7AQXQpzxM/uD4tA==,type:str]
  OpenIDConfig__DisableRegularLogin: ENC[AES256_GCM,data:8oZ5hg==,iv:W+8M8LhFST7lof3qiwoUzQIb7g9AieZWT0K1NRyN8Yk=,tag:xKh1fkWpYeXjlqUK6EliiA==,type:str]
  EnableRootUserOIDC: ENC[AES256_GCM,data:goH8TXA=,iv:qKGA7rrPhvC7LPGM+E3pMJkz0+ISChGkcPpDIBafJP0=,tag:Y1PzeqtnCckVmnD3+kxJNg==,type:str]
  EnableAuth: ENC[AES256_GCM,data:8Vyp0Q==,iv:aY9a/+352HsmVCqgN3xzvsSl00uQajo9qbzvrRa3FwQ=,tag:GfF8YxWfUn7/Nlp0W3onGg==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeVFQczdKZERvSmtNdWJS
        MVdWNVV5M2FHRERrd29qWFRySGFOcjNzbEY4CkhYRGI2Q2d2d3RCUEx2NkxsRXV5
        TVJydTRydGJyaC9ZNVFGYkJpSFpzemcKLS0tIHljclJTNlY3WE43TGtZWm9ZOTBk
        NTE5d3Q3TjZDM251OGdsNXFpVVdhUWsKmKgLajcy529dkBOGcQjiSi5LrBxsZhGy
        7EKQhhCfzzawggCbKCKMh4YaLawo+x60ySR5oqkw4J2Olb5f8WP+nA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-25T22:45:48Z"
  mac: ENC[AES256_GCM,data:5CIDH4lwIMq/aRHeK1QhYKNkYmZ5kFIeR1ZzxcPCGEyIaqY8LIV3duDvtPv5q5rv3gr0ldvajwnxFos69TBshcl34cJMEAjFOVUCkGHpM3ccIKO/fllmciC4CthR3RqPjwLNXwz5h1AdYJAs6xnfA4nb724xHz7mFJqwj4m2zy4=,iv:vwl6RpVhA3bd3Q6R3wd97VJRqorS4MHndhC5EQEjJY4=,tag:w5lT6kdaZCVO1bQloGqD0A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
