apiVersion: v1
kind: Secret
metadata:
  name: lubelogger-secrets
type: Opaque
stringData:
  POSTGRES_CONNECTION: ENC[AES256_GCM,data:n6nRZU22Bt0HSvumpPERU/093XdzYC4PmtIqG0/1pX7czwVj8y2e2ioAqvS6fHiNq1mtImbAw7irn7HiPcMcxw3LQJfMrawrj6EXs89BgSQ02o4RAfX5K7lA9f51JWLA97r5gffHQ7bYIBj1UDVzMkF1LxdH3QTGeAUHcPXq15OMJ4Ed5yH+CNef5i0sIq+OMUBYKHrEhGCkoMHoyzMQuUkVmw==,iv:DS2VRtxrqTBPr9cjIG6EMUfxE+MxdBxSbzmKgj4rOaA=,tag:eNRb4bo0/LEl8uv4Vspofw==,type:str]
  UseDarkMode: ENC[AES256_GCM,data:Ag/dkg==,iv:ibbbN6kXTUC2JkBrh44B+muMF8czNQPnv1NybMXT8oE=,tag:MUzGPfkW+q0P/b1M26V6BQ==,type:str]
  UserNameHash: ENC[AES256_GCM,data:GSkHRwq7ytyIg5Y1dMING9wZbRwFCFmm8nbCH1B3ZyhZcMORnmIWlqSWpd9Ct2uvKIcdPyKSY5G0r95nSbB05g==,iv:2/ETINIJKNFskqHq/i8j7oOipSvqWcizjV9T9AEv8rc=,tag:fro0F2YL3IO33ZDvrMJeqQ==,type:str]
  UserPasswordHash: ENC[AES256_GCM,data:69rLIYp2xBzyu0oSC/qKBwZeZI9zJGstPhT3rkJSbrAdlfY93ajkhYrB8/ZFfwNDrFxJlZh1XF2fyv0T8a8KJw==,iv:XThQs/436UEb4xx9fyXKxC4XWgfIcaYJ0oSRpuK0wT8=,tag:h6fstVG8VmL17vVZFQLbCg==,type:str]
  MailConfig__EmailServer: ENC[AES256_GCM,data:lZ4Q7+dMmzD6T4sCa4RS19vZAsKBEbj7/wUxxQUfjqjeSg==,iv:BncS8Qu23iejZDbxRNJ0iAfmLSW75Lacu6YUCk6WMZM=,tag:fZria2yaNLkp40eLmp5ivA==,type:str]
  MailConfig__Port: ENC[AES256_GCM,data:1UUE,iv:rwJSY9qLk8nYZfD2rz7iPE0HJLINlSuUlIaV33O72hU=,tag:JLYoJ2M4UHmjwTyViQ0yUg==,type:str]
  MailConfig__Username: ENC[AES256_GCM,data:vGY1JA0f5fDARBCi+Qyln1JC3+4=,iv:iInvPMwVEBJIES4iqyHWXlQBVfv8MYZqsPyw/l8PBwk=,tag:mC8XkJofdAFowbbNDHJI8g==,type:str]
  MailConfig__Password: ENC[AES256_GCM,data:Dbo31X5MbaZm3T+1zJ+3qk37hxHI4I3tnUrXdI9H8Ag8LBp5Qk1+XAsUFoo=,iv:Ugw7aUuMKMqfNDr9YPhYj8xx8nE7YPSF0IT79bXuj+I=,tag:fZBZxIOgzY7TzRaMfoXcmg==,type:str]
  MailConfig__EmailFrom: ENC[AES256_GCM,data:QE15QB/NnZNdfcMqWITWEYFIU75Q7zaMPcbfvWYsL1INDgw=,iv:03m/Aa9M2ZVz8/n0soEsy1xUP34NJjYYNeTb/rKA16g=,tag:qYEQfof1k3rce+8hwwgd1g==,type:str]
  OpenIDConfig__ClientId: ENC[AES256_GCM,data:f6xxlip/r3mVXg==,iv:7Ubb46ev6eqT6Zd22JpnB69yT1WPidz77jmGoOOPnWs=,tag:meFvcihJw1uKcNzseoAXZA==,type:str]
  OpenIDConfig__ClientSecret: ENC[AES256_GCM,data:v99TbYwa/atAwT/dYIBr/IfzBJDfQXYzUEJWW+hFnL21ODGrV29Z767G2+S13HGgMmVg7vTB+pB+BANsq/fPvv0wuLx/B82Fym0oBtktCObMZR3pYphDD3SCqF4VM90cOVzfZ6AzYAWsIbvK2QEttUHQtclre7NZWTWzPPUqD4c=,iv:0HYRvROETV/qQrztNDvCUOVVNtjq3tfDs+8RVAeDwYg=,tag:bpZG15cNBst745qTUMTRgw==,type:str]
  OpenIDConfig__DisableRegularLogin: ENC[AES256_GCM,data:Rx97U9I=,iv:yfxcuU46eA6g1etr1Xe+yx7WW/tAKVsrBCMBnzf5hgM=,tag:x20xiYMuKgb7q+fQTm0LlQ==,type:str]
  EnableRootUserOIDC: ENC[AES256_GCM,data:x7ZF130=,iv:i43ru5Dwe4OIxYPSC1h++wtiD04LVtP69+GQr2uJnNw=,tag:XqLj4OIrnOGE/bYpSF5Buw==,type:str]
  EnableAuth: ENC[AES256_GCM,data:wKMQ4Q==,iv:sPGJqCyY33q9DYwMrtRJHHCEwsIioS9DjQzH783+/HQ=,tag:alpVC6SCPNEXAk+FbEAaQQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITUV5QmlMVGVFY1dMRVY5
        c3lRRzFDYU9zLzFoaG9Ud1NGNkJSMmlFYkZ3CkpnWXNCY20zVTgxUDdWTEs1RE50
        T05rUjNRUDBmMkUvWklBYjJZc21GYlkKLS0tIGlDdnZsZ1pCbllCb0VYa2YxQjJS
        MUdBemlyU09ZZVhjcG4yYitxM0dVRTQKLx7avGHPkpbcpRQDUwQOkM1VqnDdUkqh
        jjU+ZxaWgBEJyMH3mXt3wrgvg4KCPJw6t6KYcl9T9/JBo15vLQZLjw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-25T22:22:53Z"
  mac: ENC[AES256_GCM,data:HJSboqmqBEt//ry0VlSJSwvh1wGlV/6k3tSZn6Oqe4xOqrddz0g+FuXsSooX9K8PdtzhsGH6jjBGZEKgniZ1jFOy5FwQgZBX/eClvlw6CEUDAg+x8FBsgkqJY1lfsmgQ7fHhNAY3EBv3QHZ9/u8XxP9PoAAcipM+RwqSDm2rirc=,iv:Nl2GisPGNzfyjwwT/rGjOFN2urCVRJ7ObIHQFBl0tj4=,tag:4tNjhqDNC/wfcPA3a6rlqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
