apiVersion: v1
kind: Secret
metadata:
  name: lubelogger-secrets
type: Opaque
stringData:
  POSTGRES_CONNECTION: ENC[AES256_GCM,data:FG3Ig4OQ1uKu6rRve9vnTqBEMwFuX1K2ls5tFDJ80INph9/8R/wnT0x/HtoMEI8oOnowpzEPEe4uvhfxhIOocqnjkpvFCeU3W/BImKKhi+g4zQzBYDGIwGxn4aMIKy1fx+yYIg0IaZVO6FO2sPEuddSFalw4VrTtob8BWMnCMddC1GWSO4bdfAYyGpUMCOxWM6kFWPmsK5FYAsnwtzkUymURjQ==,iv:LzN2/6dIxnYcm9y26gjIt6VO6/3L2nLVwuR+Sc4uFds=,tag:ZnaYgqDSL7+r4o971/mCaA==,type:str]
  EnableAuth: ENC[AES256_GCM,data:qmYYGRw=,iv:dTfrEff0fVRwmZmYWL8joK698B2q6uY7740nwpFr6TI=,tag:jp1DXknRaWlEE6SYfNZHcg==,type:str]
  UseDarkMode: ENC[AES256_GCM,data:I9VLag==,iv:TDCCL8yxGwUwgeeWlBcEDLKBvZkeASnBbfkYuVjuaW4=,tag:GTvYMv8pXwFMiOu7ILSMvA==,type:str]
  UserNameHash: ENC[AES256_GCM,data:uQ+ZiwUYNOEQNsGwsghe3fl1fAZam0mojRmMyWK/KvVcAPykAhHq4st/FGEPCY0dHwVSHLsnEXlkgCnPVHQi1g==,iv:XwPgyjo5vYSWguqqPSM7iALTmIBf9vvLQq+u2V+AD+c=,tag:1Bla4NbfDUiy00rbHCx9Bw==,type:str]
  UserPasswordHash: ENC[AES256_GCM,data:DVC3NB9IFnXsamStGH281l2l024SczbeVQ9SDQSTL3Dh23ibyDHpusZH4N65/q+yxdVqBNy4SBJ+oag+sORBNA==,iv:efn9gkduoVcF2w6v+p99Ak1mIzNbLsKFIA06pHq4ncw=,tag:RK9EEBZkAca0IlLSnBZ46Q==,type:str]
  MailConfig__EmailServer: ENC[AES256_GCM,data:ARGEEO9sGtifL2S2adDoZFVKaFb8mU/s6qrTq6oeP0ti9Q==,iv:v7833KevMNSoSv0dYm9EFWwbyUphYL35R4fiLbebQlQ=,tag:6fcntJw6Rxt652/DywCs0A==,type:str]
  MailConfig__Port: ENC[AES256_GCM,data:znJd,iv:bBf0q9X87MqSt3Yhoc8FmphHfY4y9cuQ2Ck2de+rDM8=,tag:tX8oRtAbQaBKcGgjW0YyFg==,type:str]
  MailConfig__Username: ENC[AES256_GCM,data:Lz5JO/upilwhv+2Lsefu09hIFJk=,iv:FCgKzCBtFKi29BzMGojkbo02/QFbdds6fuLVSdeTuas=,tag:2RzRssOo+WAgCWouRCBTPQ==,type:str]
  MailConfig__Password: ENC[AES256_GCM,data:8viLSGHZi2/0cxDMtEBn6w9ky5XSulpZjaO/i17po4x1S3EaHYpy8C49r2M=,iv:1sQhAOKlM4hQztycZ45KdFK9SJyLmziYMcCFfOktvzE=,tag:VtiOMVpLfDiBkrCmBZioUA==,type:str]
  MailConfig__EmailFrom: ENC[AES256_GCM,data:+41aavFX2MB+iGrYwlcglFP2O6uSpAqJC44Ya1wHEoLuEfI=,iv:B+OUeQnDAse9m6ls0cOe/fU8ELjFXjPAXaZSXU6U58E=,tag:Kef0ZlYFRKy94pbRZXpZzw==,type:str]
  OpenIDConfig__ClientId: ENC[AES256_GCM,data:LCCsZE2Rmlox1g==,iv:JgSeLj4SBvzy51yzukKZF6UqBl2vHM6B4RPtMvE68UQ=,tag:wgI2z/6KCFywqDAaR+gqwg==,type:str]
  OpenIDConfig__ClientSecret: ENC[AES256_GCM,data:BqrJ8f/+x2DKIehBFJARPYzRQK00JwExzaIGwpAAUrNxqlz3tnYLSZwXiId5hZ8SiyXHtTJp8uSB6U8BkRyNNrlhu3cDHh7bbA9x6T/z6C+280QDG+uH64lYSTxo7exn+2zdR0/IP1E77PU5xo2Jnwvll7xWK3rvvlV86sGTrAs=,iv:2RI51+Jxj/UJxkzTs1C1qV24zRYPdPVDYjjxY0WEb3U=,tag:ItQQiCEt67wvHcVrqXSmCg==,type:str]
  OpenIDConfig__DisableRegularLogin: ENC[AES256_GCM,data:+igK4Q==,iv:cNb1oTedPJe+/NLLsLDRRdG0McCfAH7H2EFyOFEukX8=,tag:LpNaqoL85TBJUExc+ySf9w==,type:str]
  EnableRootUserOIDC: ENC[AES256_GCM,data:eAkX6A==,iv:e+jol+KprziYrVqSG4mC+1CM7C06nu2jNPVHdsXmkgI=,tag:Jm49O4cOikiK+nCkuamXWQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVVM4SHJqaHBzdnZ3UGpT
        MGpIVkd4UHlBZkk4STZuMEd4N3k0WHZqakhNClllQUZ3OUN6VFovbnJzb1BWaXhB
        dHZHdmFBVXk2T09zd1Y0RWh2Z1htOEEKLS0tICs3N0dvdDEybGdWV1l5OEczd29D
        UVNseFJRSVd2SmZLd2d1c0tKUGpLR2sKpV7Dqb40IIFOjiNzg5wCsa2UenKr159A
        IEoxMPtLNFLC6o6uM5Nlq+tKZ5V2aCOimJvImIUsDmYxsEIpvxuJ6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-25T22:11:57Z"
  mac: ENC[AES256_GCM,data:b3CbQVMJdCQJugQa5ilnhMjd9SW+6uANigPzA89jBEemsotWPhwB4jf8LH2JUAiJ+GFsjz2zAwYgFjL2XrDAEEL0c+n+wdUA2OCSaltEjyG2ZiEqEO5gZLWROYTMWj4oFjyIv65dzltEMmpHUR2DB+4cWNOLYLeVsP+ESF3zYjw=,iv:6QCNKI1frmSIvjF/5o8dA64BSfMfTJk20+Yz/XaE3K8=,tag:Sp9LDIdFpY+9Pit8LMLneA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
