---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./networkpolicy.yaml
  - ./secret.sops.yaml
  - ./secret-backend.sops.yaml
configMapGenerator:
  - name: aws-ddns-configmap
    files:
      - ./files/aws-ddns.sh
  - name: tf-configmap
    files:
      - ./files/main.tf
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
