---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.14.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    provider: aws
    env:
      - name: AWS_DEFAULT_REGION
        value: "${SECRET_AWS_REGION}"
      - name: AWS_SHARED_CREDENTIALS_FILE
        value: /.aws/credentials
    extraArgs:
      - --aws-zone-type=public
      - --ingress-class=external
      - --ingress-class=internal
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
    policy: sync
    sources: ["crd", "ingress"]
    txtPrefix: k8s.
    txtOwnerId: default
    domainFilters: ["${SECRET_DOMAIN}"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-secret
    extraVolumeMounts:
      - mountPath: /.aws
        name: credential-config
        readOnly: true
    extraVolumes:
      - name: credential-config
        secret:
          secretName: external-dns-secret
