---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xpumd
spec:
  chartRef:
    kind: OCIRepository
    name: xpumd
  interval: 1h
  values:
    image:
      tag: v2.x
    gpuAccess: dra
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: intel.feature.node.kubernetes.io/gpu
                  operator: In
                  values:
                    - arc
                    - xe-igpu
