apiVersion: v1
kind: Secret
metadata:
  name: synology-nfs-tuning-inventory
type: Opaque
stringData:
  hosts.yaml: ENC[AES256_GCM,data:/PBt9sVZ9lt0vBmPrmU3lYlOOdhpnPKBAGcaA6TvLVCcnHDsuK5FFc0Z4HE8h0GSEXIwqy7jfp2hZXOjijxdWi08eoA4qxbUXMX33CxpHkizHLpul55O8jJsux47QQIYo2Tz/5o=,iv:pxlpsxVol2czzukS6reDsFQv7ACBYDShEerhw9HBXQ4=,tag:TXKgyPQSYCLu6fdoBrA1tw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VHZ0YVNUQ1RlWkdJTy9z
        SDNKN0FCRmpLRXhpK1FqV3NWSmtQalhWYW1FCm1tWnVlaTgwbVdqdzZLdUxrUVg5
        aGJIR2dPNkord21HYWwrYXRJWGZ5MWMKLS0tIGI5NDVhSGVwK2x2a3ZlUHFmYWNY
        Y1p6bFJIeGorRFIyRTYxQjZjUnd4M0UKC/GBjx5TiKu5OVClQACej1Tae/8ThRTq
        1WxTOpNPThZfmY4NO1urjoRjvpYuthgLM4/weA/6AVksojtGQI+Y9A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T19:15:28Z"
  mac: ENC[AES256_GCM,data:+5XTwi/QUU9E5CWY0ABfqNi4b7tHJHtKqXbcnkgs81VvlayyJTpp9eY0yIlX3MAh20RPc7BTNxyY4sW4sMr+WBVLE20aEAc+c/5X+8VPY3f78dQUxZ1URrX5MLB22l8KD3f48RnZOtz2ln8zn5fbmBGybmC/JBsWAj7MePCq5gw=,iv:IhDDkc83KV0UB5xc/Tcocq+LR9ZmwFaXK2tY2BL7A6o=,tag:gqMJ2uQGlXBDgj1fazTKpQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
