apiVersion: v1
kind: Secret
metadata:
  name: synology-nfs-tuning-inventory
type: Opaque
stringData:
  hosts.yaml: ENC[AES256_GCM,data:b53vct40NX+5aKjKzrGxyFCawOFPkUO2Rp4+Oy2FzSmrHlqUTUmHhbBZNJ0tawc7R+nb2ipAwj88IM3TPbsi+dgH0bcvimZUbJ3ppTxkQ3T8BHaHanKXU2Ew64Uoa8ISOEvahbihR9kL3/61w4lUYU+fB8UWrK/eWgc8j3r2iOc/Yr1e4XVZRyqQYap8YOssPcUw5Ibnae+uYoNFqvF6FtbW03WXsoBkqioCYAT2A2P0v/rU,iv:I56KQ6NbU6JXDig39xMT0KCbZGN6/LGFR2otiRimu90=,tag:PwISyDRtXbmKR755T84Ifw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VHZ0YVNUQ1RlWkdJTy9z
        SDNKN0FCRmpLRXhpK1FqV3NWSmtQalhWYW1FCm1tWnVlaTgwbVdqdzZLdUxrUVg5
        aGJIR2dPNkord21HYWwrYXRJWGZ5MWMKLS0tIGI5NDVhSGVwK2x2a3ZlUHFmYWNY
        Y1p6bFJIeGorRFIyRTYxQjZjUnd4M0UKC/GBjx5TiKu5OVClQACej1Tae/8ThRTq
        1WxTOpNPThZfmY4NO1urjoRjvpYuthgLM4/weA/6AVksojtGQI+Y9A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T19:45:03Z"
  mac: ENC[AES256_GCM,data:/lkpNze4KFWfoN2QHjc/0jfLgavCx7lfKxre4UT6ariE6EgQ9u6pPAvfe/SA6gchkM3MjpUfmfkxWyNRDjh4NhY8ORjjEhrzIu3TUfLw5AD/IJbHpbzoIhz7RVXLRRitGwuOT14wZOUEwqL8d2gG0o71zbIovvorQAt76EuoFJk=,iv:aIYjj0/AG1NoBlmtouqXwiJk9tzSXAlZ6rpvoB4s46k=,tag:hNr+58VxZjkGysgngEkaQg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
