apiVersion: v1
kind: Secret
metadata:
  name: grafana-terraform-secrets
type: Opaque
stringData:
  grafana_auth: ENC[AES256_GCM,data:na+xONlbvPYRHbj9xwHJ8gTbebkMmgOobM78SMbaqAnaCvbdi2KSQv88Uua5u9fqkXbP517P,iv:6ym67bB9f7DOvBulzE0Y8JyND4yLh1g+haweoIJl/ZQ=,tag:YAoKyc8oAq4UBURavxK42Q==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNVFIK1lRbUMwZDdwNmNM
        eUlBdElwYXl3Q3VoOVNod2dwRmZGdkxkdlhZCllJQ3BqeUNsaHBQZlBIN1ptNEVR
        dC9CV0V4OWdPNWt3Y2xyRUYvbkEraE0KLS0tIHBtekZSMVlwRlVvdlVWNmtreXRo
        ZlovaWNEV2Fzb0lvM0FoQ3ppS3hNWVUKwVUYe/26DoSktkD/ya7XSDQC1gerbSi0
        4atmiYnkANrdHLLX0Hqs5RbQ7eA2EMpde2LZ7x+ubrdU17XWK9H0rw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-09T15:07:05Z"
  mac: ENC[AES256_GCM,data:vOk5rcIlE+cV0xWxnURWQ5mSjB6V1JCESLYpdT6bCHC5hauoJRYGCqIVxilXd5H1Ra8N8j+1cHhuaIPgbVIDjv/fy6Qo5Uwj2F2OMOXWU6qqvU7wlfA6JphmSS3FsHKBn1Jk+J2yOJz8n61bevHqElQq5JMfXDtenPp9zIZhmh0=,iv:KUeJoHCmyZ9dqIY+0J7Pl7zN9WpAu+dcGGWHUT+XggQ=,tag:6VM2giHH/S5UCPR+sBKg8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
