---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx-internal
  namespace: &namespace ingress
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.10.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: nginx-internal
    controller:
      replicaCount: 1
      networkPolicy:
        enabled: false
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "internal.${SECRET_DOMAIN}"
          io.cilium/lb-ipam-ips: "192.168.0.20"
        externalTrafficPolicy: Cluster
      ingressClassResource:
        name: internal
        default: true
        controllerValue: k8s.io/internal
      admissionWebhooks:
        objectSelector:
          matchExpressions:
            - key: ingress-class
              operator: In
              values: ["internal"]
      # Required for Authentik
      allowSnippetAnnotations: true
      # https://kubernetes.github.io/ingress-nginx/deploy/hardening-guide
      addHeaders:
        cache-control: "no-store"
        referrer-policy: no-referrer
        x-content-type-options: "nosniff"
        x-frame-options: "SAMEORIGIN"
        x-xss-protection: "1; mode=block"
        x-robots-tag: "noindex, nofollow"
      # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap
      config:
        # See instructions at https://goauthentik.io/docs/providers/proxy/forward_auth
        global-auth-url: "http://ak-outpost-authentik-embedded-outpost.auth.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx"
        global-auth-signin: "https://auth.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$scheme://$host$request_uri"
        global-auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
        global-auth-snippet: |
          proxy_set_header X-Forwarded-Host $http_host;
        whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        block-user-agents: "GPTBot,~*GPTBot*,ChatGPT-User,~*ChatGPT-User*,Google-Extended,~*Google-Extended*,CCBot,~*CCBot*,Omgilibot,~*Omgilibot*,FacebookBot,~*FacebookBot*" # taken from https://github.com/superseriousbusiness/gotosocial/blob/main/internal/web/robots.go
        custom-http-errors: 400,401,403,404,500,502,503,504
        enable-brotli: "false"
        enable-real-ip: "true"
        enable-ocsp: "true"
        force-ssl-redirect: "true"
        forwarded-for-header: "X-Forwarded-For"
        hide-headers: "Server,X-Powered-By,X-AspNet-Version,X-AspNetMvc-Version"
        hsts: "true"
        hsts-preload: "true"
        hsts-max-age: 31449600
        keep-alive: 10
        keep-alive-requests: 10000
        log-format-escape-json: "true"
        use-forwarded-headers: "true"
        log-format-upstream: >-
          {"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr",
          "x_forwarded_for": "$proxy_add_x_forwarded_for", "request_id": "$req_id",
          "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time,
          "status": $status, "vhost": "$host", "request_proto": "$server_protocol",
          "path": "$uri", "request_query": "$args", "request_length": $request_length,
          "duration": $request_time,"method": "$request_method", "http_referrer": "$http_referer",
          "http_user_agent": "$http_user_agent"}
        proxy-body-size: 0
        proxy-buffer-size: 16k
        large-client-header-buffers: "4 8k"
        client-body-buffer-size: 100M
        client-body-timeout: 120
        client-header-timeout: 120
        ssl-protocols: TLSv1.3 TLSv1.2
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: *namespace
          namespaceSelector:
            any: true
      extraArgs:
        default-ssl-certificate: "ingress/${SECRET_DOMAIN/./-}-production-tls"
      podAnnotations:
        configmap.reloader.stakater.com/reload: nginx-internal-controller,nginx-internal-custom-add-headers
      # topologySpreadConstraints:
      #   - maxSkew: 1
      #     topologyKey: kubernetes.io/hostname
      #     whenUnsatisfiable: DoNotSchedule
      #     labelSelector:
      #       matchLabels:
      #         app.kubernetes.io/name: ingress-nginx
      #         app.kubernetes.io/instance: nginx-internal
      #         app.kubernetes.io/component: controller
      resources:
        requests:
          cpu: 10m
          memory: 250Mi
        limits:
          memory: 500Mi
    defaultBackend:
      enabled: true
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 3.3.0
      extraEnvs:
        - name: TEMPLATE_NAME
          value: lost-in-space
        - name: SHOW_DETAILS
          value: "false"
