---
packages:
  base:
    - cpufrequtils
    - curl
    - dnsutils
    - gpg
    - hdparm
    - htop
    - inotify-tools
    - iptables
    - nano
    - tmux
    - unattended-upgrades
    - vim
    - wget
    - apt-transport-https
    - ca-certificates
    - conntrack
    - dirmngr
    - gdisk
    - gnupg
    - iputils-ping
    - ipvsadm
    - libseccomp2
    - lm-sensors
    - neofetch
    - net-tools
    - nfs-common
    - nvme-cli
    - open-iscsi
    - parted
    - psmisc
    - python3
    - python3-apt
    - python3-kubernetes
    - python3-yaml
    - smartmontools
    - socat
    - software-properties-common
    - unzip
    - util-linux
  gpu:
    - intel-opencl-icd
    - intel-level-zero-gpu
    - level-zero
    - intel-media-va-driver-non-free
    - libmfx1
    - libmfxgen1
    - libvpl2
    - libegl-mesa0
    - libegl1-mesa
    - libegl1-mesa-dev
    - libgbm1
    - libgl1-mesa-dev
    - libgl1-mesa-dri
    - libglapi-mesa
    - libgles2-mesa-dev
    - libglx-mesa0
    - libigdgmm12
    - libxatracker2
    - mesa-va-drivers
    - mesa-vdpau-drivers
    - mesa-vulkan-drivers
    - va-driver-all
    - vainfo
    - hwinfo
    - clinfo
    - intel-gpu-tools
  longhorn:
    - curl
    - jq
    - nfs-common
    - open-iscsi