apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secret
stringData:
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:oCr4iM4cdkm7T0wg+ndcx4r3JFDgN/euaaIbgfWAUR3dB3AZpVZUzMcMxeFFY3Y9,iv:+4i+TLkh0sqHkM9PIq9eBUFZalaUD2H4LE+dUabdeyM=,tag:SwLiILAU8bA0AC+EdYvB3Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqM1hRK05sNGdZNFJKZnQ1
        K1VPa2ZpWU1lMWRCYndnWXMwVjltcGNCUG5NCmVJdnRYa0Y2QmhFU2xqUjNRZ1Vs
        OTJnTWpMYUwxSG94V2tiYW1helF2RFEKLS0tIDFHWWRGU0VWN3FZdWd1VVFSa3kz
        ekhtRThCQndOWXRIaUpPWXhtTmhSeGcKPl/vBase+oAFPoZw8o/xbfswyAD4y+Rn
        yfn72glzC1DAz4RZSUql0Csyq+apwMsQun4+spQyxIum6D6P0A4ozw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T21:33:48Z"
  mac: ENC[AES256_GCM,data:2bbSppkzqBuiz3sGvI3F6N5cdAP4QjB8Xqf/R/yB+rGkDETSPacMxE7Y/24Gunof+K4RHIK3NCQdE+Gbn/hAPgT5wab/6qc6/w1E206QLk/ma01N7u5Ldd4z+0OJ7anTG1Gmmftz0ofdnmqWlwJksitspLBX+qv3WvPhudE3xUM=,iv:9ZJtOQOhFntAvJai1MTC0znROCP4wenuOBUsn4Mnops=,tag:JBCOOFZ/dEdQ2+uXWXuM8A==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
