# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-5.0.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  chartRef:
    kind: OCIRepository
    name: sonarr
  interval: 1h
  values:
    global:
      createDefaultServiceAccount: false
    controllers:
      sonarr:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sonarr
              tag: 4.0.17.2969@sha256:1989718e9fceb3fd35b4e73f61696c68f8959b8f09981cf137fdef8e6338b85f
            env:
              TZ: ${TIMEZONE}
              http_proxy: ${HTTP_PROXY}
              https_proxy: ${HTTPS_PROXY}
              no_proxy: ${NO_PROXY}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &port 8989
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["{{.Release.Name}}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: gateway
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: sonarr-config
        globalMounts:
          - path: /config
      library:
        existingClaim: racknas-downloads
        globalMounts:
          - path: /library
