---
- name: Cluster Labels
  hosts: kubernetes
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: Label nodes for Cilium Clusterwide Network Policies
      block:
        - name: Cluster Labels | Check for pre-existing 'ccnp' node label
          ansible.builtin.command: "kubectl get node {{ inventory_hostname }} -ojsonpath='{.metadata.labels}'"
          delegate_to: k04-master
          register: node_label
          changed_when: false

        - name: Cluster Labels | Label node in Kubernetes for SSH access
          ansible.builtin.command: "kubectl label node {{ inventory_hostname }} ccnp=true"
          delegate_to: k04-master
          when:
            - node_label is defined
            - "'ccnp' not in node_label.stdout"
