apiVersion: v1
kind: Secret
metadata:
  name: tracearr-secret
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:xpqPTgND3lvRPWr64Ig37Nzy7DIB7Tb+txKThvbNIecAGRuB7l15hujv21hvMPeNZ7hbwxOWzlp7MxVSv/xlkqsbsUohtgXDhycgIYpONxDGSS8BDF2qiNlCcSA3WG+B7a24wyHXahXmr5OezL59O/ETBWBr9sUrK4fxdyoBzhs2TlawVAwZLMWIaAo=,iv:Mb9dG0CiDmNFXVT1yLesXcSAduwi7PDiXap0ygAFd3U=,tag:gNUAGI+xV9umsxrJWhcX8A==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:cWosjiODSdqUYq9pGMKifJ3IFAK4Pn1HyKEMN9vSMFcdcaCgjDhFgcCAay9YDf1AC9fR+u5g1XH+BVgcFsoEcaqde0Usxp4OjvA0UEwjIIsoApQpDx60sTQE9QNrlLUFQJzlx/K1fub/rbJtHLVm5Bo5gHR9CDtv,iv:c2QACT7/QZMDi6B94/pObZIh4xGC7xE1HF95SF1YERI=,tag:LA4Abauz06vx0KfLbvjBQA==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:Uyfb7Zx6s1gjGORAWKp0R2Kk0pRmo+A0JROC+xrkSn9GRtxiH2SFYekLZ1pBp8Yk8yXASRY7wCsiGfBkaq8oIA==,iv:HZ4Z/Qw2+AEMVdalaoFi8S7+gMgQ0xox15Py4b/WD/I=,tag:AnN+ING4zoJXeYeog/PsyQ==,type:str]
  COOKIE_SECRET: ENC[AES256_GCM,data:ZFYw4lWCmh7AbEyXcGBxUkb5Sd/UA2bdnux4pPNSCuG/G+kylC69vkugPxmpnp/8x73VuuiXWb6kuMm0UcpSaw==,iv:b8/GFuqmwWcajzJZWE0iEOtMDkv0saU/5OVz1LUyuBc=,tag:/zwj4hfAbFTd38jXpq6lTw==,type:str]
  BETTER_AUTH_SECRET: ENC[AES256_GCM,data:NYPqSJ/9ZHQ5irWf2MPWb9/0JYxqnFtO9sBCUdyu3WlLepoaykE8IdK1nsuNBBo8X8Apb7ETRP8j1KVDjTUv3A==,iv:oy0liZAmM5jsrwnqN4Fm9gAgfw4Wio/UtWjLOb8lhPA=,tag:OAajRYlAzoFQejlFjxQRvw==,type:str]
  #ENC[AES256_GCM,data:6TaC976GsdWUIwswneGRlgWSvinFoMbcRFVXQa/W38XqyfXKlp9iycKqSrDjYAAB+b9sG0/bUaBubjIAHRWUWzsJ4pkkm+4V82A=,iv:EFY6TRX9SWzMo51Lz0qA+M+flSpCgMUsrH4cDhhEiHQ=,tag:Xy7pfoHJptVWNNdbKPbeSA==,type:comment]
  #ENC[AES256_GCM,data:ClCyMFMal7+betCC335UFyMFuRXiVu1ckQKm47+Arp1ShhCcuWw0ls9zgTgrVP+ZMl5l7Gl4V6UThSZ7Mwc/z9++ycoF4hhU,iv:77+N2EFNMCSwBXAkRB9mtOHQ8hIaVa84H17rCoK88gg=,tag:Z1TF0NC7lXjbp0KQQG2yTA==,type:comment]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5L0VBY3MreTUwN2FETmVm
        dUdrbDFFUXRYSkdmK3VGbXNPQXBDMFNZdDBBClNZZDNKbFJYSzBuWFM3OU11Mkdn
        clFQVG55aEZGeGZ2VnVKUWd0endiaW8KLS0tIGZzZE1TRnRFY29kbi9iM3ZJaVAr
        dGhEYm5PZFZlbXFIYnZ2dW1Cdks5eTgKrubwxqFfBYb0tyO6wrn2nqe4UWdaY2hl
        YU/NbQFxuSswMcX1R/GaUie5uULb/KYNYBQVDyyUsf3twKLuq1mdtg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-08T03:59:34Z"
  mac: ENC[AES256_GCM,data:eUQQXZ9cfdtLzbBALk3iJ/mMYG7f6Bti6gWMvo5noDF4zj85T/ZoqW1VA1vkMGK6DKhRzHVNi+OKPf3Bvne1v9v3gUbhoaNaYYrCuo4enn3LbeqEE0YY92dIbGqQLXptXGrXWuzylMZVknn/Q+WJqrakRffOgxneJKu8lSU69j8=,iv:2H4EZ5osEOaBDEnk8kpdTZMLlAlT01bid8u2R4XqYeo=,tag:U7tNdcYCCdI522x4Ita1Rg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
