---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: netfetch
spec:
  interval: 30m
  chart:
    spec:
      chart: netfetch
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: netfetch
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    replicaCount: 1
    image:
      repository: deggja/netfetch
      tag: latest@sha256:82152fe952f5231b55ac32ac7acd331815f471543f2764851ccb21f20d9e1e2c
    serviceAccount:
      create: true
    rbac:
      create: true
      clusterWideAccess: true
    podAnnotations: {}
    podSecurityContext: {}
      # fsGroup: 2000
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      runAsNonRoot: true
      privileged: false
      allowPrivilegeEscalation: false
    service:
      type: ClusterIP
      port: 8080
    ingress:
      enabled: true
      className: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        hajimari.io/enable: "true"
        hajimari.io/icon: simple-icons:antdesign
      hosts:
        - host: &host netfetch.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - *host
          secretName: ""
    resources:
      requests:
        cpu: 5m
        memory: 10M
      limits:
        memory: 128M
    autoscaling:
      enabled: false
