---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: flux-errors
spec:
  providerRef:
    name: home-assistant
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: "*"
      namespace: "*"
    - kind: HelmRelease
      name: "*"
      namespace: "*"
  eventMetadata:
    cluster: home-ops
