apiVersion: v1
kind: Secret
metadata:
  name: flux-alerts-home-assistant
type: Opaque
stringData:
  address: ENC[AES256_GCM,data:vteYvVnqhKHQQtLEixrj3xX/5m2ffSNCAWbqwla3DXjQwRtwG94HTbsasZMIM9aawrnCujlmap1C6xUjP8V2BWNFupI3qcWhAeUaiI8dXWBirx3xTAM9VfB0Ox4=,iv:VKLLYgYJilPNzLbaNeH/vdxgXTKfu+6PQGhOqqvbwxs=,tag:MN4wu+kt6hjkb+tf0R6CNg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzU1JFYkxrbkVuSWtRS1Bp
        UHQxV3U4OXVKL0duK1hMdm80VVh1aHJRQkFNCkt3UFdhY2I1NWZTb215Q3VVRmFl
        N0R2ZU5iOURwcmFLaUpBSVR1M3VUVDQKLS0tIDUva1hIT056bXE5UE9jbjV0Nno1
        aXdqbDlpTGU2VlBHWXVyMGNIcVF0bzgKFq1oB16RUvPTfH4aXUaEpjgXmHl9SBAw
        9sVayfACgVY24XV7Wa7UCawyC8dBbn2ToVMRbSXewqwMTSI9BYPk0Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-03T06:04:41Z"
  mac: ENC[AES256_GCM,data:riZ5Uem+WrkxT1cntklyEPqg9ie9N5omGu7UIG7Zx7eNrkjRE8RuXtgHrJufJ7pH20bgWZ4qcBxB6qdAkIxEfdTeGejtjM7U8UXpgIsdCSxANIbhZQ8cvQRgZTBibcfCV4EXdp0tPszFv0cDSGUdGvT2bhdQtbpzT0TEk82SmRs=,iv:97cUf5Lo4bN4nhwQJsXhWGay5x3D0X0W9QjSzzVheLs=,tag:zE69XObIqGaFrx1nowZ5Ug==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
