apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    config: ENC[AES256_GCM,data:5OB4ZNxvgl+l6QXKmFaxGCVlOF4uk6qx6/Pyj9r+,iv:4I7mClS9dNx5JKYpzYr91JM426KPy1TMvwLTziCjnXM=,tag:2UkGoVHXssQffUOi6Ij+SA==,type:str]
    credentials: ENC[AES256_GCM,data:8Boiaymmia7FxAGeZXtxuRjzV66r5eT8t0IIoSsM+HbtcOEI7bJGd3WMmvwoiEffXVTbfGHuaVF8OZCwu94Td+yX0prYFrL5LIuKuHohihVXvhPvUMgGP4U4X23wIXp7VUGg/nPB8VlmNAXpfcWtzZjeEez9bS4=,iv:eWEUQlsdL0hXsVFwM0rusWiOVF5S/E7JAx81d72FEeY=,tag:qIn27EmujYzfvOtHWcZ/Lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16m88gc43aqkcnrftkrx3j938vgu6xl4v3jjt7jk4f39xvm5ck48qzj5696
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUUpMQjYwUmdVbXpXRWdK
            bk95dm1WTjYwQWdJOXlRWTNiR2NOSXpQaGtJCmlpL3hNQWtXQXhtc2w5dHYweldj
            OWFXRlREK2I5V01Hc3Mvc241TWJzTFkKLS0tIGdSYVVjNGYwcDlhS0pQcEZPdFhw
            VjhRYmRiYUdmMTR0QURGQmxxb1l5ZDAKpymDZjSOVqF5yRZxSh4ynNJtYDVq5k1s
            3HeuiLAlct1kKxI8psaGFxT1zcMZMUOWFldvjqniGWaTIhKJM4139A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T06:45:56Z"
    mac: ENC[AES256_GCM,data:u3iOeG+v6g334xZSjonRD+IyNnvPlib5Mg4mu1S+zsTbuurTGbIzs48x8kDVIhLrF2KteZrY0MU+grHH2C/JikFurUlUlXcArYXBpw3tZ91IL1OxJQPn80SeWlvpur5s1ensnU0fxf0EEABayN0Yp8z6GcJusra28JKXZIgiBOs=,iv:veAXMfeuyCFLKh8ktiGElc47gxOCFho8EfjYukGLHVs=,tag:kkWhucNzlVbLFTm0CK9mBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
