---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.0.75:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.0.75"
additionalMachineCertSans: *sans

clusterPodNets: ["10.32.0.0/12"]
clusterSvcNets: ["10.96.0.0/12"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "m1"
    ipAddress: "192.168.0.27"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/0b6deb91fb651b3885f5f703d894096cbb71e9cd59324a5ea84f9919427995da
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e0:51:d8:1f:8a:f9"
        dhcp: false
        addresses:
          - "192.168.0.27/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 9000
        vip:
          ip: "192.168.0.75"
  - hostname: "m2"
    ipAddress: "192.168.0.28"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/0b6deb91fb651b3885f5f703d894096cbb71e9cd59324a5ea84f9919427995da
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e0:51:d8:1f:9a:a9"
        dhcp: false
        addresses:
          - "192.168.0.28/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 9000
        vip:
          ip: "192.168.0.75"
  - hostname: "m3"
    ipAddress: "192.168.0.29"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/0b6deb91fb651b3885f5f703d894096cbb71e9cd59324a5ea84f9919427995da
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e0:51:d8:1f:36:3f"
        dhcp: false
        addresses:
          - "192.168.0.29/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 9000
        vip:
          ip: "192.168.0.75"
  - hostname: "pella"
    ipAddress: "192.168.0.35"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/0b6deb91fb651b3885f5f703d894096cbb71e9cd59324a5ea84f9919427995da
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "6c:92:bf:65:0b:66"
        dhcp: false
        addresses:
          - "192.168.0.35/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 9000
    patches:
      - "@./patches/nodes/pella-longhorn-volume.yaml"
  - hostname: "donnager"
    ipAddress: "192.168.0.33"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/0b6deb91fb651b3885f5f703d894096cbb71e9cd59324a5ea84f9919427995da
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "54:b2:03:f0:a6:54"
        dhcp: false
        addresses:
          - "192.168.0.33/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 9000
    patches:
      - "@./patches/nodes/donnager-longhorn-volume.yaml"
  - hostname: "hammurabi"
    ipAddress: "192.168.0.34"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/0b6deb91fb651b3885f5f703d894096cbb71e9cd59324a5ea84f9919427995da
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "54:b2:03:f0:a4:b5"
        dhcp: false
        addresses:
          - "192.168.0.34/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.0.1"
        mtu: 9000
    patches:
      - "@./patches/nodes/hammurabi-longhorn-volume.yaml"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

# Worker patches
worker:
  patches:
    - "@./patches/worker/machine-kubelet-longhorn.yaml"
