apiVersion: v1
kind: Secret
metadata:
  name: hermes-env-profile
stringData:
  default.env: ENC[AES256_GCM,data:hVcFAz0aS+C5SsSROYP/R1tBAeDUoZ1bW0dNfdV57dOu2jFTO0sxQsLCciVq/Vmc1r/FGTeOQQ5iNgxzTt/L6KipQpj271q6/5NVj83h518JpSdgqcbwrOYGGef56LBJmnwkB9k3GYjy29Zpxh/2i1bGFViXlFJ6zwWzA+/z6o9UFPSrbJl0qN45MNeDaspFgQ4iPU6v7B6R7WKypyj8W+/aW1xs8+Q33BfwVvgtT1GCbh5zM9rIk9A9nKy6QYgKts35zEQV1jbqeFLP2FLNLSOeU61d0StzEUy9Ae9ldPLTGrc/CsTqhn00QaoPyCdTq6oM+mfVzUcw0k0AyoO6kkRwak9GkI1BavwCj8he2tZPGSLyuTbmvyBAMkhN4wNgere/19gKMcQb2jE3g99VKB2l43BDcSM86mHqi42ck/QIbHXpKxl+LZIGs8A1KvI18WNbSj1Br53z3fPUjGGM,iv:xK3aq4EXXOOjZU39yDoqFk8OiyZsHzYoXGzIEiKvels=,tag:5u/Csa8PDrE/FrsDmS1k2A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLR0ZDQjZTUXovKzlDbjQr
        RDlmSkl5L2o4UFlZRzB2elJOVTNMWDNWYlM0CklEcjV2TXNwZ2doV3ZHTW9WdWdv
        dGY4aUV0dmdKZEQ4Q2k3cVFPZjFVbGsKLS0tIElxbVJDamx2TVI3NDd6WUw1bTg4
        eFcybHhsY1FrSjNXQVY4bkNRRGVzS00KKzGQrBHo/y1pqDCmmy9crsbokevgf8Jr
        Ea0vs37kt3I3Y/Rz3GcMcOXMjOgSXcMT/9Sk+Tc9HhiHRIzFh4hwJw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T19:29:25Z"
  mac: ENC[AES256_GCM,data:+iEZ6TDJ8IZfh2mbO+L9CEvdb2vpRJa01p53GkQJVW6FjyajFCGArvzueYKYZvvpoxR1kThASU0sZmrfNSvzafuqXdCpXqLdPJj30byM9KDjYh0F23lcA128+0NDpmR9cftdFScp10669siOZDjBvvmhvfgQYU+RV6Cw3BueRh4=,iv:rceUg37A3QZJyNI7eacjcejMab/Fu4W7e3QG2DBqWpo=,tag:fTZEvIEdr7Nu9K9S51oFnA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
