apiVersion: v1
kind: Secret
metadata:
  name: hermes-env-profile
stringData:
  default.env: ENC[AES256_GCM,data:nKiiEcy802EdtSQS2lgIFeqhYoKf5T8yhWJhYBd23z1yy/qyP/oAHgR44sfxIrgXQKRdYUTiO6VAFiXPe59GGg3C4cyWiPWYqiazATvTy9t2L9p71FAYxzFHrezQdU0evHEDJc8bT9CO0laEQEHQBqMhWNMQ57SAXdSB/LQhtiXUbdBokqWFTUiJCCYHmQivzh9Lh2Lr8oE74y8zES09Ky9cjIJJG2443jR09D6WGjCvBR/QPet0uYoNIZMwIU72HnzUd0Ht0jivWAU55y+Jej40N0hLCm0a9xnyuw1adO3zC/LpqPtKYCkHFMMYvxNcEdvR0XOHVMbQqOZOG4H8z/z9HWvctke2LmPKQvsVDBty9tORj2OVqj7KOWqQj97DzPbFgAlS3WGumWxPZ+wadxOlsLMWbp632WpKbm6P4iEuggus5HhXWKd8OU49g8BxRSVeoU5M8v+yfvvqCA==,iv:c/c5fspP1wa5o6KMSKiffdX/OhjIK0WV8YpzdySOtnM=,tag:yZtvXKHTOtk2pwp1sP2dXg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLR0ZDQjZTUXovKzlDbjQr
        RDlmSkl5L2o4UFlZRzB2elJOVTNMWDNWYlM0CklEcjV2TXNwZ2doV3ZHTW9WdWdv
        dGY4aUV0dmdKZEQ4Q2k3cVFPZjFVbGsKLS0tIElxbVJDamx2TVI3NDd6WUw1bTg4
        eFcybHhsY1FrSjNXQVY4bkNRRGVzS00KKzGQrBHo/y1pqDCmmy9crsbokevgf8Jr
        Ea0vs37kt3I3Y/Rz3GcMcOXMjOgSXcMT/9Sk+Tc9HhiHRIzFh4hwJw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-10T22:16:00Z"
  mac: ENC[AES256_GCM,data:6ScEOOa2zqvv4ug5f1/+6pAfoWKzA6rGCdvjwnuYeq3BmBl9+VvUvDXSyUkp5V3Ht5XfjnAt0QEDfOUugYbd4ex+uQQpx6D2a/RmPuDvphJa4BRHRQZ8TFSz7WdT9Ywtiv0G4BtS80dmf+nlDpujciPMGmTxcKcbjzVtnEVraM8=,iv:pMVJqQwXZEjWOoV6sEPL5vKgYeYLkuPK7uBFlpp+mZk=,tag:R8PRFkdd1btZr6X0l4TWsA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
