apiVersion: v1
kind: Secret
metadata:
  name: hermes-github-config
stringData:
  GIT_COMMITTER_NAME: ENC[AES256_GCM,data:L0IttnRsBug=,iv:JDtLK6RmuqK+W2/K5Zn3xS+FyP4MiOhqQtfvbcujai4=,tag:n03sC7dSJXqZfkvIzbWFWg==,type:str]
  GIT_COMMITTER_EMAIL: ENC[AES256_GCM,data:Nm+9fc9F8BF9EAJ7ZgI05wxZQBZCR0pxofSy+PTsfNdThOfKIZoy+Ao=,iv:e/9V2pg7tq9LrHURhORfK+3yk1A3c7wuwZsBCCR77Q8=,tag:K81dtC5s2oYf4EdnDnxAGw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMV0lxcUhTVWxTTGtHS2px
        SFRkMEdRRmozMDdwSGF2SHYyU1NwckZBTkVjCnFUTXlTVjNHcGw3YmRlNi9KUDRN
        WUYwSi95bEVXY2FZck5lN1R6WlBsNHMKLS0tIFlqUm9MSTd5MEJFaEFlOVBBZzFH
        NHl4Q1IxSXF3RzhmZ254SjZTTlEzVzgKpHlQMfYE1FR4UpaifZTT5fpmazAdtwyq
        gJM92ldY0tnOKruN+I8w6HNn0rICAhrGDuJO5hnGfw1PoT+X60JyTw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-10T20:48:42Z"
  mac: ENC[AES256_GCM,data:95x+2UZGEMtroUkcf/IkwrZ0WHgyRc5JKOk7pZVFVRiEVWr3MwQ86UlYqyIMxUfrYjVcC7x6rBjkwT6Rh+v31UM04obk6Ys8efw+/4/hzY9TjE/qChlDcwcyXtvXJFj8+CQYjnom6AcRO7y2SIhtkxuEIXIg0UxyH4Umf9CKzdE=,iv:WJfuETw78aNVNq8HEURNsCzj5jrDLWA54Xdc/WGVQ30=,tag:c38lu4up3xwVpKEIzAOkrg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
