apiVersion: v1
kind: Secret
metadata:
  name: hermes-signing-key
stringData:
  SSH_SIGNING_KEY: ENC[AES256_GCM,data:+lovqzzDme4b34cMeA0GfkXEvUnX9G8d5o1zFsl5vDhcjzD47PNnZwBCdmvXFxSPeyMK2f732sjZrJqRQwbQhojHYo6FP9kJ/rxh3fZ43YnuDn7g7bh3zGXn6nnU9G7hqm7ObxxKq4R1zGaKkYvi0jfb6jUemmS7ZusU0yti2ZOZxPUvA8sISM4nPzeOZuqkmBH4WU76wggoPY5cKObBUV8xZL2KhCAdqDXxTSXFnQKXBzGvhMKe08CDqDqnTKgrXlFQkhBTUn4PiKKRHLhlY+jdSeE55VfxD3iUOL/mgTOHbLtGbW9hQffaHak7jMAPwv6wsTVl7qaSv2HKzWRPEJm0p/+umiFBAEH2wiTlfDVPzaT1e0X/SFb8Q/jNQAu9RJw6grIoB9kKdtyrHs90KrU+vWxp49CymRsEjSYIHEIADq2mW3kbVxH6KhsTw3CMvcVqdOs+wOSCCyV2HK7WtM8TzHHA866TMeFm7o2YlmV3jMeNQovNONiRlG6pYsx3lHneOUyh1g55UBGIeyve//NG/IXVRjDs2Eg=,iv:EPzk1/SYTU058Y8QXx2rDyAx5N/FRc2kG2Cg/+cmdDw=,tag:Q8PthzOmEV2D5Fi/KjD5vA==,type:str]
  SSH_SIGNING_KEY_PUB: ENC[AES256_GCM,data:tpPABRFSKYXxEhnkOb8W319zmI+pbvSqlAszORtiY4y68gJZUffmvwrBHJ9HVexo2UwdtevMqb2pOJ/tKNzl4Y7dR+uVz75lNgy+YipkcyLLCoZDATrdsmk2fXvJMPFn,iv:OeMTG9TtoUV0HdzmTG1AyqHOUzMS9EoPmOQf4uj75tA=,tag:dZevh0yETT+ITKcKGdvtiQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOUY5bFN6SG9TWlFrdDND
        TG9uWWhac24xZGY4SCtCZzJwZVFGZ0tEcHlnClRFRmpoTEJSakNjNStXUmhIelZN
        Unc3bVVWQmp0K3BiV2xubURQYUhhTmMKLS0tIEdrOXJxWDVWQVhKYjJ6QnBnaGlo
        aU1udUpmeGdocVNGUWFILzh3NnFOQWsKVgFlcFGxRL3rPh5ZCW1nb372fZYNZn5n
        L+9pRFilN35ijPJTmWv/6xcJ1rM6BQK0V5YyHV1FVyeNwxf8QOEY2A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-10T20:36:50Z"
  mac: ENC[AES256_GCM,data:TuCbQfXguFxP/oaIB9KLmGwmyq/eofUrFcKN8XAYDkO/pcM97rEgOYp1LaNiINxo0fomHD2ym0MyGGvbHqATgotz4xC+rXMCujrVjouC6E8vCt2RT9vdasLIy0iYhfOG8nkkNDBAZC8Fviqc8EMzs6x3D/ofl2tfOoQhhBs03QI=,iv:QPZTNMJJgE2hypLDIW9qGAKO0AohysN5flMsFgL1pTk=,tag:gcKrZNosw5FdoGA8Y1Gcnw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
