---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./netpol-host-cilium.yaml
  - ./netpol-host-cluster-access.yaml
  - ./netpol-host-icmp.yaml
  - ./netpol-host-k3s.yaml
  - ./netpol-host-ssh.yaml
  - ./netpol-host-telemetry.yaml
