---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-host-icmp
spec:
  description: "Allow ICMP to hosts"
  nodeSelector:
    matchLabels:
      ccnp: "true"
  ingress:
    - icmps:
      - fields:
        - type: 8
          family: IPv4
  egress:
    - icmps:
      - fields:
        - type: 0
          family: IPv4
        - type: 8
          family: IPv4
