---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-host-cilium
spec:
  description: "Allow cilium ports on hosts"
  nodeSelector:
    matchLabels:
      ccnp: "true"
  ingress:
    - fromEntities:
        - health
      toPorts:
        - ports:
            - port: "4240" # cilium healthcheck
              protocol: TCP
    - fromEntities:
        - remote-node
        - host
      toPorts:
        - ports:
            - port: "4244" # hubble-peer
              protocol: TCP
            - port: "4245" # hubble-relay
              protocol: TCP
  egress:
    - toEntities:
        - health
      toPorts:
        - ports:
            - port: "4240" # cilium healthcheck
              protocol: TCP
    - toEntities:
        - remote-node
        - host
      toPorts:
        - ports:
            - port: "4244" # hubble-peer
              protocol: TCP
            - port: "4245" # hubble-relay
              protocol: TCP
