---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  COREDNS_ADDR: "10.96.0.10"
  KUBE_VIP_ADDR: "192.168.0.51"
  CLUSTER_CIDR: "10.32.0.0/12"
  SERVICE_CIDR: "10.96.0.0/12"
  NODE_CIDR: "192.168.0.0/24"
