# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-5.0.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: autopulse
spec:
  chartRef:
    kind: OCIRepository
    name: autopulse
  interval: 1h
  values:
    global:
      createDefaultServiceAccount: false
    controllers:
      autopulse:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/dan-online/autopulse
              tag: v2.0.0-sqlite@sha256:c9f117a931ab30e8f311c76fa9e0f5340fc1ef8fc1d34593e74efe0c00ec7b84
            env:
              TZ: ${TIMEZONE}
              PUID: "568"
              PGID: "568"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 2875
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: autopulse
        ports:
          http:
            port: *port
    persistence:
      data:
        existingClaim: autopulse-config
        globalMounts:
          - path: /app/data
      config-secret:
        type: secret
        name: autopulse-secrets
        globalMounts:
          - path: /app/config.yaml
            subPath: config.yaml
            readOnly: true
      library:
        existingClaim: racknas-downloads
        globalMounts:
          - path: /library
            readOnly: true
