apiVersion: v1
kind: Secret
metadata:
  name: autopulse-secrets
type: Opaque
stringData:
  config.yaml: ENC[AES256_GCM,data:o3Nmwa+UZUJ6jJroz72iW+5XYf5NEO2Zfn4LSP+qHQjrpeoNEFF46RK3Y9KP46ce1V+W5UySeNOeugQQAGvO8x3BFbDkBInVJRExL9hfcs3qoUtoDvYJc94dV85/COILVDDlTblmHIH4jCmT+CFnpWkGj16hbiaXe6rdRgeUIS3O67qEy1jjvMBy/J/KEE6Zpyf7EPKMDalxUc+h50LF3bjEkPgu3dJjm/3hRzWFyIl3UmGvcSLX0aUWJS84ZWG39dtWrO9WRjYZxmDgiGfEy9FodWU228+mUyM2AyV1OX18CzI9zX+chG1XCIrT+661GoY8G0JxYQ4ynmpTBWs6+EJ67Z+rDALUzsWYk7S+NO1IYVrgN5vzHlhJApfaGCFcvlizY06P/AO+5uP7Ez5iwKET2Zl6Fb1aNDXjNLWaTxD0gNQseRUQKbbP20+WDj+tgmZNovE+rmTUUfJLeGLMMIlzItnwf+0y7WuZZbynztM6X1mryl22LClf8ERTVBI2BxTLVhgBHIKM38Q9WpRs8Nkam9fRV7omj5/QKRBO8nyurk+jwRPKnDW5vhHTcWUTxN+j3jPbFkE5pMP6ndDe5064q0OckjmSXPTv4b+cgEGfUESM8mJcFUklOpNFIJHa3uajbgSa5xqOWEwqsy6o3sJ3eiKcXBtCs/ZtzO9V0sFl82aoPzfOq4Fd+ErYkJe62W+Xq/G3t27ZQjxeznm4fU/hakUSF7jr9XvrTHf75nmW+5SuL10J9xUPeMxuMUtgNI7/jLazqNA4XXnwrgnJqdVjmc265KA3c678o2PaFv+gmIQtMxPmNDAUcOAFc3bER+4pKWC8DHjhQzO36A2y+aCL9l0wCd0jHDi4iUwivR8EP7hw6ICiazHqXNSoGPoQXOH6R5QmQADWFWE8x3sQMkcknDz9I+CMwSVibp4f9EmAclqhl4hFTVHOwW3F23Os5jiMwBgwLKFqruc3wv3ICrnzz/a/sA1wMxMoSji9TUnh+waJSTwTc9bXxyI/H8vmE2c70Cine87Dch46PJ9GyPTm/cRCvqoyVcY8LJwyRFv7VMJEsIIC1bUXYR9Hxt2ysehZXLtPR48exHl7bevb/ZmZUXUVzEGqcepriCq0K0lczIjmoD2OFJsCs5K1ZidUggWcZNicr29hmbeyc1MmNyDXkNPrIZm7at44jjj9PEQSz7hvDx7ZSdSqD5bxF0cOUDjQI8nGE7XhOq/iZfAGeOdWXCb0p/7YgeCT7F0h8Fnhn2JtnHBJ,iv:CfRWNaiRMIJdQFGEIORab2cgBmTlTP5QmFlkjtv8qIg=,tag:zklKIIpufK/3zZ6LRSGd0g==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5M1FqZWcvVjVreFdxZDYz
        d2dadU9yQkRwVlhBNlpzNnY3eUM2OTJGMmtzCkF3M1ordHZFT0d3KzNMVmFtT0VQ
        TXVlN3ZaY2tVQmFFSXhObU5TdmoxUEkKLS0tIC83M0dhenc4Y0VNam1FUWk0RXJy
        c2dZM082L3R3NmxjWFVzUHZ6K3BlL1EKXU/y80m6dkVYvmbNBXW7MG0UL1bc2LoN
        /i9bKZ/DvrByEwEpgyKdjRYDxFT2HefdOAns1GQpRqQnGBhqSo/y1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T00:03:54Z"
  mac: ENC[AES256_GCM,data:kDykDA7wCZZCrFLEQFcsS29dY+GelWAJvrU/5y+gke61peuiD/VxSWHMEVcep6LIWcjJlEhdVrrhI5rJahtmUsbXB4uaSFBCMyj1Q6YVmypfGdMMcll5Hq8L28wkMv7utopFRpxK7GtvT/3BKc0b1xCWRtM3W/3pnUrZqlkARtM=,iv:CnObjnWf+69U24JQm18E4fPx+CqooZsqA9EED7cNxCI=,tag:YbLDEU9AZGjVhBHtj7TvZw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
