---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &name kubernetes-replicator
spec:
  interval: 30m
  chart:
    spec:
      chart: *name
      version: 2.9.2
      sourceRef:
        kind: HelmRepository
        name: mittwald
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *name
    image:
      repository: quay.io/mittwald/kubernetes-replicator
      tag: v2.10.0@sha256:a5d7246f8ebfc2a9a3ecc3a53c3d5764b952966faf3d5e20f98cc0e49f444c7d
    args:
      - -resync-period=5m
    grantClusterAdmin: false
    serviceAccount:
      create: true
      name: *name
      privileges:
        - apiGroups: [""]
          resources: ["namespaces"]
        - apiGroups: [""]
          resources: ["secrets", "configmaps"]
        - apiGroups: ["rbac.authorization.k8s.io"]
          resources: ["roles", "rolebindings"]
