apiVersion: v1
kind: Secret
metadata:
  name: openbrain-secrets
  namespace: openbrain
type: Opaque
stringData:
  DB_USER: ENC[AES256_GCM,data:x7ZOmicNETeC,iv:wYHnLgVLLpeW6SinKX135/UhGEmfcaauRSCJ36hmfvg=,tag:yTImo/Kgm7h7le3NFsqt+w==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:UULciN8FPCLhhTZEDcjKQd9fCgKYPdJ0j2E7JucX3Iwz6gmrquVwitffZJotBButWyMcD1ngqGZb08yczRh9pQ==,iv:SWqMIbrzl9cn0Mb/MZbmZnqk6seSiRGXWhQXiQf7Zho=,tag:APOcMYZAn15jcy8/yI8jmw==,type:str]
  MCP_ACCESS_KEY: ENC[AES256_GCM,data:Sh39nokxmdSSvCyvKguYDJ/wTpIWBWXh3QDuxyWPCMybFgcFZp6ircRMUbYp8L1VrsJw+Pf1//7OMGbPuUEeZMKO,iv:YlCJ5o+bfkSzS8VMPMc4wScK9z0D2i675HWbSr7key8=,tag:QMj10GP4jUZ0DzqvCNqMdw==,type:str]
  EMBEDDING_API_BASE: ENC[AES256_GCM,data:QJEBXcNO9JbbivD7ws0bKuKXYZrBZnCEhaCJkfleDjQfDpDT,iv:hKn6OzYOjnQP6B3qgTmJJwUOukzBWxKdvgrrEHgbXj8=,tag:2libsFbiw4MjkrneI2bjaA==,type:str]
  EMBEDDING_MODEL: ENC[AES256_GCM,data:5dHTZY+tiW/zDup7UnFOfX1g0jgX5Det8gcP1osttuo7f8kE,iv:PxWACwhNuuQtZDJhaUkWfmRnzSRE9HX8/yQkes1xxu0=,tag:2KFCKyyZ07Tre6ckupZRWA==,type:str]
  EMBEDDING_API_KEY: ENC[AES256_GCM,data:kgN7QqMWOlrwTmQQ/n6B7t5SRDmv3wi81pZ53r2AgPhARDA=,iv:lGngK7kDEqnjMNF6DsBOtts0p1LeJ27cJrQOuHuTrwE=,tag:Y0qrFffvuD+rFUCsB1EMeQ==,type:str]
  CHAT_API_KEY: ENC[AES256_GCM,data:bfQmIczbOtTx0LAFT2eyYOI1HUyoaaIQf7Wu/7Un1YvqAIw=,iv:yvQ1s6GIDrZT1VqJYqe8Xx+lG3X2W37JUzlzeBDWrEM=,tag:6vvKu81D9tnKmD+eshTfhg==,type:str]
  CHAT_API_BASE: ENC[AES256_GCM,data:GbkH95xUcFsQYmEl9jx0pCfNzlesQwShfP9XY5b2dYPjvHmq,iv:JChwgh3cYiikYp7ufP0/wHFPyFxJdqBcdLUfztmw3+g=,tag:z2Kfaoryfm05fPSkl+bvIQ==,type:str]
  CHAT_MODEL: ENC[AES256_GCM,data:N46u5dXhtsuLYx9wpAQuAuaJBT/LKA==,iv:y2zdm3nr5VU9k7vwi1kuRZui9GEUK/69PXfQqxSWA00=,tag:1gaeuSWnYUV+PJ1cUTX4ZQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Ny9zNC96S0poeU51bEFN
        RlJVOWI3azNJVjE2WG1jZ1BGYnllbDJRNlJJClJ1MGhiOW5Xd0VXMU5jR2UvcTdi
        YkZ2d2owSlowbDB1V3JZYWFHS1RkcmcKLS0tIG8rbVRIWUZRNHpkVlhnZEJCcTQ3
        UnpLcnRLd3lsVC83bWZmL2JBZ0ZockkKPbGU1kSHND7vn36VJlhPKrJ1xJLG3mLa
        QEuDgEi9ZXKdl50PfJQIOHJn/JtJfEM6QSR9v7Fl7yILY0Gd4BMAew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T22:40:09Z"
  mac: ENC[AES256_GCM,data:ARbv3s4bfsWfIUhzvC4ubkTml8BqbSPpCANX7E9fQKUPkbBd5Na3LbK8G0tMH3dtJME+mCYz+FXKKfUCEgYOxYkv0oHtnEB2q45l9We22ziPH/WCupxZG1h95k+2ukYQ9eFLif7wvS3gZ+SCGooFkA3nDUbCZfOyglOUY4YbqwA=,iv:qFx6TFyt6iaHyg7S2JjJ+H3wqtFqQhvpjEDgelcy+dM=,tag:GpX86Do47IVn6N9kai6/wQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
