# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hass
spec:
  chartRef:
    kind: OCIRepository
    name: home-assistant
  interval: 1h
  values:
    controllers:
      home-assistant:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              # TODO: switch to home-operations container
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2026.3.1@sha256:9dfead56f60fa9011719b4efca7a381fc6e89727bf6f58462d335fe7f04c033b
            env:
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: home-assistant-env-secrets
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /manifest.json
                    port: &port 8123
                  initialDelaySeconds: 0
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /manifest.json
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 20
                  timeoutSeconds: 5
                  failureThreshold: 3
            resources:
              requests:
                cpu: 100m
                memory: 1000Mi
              limits:
                memory: 2500Mi
          codeserver:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.109.5@sha256:f9ccfeb5a3de80d16342a6a842519c481522d80aafe65fb24a16393235a34f71
            args:
              - --user-data-dir
              - /config/.vscode
              - --auth
              - none
            env:
              TZ: ${TIMEZONE}
              HASS_SERVER: http://localhost:8123
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1Gi
    service:
      app:
        controller: home-assistant
        type: LoadBalancer
        annotations:
          metallb.io/loadBalancerIPs: ${HOME_ASSISTANT_LB}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123
            protocol: TCP
      codeserver:
        controller: home-assistant
        ports:
          http:
            port: 8080
            protocol: TCP
    route:
      app:
        hostnames: ["{{.Release.Name}}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: gateway
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 8123
      codeserver:
        hostnames: ["{{.Release.Name}}-code.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: gateway
            sectionName: https
        rules:
          - backendRefs:
              - identifier: codeserver
                port: 8080
    persistence:
      config:
        existingClaim: home-assistant-config
        globalMounts:
          - path: /config
      sshconfig:
        type: configMap
        name: home-assistant-ssh-config
        globalMounts:
          - path: /root/.ssh/config
            subPath: config
            readOnly: true
