apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-env-secrets
stringData:
  SECRET_EXTERNAL_URL: ENC[AES256_GCM,data:iGvqyWk7aRN8zcVP3BrqnWSOugUKkk+riKShNxNjavb/QJCJYSS9Qfb4PrSqw0qbIELYYLQ=,iv:Nqa/Vg/5j8siN29+GnpuTjDhvBblQOpzg/5CdUrVp1Y=,tag:CvfYhYFVuk0bgBZ1PfSoWQ==,type:str]
  SECRET_INTERNAL_URL: ENC[AES256_GCM,data:jJU5C1K+ojirrBHuMcN3jBAX/+5yx8NStdsaSiA=,iv:89pkTwvogUDhYqVeXwHpDQcp6UBj+lPpF+Ius7F0p38=,tag:vs2PTfPqNbSINtxEkLFkiQ==,type:str]
  SECRET_RECORDER_DB_URL: ENC[AES256_GCM,data:zEUqhozKsf3cSe5aisa31XlRrz3inSNc16kS2xfur+JW+uwtmtZc9nzwUByq3hES3gKveCHopTp6Hoyr1+PnVkeeqC+yk604RNXi0kLEM67wNhqJJYKbdDY95SRjyyAPMnmulKYWdhv1ScAsKpo=,iv:D9L0htxwC592tHbzAmCJVjST3++3Ga02kbuqa4DsujA=,tag:ZcroJNvTNqgttzLD7HCtXw==,type:str]
  SECRET_TRUSTED_PROXIES: ENC[AES256_GCM,data:7pptXfqkXMhL75+b,iv:pLO71prpvGyOeGPUBnCLhRve0z9VNLqb6EqXd/o1oMo=,tag:0PbT6xDAycCY3J2nlKumIg==,type:str]
  SECRET_VENSTAR_THERMOSTAT_DOWNSTAIRS_HOST: ENC[AES256_GCM,data:FIndqiOjCHx661+5fg==,iv:dS8OL3z29YZB2bg3uHObd36OVT6UBfWWXWBAn9C811M=,tag:WDhEG48vr3iThh/E2s8ZbQ==,type:str]
  SECRET_VENSTAR_THERMOSTAT_PASS: ENC[AES256_GCM,data:EIhDE7VjjHOnpubI/naLrD6QUHw=,iv:RUJktIhgQgkK91zf1xSS+6W4eOhOWeOCHTjFegkkK3E=,tag:N9OiRfAYrRM2RrYFtL/8mQ==,type:str]
  SECRET_VENSTAR_THERMOSTAT_UPSTAIRS_HOST: ENC[AES256_GCM,data:31m/cyFd1Ms6YWkqKw==,iv:cYJq5XKzvomDUBslsC6OaPmWCHxECdnSQNvxc6ZqGos=,tag:O4Xi/EC23nCT3l6TupzPrg==,type:str]
  SECRET_VENSTAR_THERMOSTAT_USER: ENC[AES256_GCM,data:u+Pmug==,iv:TH84tv6J9R8kpl+kjru/a2K7j9U3Bvz5kd7w1KNadhI=,tag:UB79ydbSwWNsxuSqinigpw==,type:str]
  SECRET_XIAOMI_CLOUD_PASSWORD: ENC[AES256_GCM,data:Yk2Q55e+SBbMIqBi8Ggpeg==,iv:AXVoWnXvMySHYMI3HZo15p0oCytXU/SsyFs7q81XdOk=,tag:WP8VUZVs3DUz82UeYxo5sw==,type:str]
  SECRET_XIAOMI_CLOUD_USERNAME: ENC[AES256_GCM,data:2gZLUY7+DdjZOAxzMX4OZRxe8S6IcAvY,iv:Zo0zRi5N2//b+9JUcKY/5Yz+dW2euoBMinoW6eIyBFY=,tag:iXIMHamnsY6MkrO1x3sgFA==,type:str]
  SECRET_XIAOMI_ROBOROCK_S6_PURE_HOST: ENC[AES256_GCM,data:BPLOoUJXw1SGQrJ9uQ==,iv:VoHZZGmjtRWAX0bCxhdFi6dEhNmYq3qn0L6qNh7Prxo=,tag:560PVCn0A8ncET2wnY6FVQ==,type:str]
  SECRET_XIAOMI_ROBOROCK_S6_PURE_TOKEN: ENC[AES256_GCM,data:Byh7ZP+yjBsSpdDqiL62E7GeBiUnBjf+Y2rNtVWL3ZA=,iv:aM2vqjvsCV8VJNeKYcXacP+EQhRMH3pDG3tlykF3tdo=,tag:ejGbxvr3L49lqIVaaXL/gg==,type:str]
  SECRET_ZONE_DAYCARE_OTF_LATITUDE: ENC[AES256_GCM,data:wvHOiRCbZ/RFsqNBdaiUzcn4,iv:y4JREBzJngmambFIItoQrPMQpHwRmxzUAT+920W77pw=,tag:wcEN+lhQ8+nmhh0to+ksgg==,type:float]
  SECRET_ZONE_DAYCARE_OTF_LONGITUDE: ENC[AES256_GCM,data:esOwF5ZXkCNPH4dWjhtmx3j2,iv:gb1iGNGkWH+KT/OXf6GFjEq7qoFWGFYftlmJizo1ppI=,tag:3udhrVg+shkt1e8YwP+VNA==,type:float]
  SECRET_ZONE_HOME_ELEVATION: ENC[AES256_GCM,data:JK4=,iv:6lMIxQ0lqKuLm8+fsUMDXx/9VXnrI1XLQWwCd7KvaoI=,tag:GsrAguP94AML8e1ajai0Gg==,type:int]
  SECRET_ZONE_HOME_LATITUDE: ENC[AES256_GCM,data:tqfXGDdHW3e/zDE/yNBENFNP,iv:/RZZvZ54Qn0+ZhxKSTSLqmk4bmwzWzP0zhJQxk5bmro=,tag:Gyi7DQOhX1ZmchfQZtklwg==,type:float]
  SECRET_ZONE_HOME_LONGITUDE: ENC[AES256_GCM,data:+CeMkNERYSPT7pEBUSMxDdI=,iv:Pe1EBvPIqmbW79hviHKDTVxbaHiXLDLtuHIUU2yVp4Q=,tag:1ETcZ6DVwsL8AY0U59aUIA==,type:float]
  SECRET_ZONE_JESSIE_PARENTS_LATITUDE: ENC[AES256_GCM,data:yMkBVkjIWuLWBw==,iv:Tbdq6kEkqFBlARRCqd885EuMHgsi6etwLLG3oxeHJX0=,tag:IhWh6E2vCU1Md9BTeu0+JQ==,type:float]
  SECRET_ZONE_JESSIE_PARENTS_LONGITUDE: ENC[AES256_GCM,data:30LdgN8G/kxtong=,iv:4fPK5tmyjHVAVyHv2sky8E0x2wwcvQ80LNFVTGl3zRg=,tag:15bDw0TWKFtsAl6vd1T+ow==,type:float]
  SECRET_ZONE_JESSIE_WORK_LATITUDE: ENC[AES256_GCM,data:F6EDBlfUZJAkySANskGL4ffR,iv:JHpm7vb16ZSNC0bLLJ71C2FhLV7OPi57XROXFj5lsIU=,tag:x1YM6jDcynzgxBSVWkJqRw==,type:float]
  SECRET_ZONE_JESSIE_WORK_LONGITUDE: ENC[AES256_GCM,data:aYrYUPwJFmj1BcGo2CCwzJg=,iv:QgXKwPTfj4DyYELaiO9nN24PkyNSyLGDzjIT8EKxyUY=,tag:viGk3kxVF8/vvUoGuNIfrg==,type:float]
  SECRET_ZONE_NATHAN_WORK_LATITUDE: ENC[AES256_GCM,data:X1gC+W0ijZLIPA==,iv:6WU3DT+0LIL9egY5ZH+rFGTuPvNx1Hng1147omHhYBg=,tag:Jms8cacMmYh4KIBAfPD+ig==,type:float]
  SECRET_ZONE_NATHAN_WORK_LONGITUDE: ENC[AES256_GCM,data:xCD9cknT2o+2rZw=,iv:GeOHMREO7t4d/eqYwgrDNXPy9/1N3WsjxnFMGiNIuNE=,tag:WhRYAgWq+xkpKI+FNV1bhg==,type:float]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOW9JUGpObWtUNEM1bVdC
        amprcWxzRlFUVk11TFg3TGxtV2h3VkJBZjFZCjlLajU1QnAvZnJsenp2L0FTbWt0
        alpETkhKZGUweEhwR0tEdzNCY1JGOWcKLS0tIHFOUjVkcHIzb0tKeWorOXVPbEJH
        RU1PNjNaMWpKbm1mallmalQ3MWFnNzAKEvYydHdMsA7AyDmPt3/nD5Og32nMVNbj
        3R44Fb7toSUfbvLueBmTq279LK/a6jEIWC4jBwmEbYjSM54MyAsAZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T22:23:45Z"
  mac: ENC[AES256_GCM,data:Ln8u27wQlAiM1s2t4rtFBYkhv2ncuhyWCPfObUZyt3y32DRTNA3yx+TyfGfSEIm6T4xmuICWNG3cKk5p+6LPIOD4RMh9Ua++4YMwiuqMAapIVehNy/seplAoafSu22e3jMaRU8uqZ7kc2k614p4Lc06Mrf8Fn2n0vgR8hjA+qPU=,iv:SvgkJL/gQXPDos3eiRQ96IcSsS2w1SOMyFH6WiRMb8M=,tag:yxJTMxX6rrFM19Q8P7MXVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
