apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-env-secrets
stringData:
  SECRET_EXTERNAL_URL: ENC[AES256_GCM,data:rBzDwyEGYooS0BlGvrACNvmi0l8WhU5BDrP7LAyEAx5rC70X/QpelbM9gQSbBjFEq4LZoY8=,iv:7WkkJnX8PmKx03HnauQcjXcnzUkd3CgLdBByh21Zzgc=,tag:QaYunbm3MWsYNTJUKTnWVA==,type:str]
  SECRET_INTERNAL_URL: ENC[AES256_GCM,data:aJiLni4exNTErMIOnJOk42C2s6bp9MVKImpjt/s=,iv:Hj9AuSTt5Hc28584LPSH927lV9PR9kiK2JjY9J8n2J4=,tag:aK7XAmmUEGrQbJCaG/acLw==,type:str]
  SECRET_RECORDER_DB_URL: ENC[AES256_GCM,data:gYXrKwHNVqG9R8UjeBUuLBg4ArRKXgYkNeBtKMG4KIro4VKhnIla/QSjcanhzScw76Xvv4Z7qjkp5IfzoDw9cV8q7zvri1oD2pHVWHVXa+iWZGzQQyojItv9rGPbGk80vnWRISoEMjYDkOHdPY4=,iv:8S1jRGNZo0MhCQ/TNXoTG0JH7ZvZvkHc1wR5MHgq3RM=,tag:OeAf6l28guwqNTcT1rNB3A==,type:str]
  SECRET_TRUSTED_PROXIES: ENC[AES256_GCM,data:KVvqYohjuE3YpQXF,iv:LRTuvHeCJ/mRKq81jDyxfep9jiXzVKF9IoISOo1rnis=,tag:nsXK9FlPao68Qd8uGz630A==,type:str]
  SECRET_VENSTAR_THERMOSTAT_DOWNSTAIRS_HOST: ENC[AES256_GCM,data:EWgCsVjqmNYeiCfGZg==,iv:oJBd4fJyQAssUmsJEkEh+Wb2y5zL9V+MLZQZoplo1e4=,tag:vG6F1H7gvLSNCoanRAafhQ==,type:str]
  SECRET_VENSTAR_THERMOSTAT_PASS: ENC[AES256_GCM,data:7pDwTqoOU+2OqVunsFEhbhLY8Z0=,iv:POlpfxLMBym+Hfm5FhP1aaeer6HCDbSSARa/tAdSbvg=,tag:DoeU+xz7bcAv+hdvARNhKg==,type:str]
  SECRET_VENSTAR_THERMOSTAT_UPSTAIRS_HOST: ENC[AES256_GCM,data:b1U7FF0n2Zzh9mlohQ==,iv:pnDZ1svXIvfIEXHoUqxGa7kAgHZn+oTtdoFOx7vGeU8=,tag:qN6KAlUTm4lvF5BdTYxhRw==,type:str]
  SECRET_VENSTAR_THERMOSTAT_USER: ENC[AES256_GCM,data:e5PC2g==,iv:qZr3V1/Kb1ZCIIthz7X5kop6PR44vodlVGM4j13YLCY=,tag:5yFlx9G0lA11fuuWptxr8w==,type:str]
  SECRET_XIAOMI_CLOUD_PASSWORD: ENC[AES256_GCM,data:01VtzelvLB63rl1Fuf1+cA==,iv:idMaxkOxFsVh2R806JkVKhF3XxxoLSxu6Gl0+f02ucw=,tag:UXfL4eijwX+07TWiYNuzSg==,type:str]
  SECRET_XIAOMI_CLOUD_USERNAME: ENC[AES256_GCM,data:2ls9eEMTtq8Suc2uAhSXAudHCanhXKcY,iv:Zk/OSGYrsLTei9dRkIxZHnpOD5PLDDazb0fVzthzoyI=,tag:Vp0IRLjjdRjsiu8AHve7CA==,type:str]
  SECRET_XIAOMI_ROBOROCK_S6_PURE_HOST: ENC[AES256_GCM,data:I/V/EMV2fylF+HeT5Q==,iv:mlHUIRYwRj0o+eWf79kTBkxPZbQX+3rsPHvG6MAR3EI=,tag:/80hhRt8VBFStMBlStvBdQ==,type:str]
  SECRET_XIAOMI_ROBOROCK_S6_PURE_TOKEN: ENC[AES256_GCM,data:hLHpx8ArK7YEFwHjarFqbYI7eYArmopRhpMljolRoHc=,iv:rzujXon2LYoyQGxcBAYaEA6+Z0BK1mHB4mjGZm4OJxA=,tag:F8myy/T18OWr6GsjC+0fkg==,type:str]
  SECRET_ZONE_DAYCARE_OTF_LATITUDE: ENC[AES256_GCM,data:otY3qtd/6X8Sq9RO76peehAp,iv:iP5E3tHWUIiB7V8kJ66nb1iIVZ/C8L9eDQRdQaCoij4=,tag:OjO+QpMf7Hh86C8axYUjGA==,type:str]
  SECRET_ZONE_DAYCARE_OTF_LONGITUDE: ENC[AES256_GCM,data:46yBcERgB1yyUcfHU9nFCOkT,iv:z9zNtZwiqojVFafiF62d1FObPy/iP+EbumYgVoNcOOc=,tag:fcZUe+OmlSrQNCKbXjxYdA==,type:str]
  SECRET_ZONE_HOME_ELEVATION: ENC[AES256_GCM,data:2wQ=,iv:YWQHbt5AdCcWLjtg3tKlEnex6VI6gbMEQSywkqOvP2o=,tag:fT1zQwurTabAl9zgOkVkSA==,type:str]
  SECRET_ZONE_HOME_LATITUDE: ENC[AES256_GCM,data:n2ZlWrEAHI48oHvA+P0E+xyh,iv:YOZvALD315WzT8UAqMU9DF6CmomoNiKdpsr70kMin50=,tag:uWYeGo2ZoFPgXIisz4rwCA==,type:str]
  SECRET_ZONE_HOME_LONGITUDE: ENC[AES256_GCM,data:kVHT1yyveft5/NtXZY8y/Vs=,iv:qWv1Yh91fKvrH/G1YxsYQHPRtiWZqJrkRUmlaD453DI=,tag:HTD8zNj2BwpUYF/W1esHMw==,type:str]
  SECRET_ZONE_JESSIE_PARENTS_LATITUDE: ENC[AES256_GCM,data:NRvNxrOVe69uJg==,iv:rERQoLc6zfZCUnotr+wCpCdyinzzPQ2cy0yTZ5FvjJU=,tag:Oimrwm7L5ZC0kn5DW0jxMA==,type:str]
  SECRET_ZONE_JESSIE_PARENTS_LONGITUDE: ENC[AES256_GCM,data:ZMSQ5ZQi4VsLa8s=,iv:XmFDWlvDWbI1b/8dpYzsu7OQqWlg6q4p4PTbiEYMsvM=,tag:bGyh0zn+mmecMEaHJyoqwA==,type:str]
  SECRET_ZONE_JESSIE_WORK_LATITUDE: ENC[AES256_GCM,data:cWF4X556si0akEXtZ8uegtrM,iv:YlDaq3TZMCqs2Iv2p8xYFpH+iiEUNV7s3r/zTg76IdY=,tag:JYnBeAqFGiWLONpdmp347g==,type:str]
  SECRET_ZONE_JESSIE_WORK_LONGITUDE: ENC[AES256_GCM,data:VVLoG5TXMN7QJFV9VgQo54A=,iv:TY2YEC8ONM3XTqM8RrPH4TaQzdzcsLE+uf4uZ192vJI=,tag:Avf6yZZelu3fO+Voo4Rvig==,type:str]
  SECRET_ZONE_NATHAN_WORK_LATITUDE: ENC[AES256_GCM,data:VKbxawZZaA3PZA==,iv:Jr/mR5RpLp/WFTj0FJtKJf0yyQBwOVFq4hEv/w+0Hk4=,tag:I93jFCR1sAyXDxS4/fFHeA==,type:str]
  SECRET_ZONE_NATHAN_WORK_LONGITUDE: ENC[AES256_GCM,data:CM9dl9aEvX+Tfls=,iv:Y4qTyMLPz1EsWO0IwcedkkCS6dK7puZbYobK3k8csjk=,tag:VxnBikulQq7vSijVDJH96w==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOTkwYWw3OUNmU2U0Tk5w
        TjdWOVhTM1M3RVFVVHVBY0Z2STV1aVBBcjMwCkZtVk9pUitmN3JoM21ESEt0RDZH
        Z1hkeHBMd3ppYjdtSytPc3JPb2pBNU0KLS0tIGg0aStGSnZpTHhqN2pyM2dxKzJJ
        SzdIR0UveWEzL2NveW54Mm9WNm9vb00KDjyZJAKTcgodDduGsVjRpATZIJvuZxp6
        ulut1VMIn6tf4OctjXhDNwBH96ZHcBOPNHESUludJE+wSUn9LbSHaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-28T17:34:55Z"
  mac: ENC[AES256_GCM,data:fk5ZyirlYbDSV9natOkcNErU77DluUiddwHT4prqbIN9PeppJlBSc7hyEty+CxDXVWRA/lKzRoJqsbglwO+YqFaFIk4mSTlSzM4rZOmdafCOmx3EAvweN4H4UkaP2uU4JxI7PseJ9fD9oZ9/naKk4jjMgKUPvh+FMvd7Y7oPOqc=,iv:PDVUrf5Vd3W4o6mXFlCdUeB7FmAl+RmBXyVTLDpVUAk=,tag:D7FuiLbnZ4UhwyXS1A2NSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
