apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-env-secrets
stringData:
  SECRET_EXTERNAL_URL: ENC[AES256_GCM,data:x//SQ4JLV94A7JitddeNQ7xNZ3xMcY/japMN34lvfM8lY5Z+sCeoQTRFr2jui8bDmS/sVeI=,iv:nvYdpWBOtzfUo+G4i/BhUI/uVHX9Gk535UmOjENKz38=,tag:6nfz3NRWtmw2SXvvJkbVmQ==,type:str]
  SECRET_INTERNAL_URL: ENC[AES256_GCM,data:gjnNyMsyq7F8t7ewqfZOZJm1x8o7DTsdePZ0xgI=,iv:eQM7gNyZ96emISyhwsH1/jgrkNjQMBRiCbkA1aprybw=,tag:0gF7HII2nSufgoCRCC+i7A==,type:str]
  SECRET_RECORDER_DB_URL: ENC[AES256_GCM,data:kZ1Ie+SUDXFKot9/Z1fUb5yPNNmjUHg7FgLquoOmJkK2gLVlIltrzhdPRZuF1FsewICRKS60d6AE9VOr+kv4oB/UmFpYomCIMBNM1RCkpTsb6tLDf/vJe9bxZFeGO4sCkFu6FIeai35nXa63+N3v5Gr4Kip2k3g7EF3B2jJRY0nTvtxazSDcZqOpPLFhCXgcP3EKo2l2EIF7lC//YPy3/5lXkcldgoN6QYsnvcYWHIg3ePolVuah,iv:pa0yM9oxjoCLBkjx7X2S/Uwf/ZIWHH1l7Pyj/To5Spk=,tag:P6DN1SIc9H7eNv+JLw8fiw==,type:str]
  SECRET_TRUSTED_PROXIES: ENC[AES256_GCM,data:IdG3bQPlAUJuY/DL,iv:mJveOPX+fl1TBoCGO4Njjg7xICKHVY/SJLuykKPFEng=,tag:M00W7wUe+IOL51yjpxeaGw==,type:str]
  SECRET_VENSTAR_THERMOSTAT_DOWNSTAIRS_HOST: ENC[AES256_GCM,data:7oGwudhep9Ok9JZ0EQ==,iv:dnfY4xRcboeavLPBxbZ45GyF/B/hO61wLyIcCuJ9Kk4=,tag:NjYlf9Ylxd1IzocL/b4NeA==,type:str]
  SECRET_VENSTAR_THERMOSTAT_PASS: ENC[AES256_GCM,data:k61zf1ftoTrJMKQPunC/ZasvgoU=,iv:yr4EduUL3WKKm6eZG9Zu3O6xX8TGSh7zjpoziGBjybM=,tag:DskjDDd3UmPaXcwN+r+88Q==,type:str]
  SECRET_VENSTAR_THERMOSTAT_UPSTAIRS_HOST: ENC[AES256_GCM,data:+x0W14nizVh6eYYFJA==,iv:+c1yQh0cNvK1J7H5XYClaaIvsNZ0TGzel+ry6Rf/sb0=,tag:c3zEqgz33HvRy+qJmPCb1Q==,type:str]
  SECRET_VENSTAR_THERMOSTAT_USER: ENC[AES256_GCM,data:sZ0OAQ==,iv:W2U5MmnUvCdyLX2VI0vfkwyUOG8nQG5gtFA1aBLWnjs=,tag:ZzCT4L3wvb6nEU3gGMQM8w==,type:str]
  SECRET_XIAOMI_CLOUD_PASSWORD: ENC[AES256_GCM,data:FrcFVEHU6bSwaW88kY5gFg==,iv:99ZpRGYmfLnv7emo+FgtKXsK6d6CyeuQAguaR8P9erY=,tag:Zf1K50ASjq3G8WqgSGmdUQ==,type:str]
  SECRET_XIAOMI_CLOUD_USERNAME: ENC[AES256_GCM,data:Pv593W2gD0JZvPVfCGw6qWp+mF9tB/9j,iv:Dk5G2xtNXsAhbTtMngySQJnl8sICfIAM5bPqTuNePRk=,tag:4MK6WfyuEMX0i2joq+Htrg==,type:str]
  SECRET_XIAOMI_ROBOROCK_S6_PURE_HOST: ENC[AES256_GCM,data:fSIVToa5BcOuCrXrGQ==,iv:DKxp0pAxMsAuXojVAM2HlP6FwVycHwSBaqKoF2IhYbM=,tag:kzNCYFCTobzma2FdPIEOOg==,type:str]
  SECRET_XIAOMI_ROBOROCK_S6_PURE_TOKEN: ENC[AES256_GCM,data:mKpxSXKkfXAQ6F1wGKpVGeQ60NAnKcuzO5PChG+migQ=,iv:XNFieUvW41ckx0PGPBMfn1ck69VufHmT3Z2RH20DuXQ=,tag:tfYEsjbp8hNRILfb1cQzSw==,type:str]
  SECRET_ZONE_DAYCARE_OTF_LATITUDE: ENC[AES256_GCM,data:r627S/c9zYEmHHjo+zlDs5aL,iv:PR1fbTDGPJjtwfzr+xbdjbFAlXAqTN+3hhei4/WZ7r4=,tag:Nuvlv5IzzZVENRpUKwNAPQ==,type:str]
  SECRET_ZONE_DAYCARE_OTF_LONGITUDE: ENC[AES256_GCM,data:wwDNMJ5Cq+JnysDZQsXGr29a,iv:gY2r+ua6sECaQDZOtBDHjDM69ZJBnjVzcxEJU+feUiI=,tag:a4x7U55pAEfzjvjJCTGdsA==,type:str]
  SECRET_ZONE_HOME_ELEVATION: ENC[AES256_GCM,data:4h8=,iv:vcq44kUL7W1tc56Us4uR43D0msY9NApqycN74ZN3iMc=,tag:eDCcSuhpmrhUY9gXsULmhQ==,type:str]
  SECRET_ZONE_HOME_LATITUDE: ENC[AES256_GCM,data:9TiohRmN61aRQIKtvSS/Dc8x,iv:5T6Qx5hQbDoHc8BY4Fbt0qptdBD9m3UxNjCMcIhta1A=,tag:3/b4AAHU1OwUjYLN+Rqh4A==,type:str]
  SECRET_ZONE_HOME_LONGITUDE: ENC[AES256_GCM,data:/0fqUzIUcEdyEV/H4yD2Q9U=,iv:kZuvYIA5sKTaZLKkVLgV5T/Sz8MiKd9xcudVnPGFWG4=,tag:NU3g+hBqs+TRr60u9mq1ew==,type:str]
  SECRET_ZONE_JESSIE_PARENTS_LATITUDE: ENC[AES256_GCM,data:wcT7zlJNOb07jg==,iv:9VnhjI3Pj3m0MbIDcdmh3u5ck0VpG0D6IdjjxePHSPc=,tag:0yexKPhTP4UsRcKtznIAuQ==,type:str]
  SECRET_ZONE_JESSIE_PARENTS_LONGITUDE: ENC[AES256_GCM,data:D1nKqbP+cYa7J3k=,iv:OYkeOnOMakhRjs3GhlDbmIe7GRAdV7dgxbRIbRFCiOM=,tag:VNJyc5zLeI50AA6xeeApqA==,type:str]
  SECRET_ZONE_JESSIE_WORK_LATITUDE: ENC[AES256_GCM,data:7mEmEopZ9KwrXUEkHSczDFj4,iv:E7laJ+JlXn+N14ml6SA+seEFxYKVUpOLEl1ueXVqWh8=,tag:Rd4JkV5WBay/vSxJUxdDxA==,type:str]
  SECRET_ZONE_JESSIE_WORK_LONGITUDE: ENC[AES256_GCM,data:9zr+42DbYnBQELrYAJXmtNQ=,iv:Lt8835oX8Tz6lyXYaL9ruGZHNPwxSOKThtoXku6aedw=,tag:sbjQIvbtPdUIAi6G9wcXyA==,type:str]
  SECRET_ZONE_NATHAN_WORK_LATITUDE: ENC[AES256_GCM,data:jUHFk6f9xhZdoQ==,iv:Sos7AIaeZQi9wR0oVweyU0Ws5yQSAcL6NssqBa8iZcQ=,tag:O9lWT4Y7Pt4vBmKuQwTy1g==,type:str]
  SECRET_ZONE_NATHAN_WORK_LONGITUDE: ENC[AES256_GCM,data:pVIImF9CLCx+VM0=,iv:MSsM8ZPUETZBsICNN9vnQ3dWnY1JFWS1zC/dwXJiokY=,tag:j6QhaG+zcrY3z/bFUzBXpQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWDJtdmVmeVIrNFhiN25s
        REN0b2dCV245NGh4VmpZMm0xdUQ1eHI2bnl3Cm1vOUtZOHJWcjV5UVJaa2hVZGMz
        aTBXZmt1TWp5d08yNmRPUkFaM1RQV1UKLS0tIDk4NnM3cEM1QndaR3VxSW02TnU4
        NldlMStIZW5CRVY0V0NlaUpSdFZkZ3cK9rtWIZ3nN7nbpcQHaYE4n0mtpQgn5opB
        eAq/SEjrUbhwHrJAfMtEK7hzIdq/pN2wO73x8iJzmnJM5vV1ygD6Wg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-17T15:25:00Z"
  mac: ENC[AES256_GCM,data:0AUnHgoX6zPgHcvW28P7gnCOPyG1dIbI6u3h+qLau5Xte/ZWnQB/fLNIxeJ2GPgYYumj+DI9K0tVnxddLqoh/haTUhVW6DSJEcaVoASM+5rQrHQqE/a2HnRT2Xv53DKkdNtnDRWPvxQz3tP7PtPjfJRRHFak3IrcvdyD1V/7pFs=,iv:zZQzcMmU8Ot44p9PPZY1aI3A+iuNPLGuty2WqsEGboA=,tag:hKNf5HxsyLjSTolDB5ihzg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-coder-env-secrets
stringData:
  CLAUDE_CODE_OAUTH_TOKEN: ENC[AES256_GCM,data:wdIUn6NnR0y1TAMHY58Vo5pM2zopq89G75zJWChrcWGAJvHhDPYeYmx3RrQFyERQXi6dQp+qQ2bA+LMOJ+bw/gMiXuJKIBaCTFuHYA+fXWfkQaTlve2Qut2v53sSFY39Ib3Sc+kSQYmSu/Dx,iv:NjI6501q/iaI/pua9SXpkTHVxCfPZ8ONBqXf1OWZb3M=,tag:4F5N+w4zs12bZ2sF0qZg+A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWDJtdmVmeVIrNFhiN25s
        REN0b2dCV245NGh4VmpZMm0xdUQ1eHI2bnl3Cm1vOUtZOHJWcjV5UVJaa2hVZGMz
        aTBXZmt1TWp5d08yNmRPUkFaM1RQV1UKLS0tIDk4NnM3cEM1QndaR3VxSW02TnU4
        NldlMStIZW5CRVY0V0NlaUpSdFZkZ3cK9rtWIZ3nN7nbpcQHaYE4n0mtpQgn5opB
        eAq/SEjrUbhwHrJAfMtEK7hzIdq/pN2wO73x8iJzmnJM5vV1ygD6Wg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-17T15:25:00Z"
  mac: ENC[AES256_GCM,data:0AUnHgoX6zPgHcvW28P7gnCOPyG1dIbI6u3h+qLau5Xte/ZWnQB/fLNIxeJ2GPgYYumj+DI9K0tVnxddLqoh/haTUhVW6DSJEcaVoASM+5rQrHQqE/a2HnRT2Xv53DKkdNtnDRWPvxQz3tP7PtPjfJRRHFak3IrcvdyD1V/7pFs=,iv:zZQzcMmU8Ot44p9PPZY1aI3A+iuNPLGuty2WqsEGboA=,tag:hKNf5HxsyLjSTolDB5ihzg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
