---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-configmap
data:
  settings.yml: |
    ---
    use_default_settings: true

    server:
      limiter: true
      image_proxy: true
      method: GET
      public_instance: false

    search:
      autocomplete: ""
      favicon_resolver: ""
      languages:
        - all
        - en
        - en-US
      formats:
        - html
        - json

    general:
      instance_name: SearXNG

    ui:
      default_theme: simple
      infinite_scroll: true
      query_in_title: true
      results_on_new_tab: true
      static_use_hash: true
      theme_args:
        simple_style: auto

    outgoing:
      proxies:
        all://:
          - ${HTTP_PROXY}

    categories_as_tabs:
      general:
      images:
      videos:
      map:

    plugins:
      searx.plugins.calculator.SXNGPlugin:
        active: true
      searx.plugins.infinite_scroll.SXNGPlugin:
        active: false
      searx.plugins.hash_plugin.SXNGPlugin:
        active: true
      searx.plugins.self_info.SXNGPlugin:
        active: true
      searx.plugins.tracker_url_remover.SXNGPlugin:
        active: true
      searx.plugins.unit_converter.SXNGPlugin:
        active: true
      searx.plugins.ahmia_filter.SXNGPlugin:
        active: false
      searx.plugins.hostnames.SXNGPlugin:
        active: true
      searx.plugins.oa_doi_rewrite.SXNGPlugin:
        active: true

    hostnames:
      high_priority:
        - (.*)\/blog\/(.*)
        - (.*\.)?wikipedia.org$
        - (.*\.)?github.com$
        - (.*\.)?reddit.com$
        - (.*\.)?docker.com$
        - (.*\.)?archlinux.org$
        - (.*\.)?stackoverflow.com$
        - (.*\.)?askubuntu.com$
        - (.*\.)?superuser.com$

    engines:
      - name: startpage
        disabled: true
      - name: karmasearch
        disabled: true
      - name: duckduckgo
        disabled: true
      - name: duckduckgo web
        disabled: false
      - name: braveapi
        disabled: false
        inactive: false
        api_key: $${BRAVE_API_KEY}

  limiter.toml: |
    [botdetection]
    ipv4_prefix = 32
    ipv6_prefix = 48
    trusted_proxies = [
      '10.32.0.0/12',
    ]

    [botdetection.ip_limit]
    filter_link_local = true
    link_token = false

    [botdetection.ip_lists]
    block_ip = []
    pass_ip = [
      '192.168.0.0/16',
      '10.0.0.0/8',
    ]
    pass_searxng_org = false
