# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-5.0.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
spec:
  chartRef:
    kind: OCIRepository
    name: searxng
  interval: 1h
  values:
    global:
      createDefaultServiceAccount: false
    controllers:
      searxng:
        annotations:
          reloader.stakater.com/auto: "true"
        type: deployment
        initContainers:
          init:
            image:
              repository: public.ecr.aws/docker/library/alpine
              tag: 3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
            securityContext:
              runAsUser: 0
              runAsNonRoot: false
            command:
              - /bin/sh
              - -c
              - chown -Rv 977:977 /etc/searxng
        containers:
          app:
            image:
              repository: ghcr.io/searxng/searxng
              tag: 2026.7.12-74b4e7c8d@sha256:bf2700fa1e7b63c9ef577004513efef509f9c23bfa2cd6e56be08211508df95a
            env:
              TZ: ${TIMEZONE}
              http_proxy: ${HTTP_PROXY}
              https_proxy: ${HTTPS_PROXY}
              no_proxy: ${NO_PROXY}
              SEARXNG_BASE_URL: "https://{{.Release.Name}}.${SECRET_DOMAIN}"
            envFrom:
              - secretRef:
                  name: searxng-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - "ALL"
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1024Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 977
        runAsGroup: 977
        fsGroup: 977
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: searxng-config
        advancedMounts:
          searxng:
            init:
              - path: /etc/searxng
            app:
              - path: /etc/searxng
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["{{.Release.Name}}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: gateway
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
