apiVersion: v1
kind: Secret
metadata:
  name: searxng-secret
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:tkfAdKC0DqvGPZ7v0iOJlzZJlmFgU5OHVUsj5M2vy09Y8sFUqx0V3JkADxfrJKnm,iv:5z5msJlwgTRJW/BeeE5TdMlAeS+x1w95X3lE54BVETw=,tag:+K34bMxdI0Ltwyq20v5ZjQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbEdvb1RCT3Z1VVpqNGxp
        MFVwRVg1ODN2eVcyOEpVcDNRT1VuNFBlZ1VZCnRsdDJOa3JPZTdpK0V3ZEk0WTd6
        K2djdWRFdG4zU3ZtenllMmo5KytSUVkKLS0tIHB1eXRONzZnYWtzclZwNTNRODNk
        Zm41N2p0U2l0UmIvazdxTHliL1l4TjgKp+OM2baWr7x8IliZbpNUR5l7SUVrU0ZM
        K5A30ISw02QtglTa1mlAu6HEn7MVOvwzPIbIozINVFTg9twYM4PagQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-15T02:56:11Z"
  mac: ENC[AES256_GCM,data:JGbIn4NRokJlEqz5+IsvblSC/h+fpueCfs+VW57xwYOb9d87SN+YBA0VrsUzlp8m05f8Of3AgWv4LR91aTkM6JiRtnOVc511Kr5WRkM/sZ6tU5XM1qQo6ZEpluyoAfQPCBDCZehgEfZ66EUYMAZr0ZdSUJwwB73SyDuZJmNL4E8=,iv:gye+Hp6TJbdqbQF5cGeYmbGfTdWeqJ/vQY/T7IaaRFg=,tag:eeWDIf97IDlBtT4JXh3OEw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
