apiVersion: v1
kind: Secret
metadata:
  name: searxng-secret
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:KSa/8fe3ULLOz2Db0DoH3tEtglsR+sywtO9ylUmuj5B94nMetT5ptlZpIV4ZHA2bHRpjg0OkAWTSeiRC0T7aGA==,iv:wHdv5I5lQK7sLcQ4DR9SSmOBmz4tK4Xj5LzK7CkG7s4=,tag:c429OfCawCmy9AMVZWbZQw==,type:str]
  BRAVE_API_KEY: ENC[AES256_GCM,data:duPED+o1b7q4uB3A3Lbm3iVyqEzAo7zMBye+75eC1A==,iv:tSLnLbQuWnPMD/KPbX7EEUkG1FfOCAriLBL0whpbRSQ=,tag:zBKKRZbHeu3FNOv4eB4XgA==,type:str]
  SEARXNG_VALKEY_URL: ENC[AES256_GCM,data:diJhOUx6Wo07aBCyDi/W9yk9M0gA7bmZGMgOncSrgkFyGocoZrDEs4oFUc4BTleKNTk7m808J4W+AZgoXTufzLiqGnDB8/rlAl+emq2apr921MeAyAn4Cr3MfbGMrMv6qNCxS6dxLjkMyd4M3XZbAklmcZziEjjcGOlPGdnNebbUbViPcVYcS/nH/3CT2DwZG48m+PFcFqGi,iv:1l0D94ywsVA6VZfCVNokxB/cI5MIz+tIWCO9AC8/APs=,tag:AwjACHiVKoPCy+3Ez02r+A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbEdvb1RCT3Z1VVpqNGxp
        MFVwRVg1ODN2eVcyOEpVcDNRT1VuNFBlZ1VZCnRsdDJOa3JPZTdpK0V3ZEk0WTd6
        K2djdWRFdG4zU3ZtenllMmo5KytSUVkKLS0tIHB1eXRONzZnYWtzclZwNTNRODNk
        Zm41N2p0U2l0UmIvazdxTHliL1l4TjgKp+OM2baWr7x8IliZbpNUR5l7SUVrU0ZM
        K5A30ISw02QtglTa1mlAu6HEn7MVOvwzPIbIozINVFTg9twYM4PagQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-02T03:06:54Z"
  mac: ENC[AES256_GCM,data:67PG+ZU+jYtJcnJvVkqQwgp9v1vOcuEfgCmxQMlEv3sU20aRUkTVH32pYCAAoTRwlM3vpPhuBUo44QHrSzsxoqiR0HhtKZt4kBW2HPZm7l32I0StRTw1qZ7NVtMBl3ORHK5zYpm1VpUwJQDEr7lDmWiN8kgCrHQ19HuwD1I7ZfY=,iv:YB03sgY2vT012NqS3SLM/mnaA3XXo2PpRKylCMr4JOE=,tag:8kegMUgjcQEB5Pn/T+GJcA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
