---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
  - ./netpol-authentik-postgresql.yaml
  - ./netpol-authentik-redis.yaml
  - ./netpol-authentik.yaml
