---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: authentik-backend
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: gateway
  to:
    - group: ""
      kind: Service
      name: authentik-server
    - group: ""
      kind: Service
      name: ak-outpost-envoy-outpost
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: authentik-server
