---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
spec:
  chartRef:
    kind: OCIRepository
    name: tofu-controller
  interval: 1h
  values:
    replicaCount: 2
    concurrency: 24
    allowCrossNamespaceRefs: true

    image:
      repository: ghcr.io/flux-iac/tofu-controller
      tag: v0.16.5@sha256:1d6ee0e34ee56a22827541b1ef44e5a3d65ff21bdb870f79103c4c5d5e6d4cba

    runner:
      image:
        repository: ghcr.io/home-operations/opentofu-runner
        tag: 1.12.6@sha256:305e14b33a5bb95dfd36459df1d12800fe87e3fcf8cf39e9759f9212aef4079d
      grpc:
        maxMessageSize: 30
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 400m
          memory: 64Mi

    metrics:
      enabled: true

    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
      seccompProfile:
        type: RuntimeDefault
