# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/dragonflydb.io/dragonfly_v1alpha1.json
---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  replicas: 2
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: dragonfly
          topologyKey: kubernetes.io/hostname
  # renovate: datasource=docker depName=ghcr.io/dragonflydb/dragonfly
  image: ghcr.io/dragonflydb/dragonfly:v2.0.0@sha256:7426fdb31ddcf7bd9499b4205f36ebaa83b26149ba1609a0d5f8f474b3631233
  # tlsSecretRef:
  #   name: dragonfly-tls
  # authentication:
  #   passwordFromSecret:
  #     name: dragonfly-acl
  #     key: authPassword
  aclFromSecret:
    name: dragonfly-acl
    key: users.acl
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  snapshot:
    cron: "*/10 * * * *"
    persistentVolumeClaimSpec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: longhorn
  networkPolicyEnabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 400m
      memory: 512Mi
