apiVersion: v1
kind: Secret
metadata:
  name: dragonfly-acl
stringData:
  users.acl: ENC[AES256_GCM,data:D90emqspN2lWEiGXUZEuKJV/H6C8j8AzPycLs6JJRRLfQsAR5tgZAxJA0/p0kb4r9Gtm/zahRK9RR4f/leUSfltmaTiHK/y/aVLauT+LN1HQ43SFaakObSDBJhMDOX9F9AkGYE8T89qlJ2LcyDhk2YU7KMiYDagafdmM2iRDr+2cJ5VmBNSvxGr8dbhI2y5sWuUhb+kbDuVCGN2wWVoje8GuknsBROzZpqCO+r4+MpOpNMaBCndu2zbbPuXbz8wAu9cgyseYTYkFe5VvafEWhAQLeOUD8fiLlCjKLPv45JTE2uk44gjGYjGEP2emK+1Yy0ZIqCi4PzSre1txeEk1rJFfrXNSDzQdV1BIg0KX9Oit9B6/XIMYNqkTZlxnTCJ4L30dhDF6OFT0UytUqXTLZ8tN58ztfvObf2Er56bfyaSCOJXb5P1KEASHA+RPFfAto8JZDnPqzIALqX2H9hhrEhsjBCRjmb1Z3OwZC7X1alTZfNXzFO0IYWgtwZXCrtyKQP9rX/333d7wx8uA10hjMuLBST4v6XbjAwePs6VY1sjP6jff/oL2Cw/wQhM=,iv:5hNQiCANhKdjlOsq4kHellSnDIKocnZhSOkLHM+a/so=,tag:Eub9F3va7lyIjHTiKjFH6Q==,type:str]
  authPassword: ENC[AES256_GCM,data:fYwFNvu64zjG4ybE63QjhmY+EZTI9e84D6/OnXjE+SpbVzrRdILI2rPD7pDA5xHDJQVe5ZimX8xkVgXibhZAiQ==,iv:xP97c8nM+DMNsIVa1JphhMi0GtZBPzjqOcJ67xj2vXY=,tag:oqgBv8ChCStaXA3xtX2x+w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzU0NjS2tQaWo0aTJkWFB4
        YmdzbWZveW9BcVpIZkUzN3pNd0tmTXZXZmdZCmxPc0VhS2xRejc2Z3Z5UDc4SjZk
        ZlNmUEp5YmErTE1ZYnZQOWRoTmYrNnMKLS0tIFp2NVJrMzBSUGxPM01hSytUTzN2
        c2toVnlRWVJ2cHRZRTJvUkRoN0s1STgKJr1d1u2letXHYfakEvNM9D2ku6+NtF2A
        jMqI13ABEsjKbT73BYIgBsx64YpNeyQBRMOPV2zpoGRyUq9fbeLDFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T20:43:59Z"
  mac: ENC[AES256_GCM,data:P5H8HPxRvO061Koe9pUEUsXgUNxH6S8cohU12IpPSi/5yILqmOIgRqrtPiuswOkyVGREXVrTXLwALOWr39iYfx1qJ8n+8Q45+EPV+qZA01NxMqA6Tcs7qojmiVMaclhc2O0Fa84C+ubd666S/CISrbdtnqOk+7TjI7jRtMJyK2E=,iv:XrjD6/6dwFkbk+DO0VEXHsc2RO4pWYtjQPTxWWKzQUA=,tag:TRX1YuJlOVz56Z7zG2bpaw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
