apiVersion: v1
kind: Secret
metadata:
  name: dragonfly-acl
stringData:
  users.acl: ENC[AES256_GCM,data:9TK+C97xfi6KhdRCLH6YpHzSOhUY0UvrCv5i6Zy8E6NDz8S6igppHVGzGAPRwidwRDSBQjUiochYFUYojLQgPsR71w68JfNFTRHKkhMWSB7son5dju15F8dwXGSZyN1V6XUN6IS2smv/EnhKhaT0nsCCDxRkUcujnNtOiCeTecGrp0NMBMLOvgrlce4jina64WlOff3AJP86T3ARIQ4FSITy5rCh1yKx9MhzgjEUjGtb1qcq07h7Y4l+5LoYSASgvN8Mmw3ue99tPLWn16ecApaeEq13OODmWZ5MLUyu95UCTCnNkcpt/f3wzWckbKVgPU3/8wAvlEDz66dn5UAl8LAqxXN3g/22X+/CneXHQ5WN0kl5h8QmrbJygnrGPc+uLZzhxIlefo4WZ3PUWl6iCUfC0gVMouWoeg==,iv:NIv9JI6QF0rzqDXdhXxG6IU8lvaWY2XUd6xMxMsdCDM=,tag:aeRIUnyAckM/o0t6PywYQQ==,type:str]
  authPassword: ENC[AES256_GCM,data:fYwFNvu64zjG4ybE63QjhmY+EZTI9e84D6/OnXjE+SpbVzrRdILI2rPD7pDA5xHDJQVe5ZimX8xkVgXibhZAiQ==,iv:xP97c8nM+DMNsIVa1JphhMi0GtZBPzjqOcJ67xj2vXY=,tag:oqgBv8ChCStaXA3xtX2x+w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzU0NjS2tQaWo0aTJkWFB4
        YmdzbWZveW9BcVpIZkUzN3pNd0tmTXZXZmdZCmxPc0VhS2xRejc2Z3Z5UDc4SjZk
        ZlNmUEp5YmErTE1ZYnZQOWRoTmYrNnMKLS0tIFp2NVJrMzBSUGxPM01hSytUTzN2
        c2toVnlRWVJ2cHRZRTJvUkRoN0s1STgKJr1d1u2letXHYfakEvNM9D2ku6+NtF2A
        jMqI13ABEsjKbT73BYIgBsx64YpNeyQBRMOPV2zpoGRyUq9fbeLDFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-04T02:17:03Z"
  mac: ENC[AES256_GCM,data:bry1mOr1WX9r+eA4kggnRtTwxxfyhaiPl6/dGi5iQsMAo2Qn457DCStIFM3Stnmj4YiZyQ/xFNviH6ay82GNsWKUE8NbJv9kmbn9VuFThE3rgefG0I+6qZLrjanLFjbO5CWkB37Kq+tgcdELPTbwiry1DLPXVRzxV9SVGVrtW2I=,iv:TeCN4V2bH/uHXnAVPfs4T4c59Wo93gKTI5lSFIZw/Fg=,tag:w2M9u3842PR3wLm++2YIFg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
