apiVersion: v1
kind: Secret
metadata:
  name: dragonfly-acl
stringData:
  users.acl: ENC[AES256_GCM,data:9TK+C97xfi6KhdRCLH6YpHzSOhUY0UvrCv5i6Zy8E6NDz8S6igppHVGzGAPRwidwRDSBQjUiochYFUYojLQgPsR71w68JfNFTRHKkhMWSB7son5dju15F8dwXGSZyN1V6XUN6IS2smv/EnhKhaT0nsCCDxRkUcujnNtOiCeTecGrp0NMBMLOvgrlce4jina64WlOff3AJP86T3ARIQ4FSITy5rCh1yKx9MhzgjEUjGtb1qcq07h7Y4l+5LoYSASgvN8Mmw3ue99tPLWn16ecApaeEq13OODmWZ5MLUyu95UCTCnNkcpt/f3wzWckbKVgPU3/8wAvlEDz66dn5UAl8LAqxXN3g/22X+/CneXHQ5WN0kl5h8QmrbJygnrGPc+uLZzhxIlefo4WZ3PUWl6iCUfC0gVMouWoeg==,iv:NIv9JI6QF0rzqDXdhXxG6IU8lvaWY2XUd6xMxMsdCDM=,tag:aeRIUnyAckM/o0t6PywYQQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzU0NjS2tQaWo0aTJkWFB4
        YmdzbWZveW9BcVpIZkUzN3pNd0tmTXZXZmdZCmxPc0VhS2xRejc2Z3Z5UDc4SjZk
        ZlNmUEp5YmErTE1ZYnZQOWRoTmYrNnMKLS0tIFp2NVJrMzBSUGxPM01hSytUTzN2
        c2toVnlRWVJ2cHRZRTJvUkRoN0s1STgKJr1d1u2letXHYfakEvNM9D2ku6+NtF2A
        jMqI13ABEsjKbT73BYIgBsx64YpNeyQBRMOPV2zpoGRyUq9fbeLDFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-03T22:13:29Z"
  mac: ENC[AES256_GCM,data:/ua3ZbjQLjdxNdKNQVx/Lvw64GUEL6QUKtvcN3vop887wh8aJVt71xExzaLniTawCZ+emd6ipzF8H0A1MjtRdN1m3enjNjV2bJKk2qunFlQMqiCB1rjiM7BDZBa9eEEpVrybKlliuLnCmVD6TVIAMhZ5XhVwAB6CgKd4awhBiqs=,iv:X353ueD7yIUkmcHEZ7xpn7UKwe9DJRJyRkr8yP91LlU=,tag:iFRX2/A38+ZP6xaSOXTAXQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
