---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: racknas-services-trek
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: racknas-services-trek
  resources:
    requests:
      storage: 1Ti
