apiVersion: v1
kind: Secret
metadata:
  name: credentials-tracearr
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:/l+bOyl8Oyg=,iv:p6RRdU1EbxUhMVYlt31HefVLgy3wyPE3MIUayQ/3k60=,tag:7oefPsezoivk6Cgrfc85wQ==,type:str]
  password: ENC[AES256_GCM,data:4MqEYxgHVjfYACaRyhROHraERkqiOsZMEPiu+4hGuc+tPfBqPsg+eZyKi+6AuEd8,iv:SaspxaQsEqcNu89JRqu6wmldIByYvWxDQNCyrjUbL5U=,tag:GQwEaewyzO2v4/wQlVQhkQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMG5TcEFCKzVENzV3VDFY
        MERtaGNObTFrL044SE1taWRsQ3hDdU0vM2hrClNBUGhNbzQ3cHE0ckRLNWo4eVlk
        bmYxUVgzbkViTmJnc3NhVU51bU5sYVkKLS0tIHk5YWk1eElHc1U0V3lMNURyclh4
        T1ZueUovWWxuRFJQaTBVNjZJbE9La0EKmbHdi/CFMY86uYvzWlotffQ63lehcdtj
        cD+QSW310uzWYrnQIG0Mt1KNkqiSeDA/M6CrbeBO2ae/3sZ2g3oUFQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-08T03:55:26Z"
  mac: ENC[AES256_GCM,data:DH42ccxkihjAfp52vAaZdFf65vjExdV2Jnfbzpb8Aj2rUmbOgO1s+XEJOtxd2e1kwnjpWLZpcLb5pdm0wkayEyleIbY3dQM8W0ofEIBwXGFnzGd99cZ14nlvvypAjcqcxEYSD7K18lelUtEFU8kD7PCY6v3xegD5T9AEfJy7YRY=,iv:QS7ztKOJuT983dmyK1rZAkKfpo1Mk4ycrVm70TufTxk=,tag:ia0vG24Elii6lzcLU+j/Jw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
