apiVersion: v1
kind: Secret
metadata:
  name: credentials-timescale-backup-s3
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:BGM4tyo0iVqJxJ+nw4MIyZGagbc=,iv:l4jQZAN1YuizucbdhzPea465+kA9qCV2fJBrbZP7iyE=,tag:Frg5gDn2BxGDhzDeoJAREQ==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:JEA73UDciz7qtRDLN6B+14+qoLj7l3tzFzUfDLy0x6QXytReR9BTbw==,iv:fV1xU4Gr1ioypWbnuCxCpjWvE6V+RekQdnLAWbPacB4=,tag:ec8LGdlmywci/0arW3M4lA==,type:str]
  REGION: ENC[AES256_GCM,data:8BajDNfNvPvX,iv:daQk+vYJlAPFxNSzqlnCCu3majuWT4MJqOtCA0kW/ys=,tag:tmOOlAVXk0QDuvGPLSQLwQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOUwyR0lJSVo0YmJYakhC
        bnRUcEc1aUZoRkt3UER0WVEvNjBZeFIwSnlvCnpnTG1JbDZEQmkyRU5ZTUVyV1Ji
        SFNNc2VrS0ZqaGlSTDgvZkFJNzdmK2cKLS0tIG5BNUVFbVh5am9qU0ozd2NNanV0
        cmdUenNGdGtoc1VOOXFQVTExbzRaSHcKdibdwm8DdNSvbDxD+HQrz1S+/aFTjV9n
        pR6RGGiN+ROjtKLpzzBZXcU3k0BYTzLMIgjDgwfLzCPGB6iry1LycA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-08T03:53:17Z"
  mac: ENC[AES256_GCM,data:DnpadE6F1OdRC003o7Jf5TNM+6VlHroWK2FaqYkH8BponTAqoyZ/oMFOKZvtlsippfGQeWsJgLh9D6Z0TYOWUAt3MWP2U+UrI5RGuRzDpuycXv5KeXl/9jKa99kFk1Bix02qMvbrufxUvHbb2okzwJAOICachObAgNYxzuO1UA0=,iv:01etGTdNWp7Qg9HxWSPcnV9rK8GHvhOYcU03zHw1Msg=,tag:BUzS4K6XCWOO0wvllvp5Yw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
