apiVersion: v1
kind: Secret
metadata:
  name: credentials-lubelogger
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:7wXuJeAaYhVnkg==,iv:/s5agdLW0Qw45n5qT0uRlpQMFl6gL/8dvusG90HflO4=,tag:Qyy5vzSWU/XOQlT8MYJVRQ==,type:str]
  password: ENC[AES256_GCM,data:3TsOMfL3EvvTsfzkWgVIbooLf3MY9ztkflnnte4l9npVJHIjDzcGarRoPOsIQUDoDuXuwV5pBeuGOv+JE1tJLw==,iv:g0LP3/hiFoDiihlHdvq29oqrNI3nl8s3V+e6mCPdFqo=,tag:/7MRXl8D064PItblIk1KWA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbUtBbVdiYmxKQ1BLci82
        K2RsamVnNWQ1Snl2L1laMVZUOG9vRXJGeTNrCis0REg5ZCs4Sm5tcVBtNXp2cjN0
        R0FqdDkzUDJ4cGlqYWltSGxmTE9TYlkKLS0tIEJqR1NhNjBBSDJrVWIvdjdiVVZU
        SzVDbUN6WTZhVnZBaSs3enpRRi80SUkKh2bsMNWDauhOQCbianS77aKa9o+dd8Jx
        Z6V4iG7PLUFSpsUDu8wNlNSXSz5hyPfNhH3XAlp9O2aaNum51xMUnw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-08T02:51:41Z"
  mac: ENC[AES256_GCM,data:fwfLun7hIxSy/oSFrkBjaJcda2fXp1OAymtnDxzeFwG1tUU/h2KrTVrOzLJRcLqYNqEN5QcOy2rZkII95HHqMEma959VxmENcHi54WvqYNVOHmgQ5LVanN+Dp5vQP5Wruc/To7ZRSa4Xd8/Q7FP0SNtfHXDryqR8oJ/A7o56mAs=,iv:8GvMsgQp7xzPJsJm5vHNqYtQ/pV9MdTbGTBJ19Q3HaM=,tag:3TGTplHMecPLSMSwqdYXQA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
