apiVersion: v1
kind: Secret
metadata:
  name: credentials-jellystat
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:kZLWx34hJ5zJ,iv:P4UwBeiTgb28uRyO7ClRK4WIpTbbiCIhQkwQRi/Rf5s=,tag:TBHlMD8dbP2vdkm/CgTINA==,type:str]
  password: ENC[AES256_GCM,data:MLovxxsY5cUor9UZBpi9Yr6UeevTEbPSjDrRw1Fjh+zPf/oyLOy9vPo/c5Gft3lk,iv:aQpDKrUDhYtTEiKDrbEaY1DuU/NNh1QgoKoUe7prOoY=,tag:qv3nVOn914JJ7R3mflMucg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbmdUWDhDcVZKTXFZaG1L
        UUx4eHhqbDMzaUhDQk5OSlhRWjJHR2dVcHhVCng3SVYyTVVNVS9DeStKWDAwN05Q
        dE44UlVpaS9pTFhqZVJ3bDYyeHg1dlkKLS0tIHNpc2p0TERWY2lMUzlwVDFjVklj
        R3pzY3RKMFk4OWhvNFFhaUttREZlZzgKoTnY8roUuj5TiTVwEYr0c5/JnYEL9AVm
        UNc3Sxi0lgEPDIL1WfeJ9xKcaEYjyb0gBDEi3whgRQwQiHxFI7qe5w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-08T02:51:35Z"
  mac: ENC[AES256_GCM,data:vi7L/6c9CIxf2K75i9ABJ52K3UXlHlnF5DAQXJUMzzQta3mDLNu3ddrTGfdDFQaR5elXDD+TjUnbxvrUacpnZ8mpwxkvYugFQ7pd2e3xT2Sh1B9NwHDwi9kjLKwMV+riLG3WwXlBqmfIIKC1hTAhtXiWpl/R+vZQ6/d9/s7AtP0=,iv:QE0azqRgAHC2H+gLgefR1TlOBaa/CH+iQ8mXQKTNtWc=,tag:ANHP0xIiJlm/5AMsd2SbgA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
