apiVersion: v1
kind: Secret
metadata:
  name: credentials-dawarich
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:0a4hZg7clOE=,iv:h0VmVuEuXSpvHSH3QHZPempeOgiAkJD1Z++VxmAvWfc=,tag:iFvA3lojhIPK5BN6rrg8qA==,type:str]
  password: ENC[AES256_GCM,data:YBKYv9+BH60eqamu8adHypTMp1uf8knkVTgYyR+XHzgQnioJnRA3X3Y6ezu9sV6PfIIWa+mw2XoChZU9lKEs4w==,iv:2ot0c/W326Ky8qLxzea2vfoETUL6wPWZpcYqXtvtxws=,tag:09WIxdco7cp7UWcUR9vGFg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RURWRERaYWU3SWZHZ3lG
        bzZ1clU2ODNTbGQzMXJpWE1wZkhnTXVGU1NRCld5Q3RwMW05aDFlWWpwYTRqTWNj
        NFBKeEhVbFBIdVZFK1pCcXdNTGF2VGsKLS0tIFlBbC9KR2xBU0xUbVQxNEpCRTQz
        TUxtVWRkMmtwQllTQndES1BqZEt0dEkKdCuXGTOJdbtEz43Mfi/4jl7CKvGzHNh8
        qVIOGvu72hKVfUUxSHM7Zsh5SHdLAZV59M/5VUflmX3wnPoDw67B+Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T20:46:16Z"
  mac: ENC[AES256_GCM,data:61TwAvpd82F/GZdfhJVco3y3YD/G0lS4oWEd6nvgU81KseeWBBmD7OIvZ5gmiecabkEsnp0MZ1SF3NuSlrsbJiRzTVoaBvm1RM9RBYdGpXTNWfqgkbeKuQtLr6TUtHAm56kr4i2skxfKQ/E2IpYwinCP/9HrlzDPJhV3Knfda4w=,iv:JtJMGSDVhelMBE5d6ZBGtdSwIWfjCEkQsYQtAuLtcdU=,tag:AkFguA6Akzo8Xewj/9L32A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
