apiVersion: v1
kind: Secret
metadata:
  name: credentials-admin
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:1McTCC3lPCI=,iv:4feyWQtr8hNSsXx3Y3uYRQwyVZkjcR8t+VQwHtycJI4=,tag:VgajNifDofkMqARM1WOCZw==,type:str]
  password: ENC[AES256_GCM,data:dCDOg3i17hSNMVdfQinIntu1xOndypNl1ipxiW9B2wwZoR0Fm8Zdr2ytgQ3jUOme,iv:2inQTOwkty2Db9VVhZtlD4fMkauUSd87o+o/uuD3C/c=,tag:zvbkSPQsLXQl7CRc0tx8Ew==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaE1tbDREZjYycTVwNkN0
        Z29FaU5SaTV3c3VNVTZwQlI3a29ySnRaenc0CnViOWt1anBWOWlaMTJqOHlkM1Fo
        SE5yMnhFS2Q2cVREL1RIY2RJanBkVDAKLS0tIFhSRExqVFZtSW9GcEpXNmlCSXAw
        ZnFVY1BHTUtWNnh5c0Y5cThGNGJYZjAK6aQZBHJVJyLfC3jTBHDLLY/SLmzSu1zT
        qgb0SQv5wIA++uXmIVkpgeezyTqy62yuEirwI2NKqQVCAN0wswXxVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T21:03:08Z"
  mac: ENC[AES256_GCM,data:TzUOpfnjvkOc3iP9ha2FdMqzGlnRu7lVJXcxqIxS9oRtOJJRRcsOWOWXUI0n2o8l0ssa/ETr044r+AtHAvI6JsfMYxhcMgCAwsdibJ6a62ABGtOrGlGf5T93v2xVOkhyO11thUSB7Z/SfKAkuuE7VumQD8j9ly/Peoob4Wak3vw=,iv:iuPz2y80iBXztWr3o5+Z31e47Jwap0waqLF/nxeNCGs=,tag:/kVtgDO0I0Ema1SaWmWjgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-hass
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:iuOxTw==,iv:0WDofzD4fMdv7TOVw59vBrHWInINb5VyHNETWqflx2k=,tag:ckhpZM7ZKUfSwu8WK17Wsg==,type:str]
  password: ENC[AES256_GCM,data:8QoRMSpORPD8w1RgZxspKtAlwMVHAGqQaSMQs/WeOV/9etX48I2mADLHh/jzTUvh,iv:gSigM61ocwFmRAEESHnu1SxK6AU+UpVkpTwx7Ps+Vd8=,tag:+PMZeZhF1F2rESCYFNZ5yQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaE1tbDREZjYycTVwNkN0
        Z29FaU5SaTV3c3VNVTZwQlI3a29ySnRaenc0CnViOWt1anBWOWlaMTJqOHlkM1Fo
        SE5yMnhFS2Q2cVREL1RIY2RJanBkVDAKLS0tIFhSRExqVFZtSW9GcEpXNmlCSXAw
        ZnFVY1BHTUtWNnh5c0Y5cThGNGJYZjAK6aQZBHJVJyLfC3jTBHDLLY/SLmzSu1zT
        qgb0SQv5wIA++uXmIVkpgeezyTqy62yuEirwI2NKqQVCAN0wswXxVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T21:03:08Z"
  mac: ENC[AES256_GCM,data:TzUOpfnjvkOc3iP9ha2FdMqzGlnRu7lVJXcxqIxS9oRtOJJRRcsOWOWXUI0n2o8l0ssa/ETr044r+AtHAvI6JsfMYxhcMgCAwsdibJ6a62ABGtOrGlGf5T93v2xVOkhyO11thUSB7Z/SfKAkuuE7VumQD8j9ly/Peoob4Wak3vw=,iv:iuPz2y80iBXztWr3o5+Z31e47Jwap0waqLF/nxeNCGs=,tag:/kVtgDO0I0Ema1SaWmWjgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-jellystat
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:sfhUJBaui4oT,iv:cUAPCKx0uLECAvRnDvBygLZsqMdZzgOMT/1OCAKo5Jo=,tag:UGlFOCTPEqaz31loDiyePQ==,type:str]
  password: ENC[AES256_GCM,data:5VQycUDXeZ0NMTLn87ANai0+ABfzAm0eVlmV/2a9ztqJXjkiy4XWsTO5qBmar+Tq,iv:eZyXpgmLqWq0q8459g6gHX7/DX1Q91bl9YKBlE75EmE=,tag:UIHoSO5x+icaNEI8Z1WWGQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaE1tbDREZjYycTVwNkN0
        Z29FaU5SaTV3c3VNVTZwQlI3a29ySnRaenc0CnViOWt1anBWOWlaMTJqOHlkM1Fo
        SE5yMnhFS2Q2cVREL1RIY2RJanBkVDAKLS0tIFhSRExqVFZtSW9GcEpXNmlCSXAw
        ZnFVY1BHTUtWNnh5c0Y5cThGNGJYZjAK6aQZBHJVJyLfC3jTBHDLLY/SLmzSu1zT
        qgb0SQv5wIA++uXmIVkpgeezyTqy62yuEirwI2NKqQVCAN0wswXxVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T21:03:08Z"
  mac: ENC[AES256_GCM,data:TzUOpfnjvkOc3iP9ha2FdMqzGlnRu7lVJXcxqIxS9oRtOJJRRcsOWOWXUI0n2o8l0ssa/ETr044r+AtHAvI6JsfMYxhcMgCAwsdibJ6a62ABGtOrGlGf5T93v2xVOkhyO11thUSB7Z/SfKAkuuE7VumQD8j9ly/Peoob4Wak3vw=,iv:iuPz2y80iBXztWr3o5+Z31e47Jwap0waqLF/nxeNCGs=,tag:/kVtgDO0I0Ema1SaWmWjgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-firefly
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:xqnV1JN+Aw==,iv:03KbywMVTcJ8y2yQSp3FKZb0D7hI3diB5FjVeh1SHIk=,tag:1nVPXzuSh78G2p1dXFcMGw==,type:str]
  password: ENC[AES256_GCM,data:q+0gwLIind8vWw1t3bM36QJnttk9To7wW3lk8LSLoLe5NAm4rSsQCYn+T67CwoUo,iv:GYDdE0AV6VgiIg7DmqwTBO6m+YDjOp13aEYr6biiZds=,tag:OsFq4W5/y+vGhMt5+4JMSA==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaE1tbDREZjYycTVwNkN0
        Z29FaU5SaTV3c3VNVTZwQlI3a29ySnRaenc0CnViOWt1anBWOWlaMTJqOHlkM1Fo
        SE5yMnhFS2Q2cVREL1RIY2RJanBkVDAKLS0tIFhSRExqVFZtSW9GcEpXNmlCSXAw
        ZnFVY1BHTUtWNnh5c0Y5cThGNGJYZjAK6aQZBHJVJyLfC3jTBHDLLY/SLmzSu1zT
        qgb0SQv5wIA++uXmIVkpgeezyTqy62yuEirwI2NKqQVCAN0wswXxVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T21:03:08Z"
  mac: ENC[AES256_GCM,data:TzUOpfnjvkOc3iP9ha2FdMqzGlnRu7lVJXcxqIxS9oRtOJJRRcsOWOWXUI0n2o8l0ssa/ETr044r+AtHAvI6JsfMYxhcMgCAwsdibJ6a62ABGtOrGlGf5T93v2xVOkhyO11thUSB7Z/SfKAkuuE7VumQD8j9ly/Peoob4Wak3vw=,iv:iuPz2y80iBXztWr3o5+Z31e47Jwap0waqLF/nxeNCGs=,tag:/kVtgDO0I0Ema1SaWmWjgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-immich
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:1KsajWiy,iv:2u5PtTvvfy80DJ0rKpdPflmeFj58J++DZ/qSoz1V4f4=,tag:8YZMWJ6JJOqodFR2J0LuDw==,type:str]
  password: ENC[AES256_GCM,data:upmjyx5Sl0e5KahPuBBWDSTXvK96vmjxq1nEAjkadj9fdFJmx0xaKFG1jJDoQj2K,iv:eW7x1GC+IQKlbIsVEb/nt2cwmlZjdiAWJeUBRZqt9YU=,tag:1g+M73uBmTwLF2o+6QsZ/w==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaE1tbDREZjYycTVwNkN0
        Z29FaU5SaTV3c3VNVTZwQlI3a29ySnRaenc0CnViOWt1anBWOWlaMTJqOHlkM1Fo
        SE5yMnhFS2Q2cVREL1RIY2RJanBkVDAKLS0tIFhSRExqVFZtSW9GcEpXNmlCSXAw
        ZnFVY1BHTUtWNnh5c0Y5cThGNGJYZjAK6aQZBHJVJyLfC3jTBHDLLY/SLmzSu1zT
        qgb0SQv5wIA++uXmIVkpgeezyTqy62yuEirwI2NKqQVCAN0wswXxVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T21:03:08Z"
  mac: ENC[AES256_GCM,data:TzUOpfnjvkOc3iP9ha2FdMqzGlnRu7lVJXcxqIxS9oRtOJJRRcsOWOWXUI0n2o8l0ssa/ETr044r+AtHAvI6JsfMYxhcMgCAwsdibJ6a62ABGtOrGlGf5T93v2xVOkhyO11thUSB7Z/SfKAkuuE7VumQD8j9ly/Peoob4Wak3vw=,iv:iuPz2y80iBXztWr3o5+Z31e47Jwap0waqLF/nxeNCGs=,tag:/kVtgDO0I0Ema1SaWmWjgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-backup-s3
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:iCkl5Gqp139IFBBJRU2ly9+MKtOEgooVnw4=,iv:LwMmtFT0/EVu/8b/9kWtnG12yl8uTJhNwd33oseA3uE=,tag:WyqceKdynAI/POw3o/7nzA==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:+2zRse1wOQiQQl5uL0wNPtROJfeTvPjWggA+K4x9udwktnN8tdPCpf+pz1mETpXNQz+s9BgoJvOJZQLT8dzq/g==,iv:CO7WCeGKwGWUaay4drjMOXK1fr/Y+5+NOcL+W5lUblc=,tag:4AOyHXFS29Vu5pMbCT5APQ==,type:str]
  REGION: ENC[AES256_GCM,data:wFx/FgcnHQ==,iv:pmY3lhCXqB7/gv3FfCQ/3RXxOZAHZqKKxTTteKyIlaw=,tag:Xl+D1S9YvPj7aDYGi46UBw==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaE1tbDREZjYycTVwNkN0
        Z29FaU5SaTV3c3VNVTZwQlI3a29ySnRaenc0CnViOWt1anBWOWlaMTJqOHlkM1Fo
        SE5yMnhFS2Q2cVREL1RIY2RJanBkVDAKLS0tIFhSRExqVFZtSW9GcEpXNmlCSXAw
        ZnFVY1BHTUtWNnh5c0Y5cThGNGJYZjAK6aQZBHJVJyLfC3jTBHDLLY/SLmzSu1zT
        qgb0SQv5wIA++uXmIVkpgeezyTqy62yuEirwI2NKqQVCAN0wswXxVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T21:03:08Z"
  mac: ENC[AES256_GCM,data:TzUOpfnjvkOc3iP9ha2FdMqzGlnRu7lVJXcxqIxS9oRtOJJRRcsOWOWXUI0n2o8l0ssa/ETr044r+AtHAvI6JsfMYxhcMgCAwsdibJ6a62ABGtOrGlGf5T93v2xVOkhyO11thUSB7Z/SfKAkuuE7VumQD8j9ly/Peoob4Wak3vw=,iv:iuPz2y80iBXztWr3o5+Z31e47Jwap0waqLF/nxeNCGs=,tag:/kVtgDO0I0Ema1SaWmWjgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-lubelogger
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:+FMZc2X+stJo6w==,iv:7wfVNj8/3PwLdUnwmopNuDwwftaE024M1W3xL1lS4KM=,tag:wgsyUGRNLbNUxgAFfbu3Vg==,type:str]
  password: ENC[AES256_GCM,data:IDSrPTn/Mtj15XmJQJtf7fuo8fB6J7ZGsZ+Xez55oYhX+CHRLM9nYaDkx1sDtIoCSi9q0zHWRrrpWmOqeTsphQ==,iv:7CUau8+i+Bezb096JQvfnDp6nOBkKcIRkGRn43INilw=,tag:y3U8qUWf/0LD77a97TkZqQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaE1tbDREZjYycTVwNkN0
        Z29FaU5SaTV3c3VNVTZwQlI3a29ySnRaenc0CnViOWt1anBWOWlaMTJqOHlkM1Fo
        SE5yMnhFS2Q2cVREL1RIY2RJanBkVDAKLS0tIFhSRExqVFZtSW9GcEpXNmlCSXAw
        ZnFVY1BHTUtWNnh5c0Y5cThGNGJYZjAK6aQZBHJVJyLfC3jTBHDLLY/SLmzSu1zT
        qgb0SQv5wIA++uXmIVkpgeezyTqy62yuEirwI2NKqQVCAN0wswXxVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T21:03:08Z"
  mac: ENC[AES256_GCM,data:TzUOpfnjvkOc3iP9ha2FdMqzGlnRu7lVJXcxqIxS9oRtOJJRRcsOWOWXUI0n2o8l0ssa/ETr044r+AtHAvI6JsfMYxhcMgCAwsdibJ6a62ABGtOrGlGf5T93v2xVOkhyO11thUSB7Z/SfKAkuuE7VumQD8j9ly/Peoob4Wak3vw=,iv:iuPz2y80iBXztWr3o5+Z31e47Jwap0waqLF/nxeNCGs=,tag:/kVtgDO0I0Ema1SaWmWjgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-openbrain
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:wPZ7bWXAlQcl,iv:YVagatFsoZ+ZGZps+xaln2EDKYAK62Ue8Yf852Yl/xE=,tag:Gxh/8vsNElCQVUABvzAvmw==,type:str]
  password: ENC[AES256_GCM,data:0LOmy+N8TQUoTicRBNK4WUO8Ut4oRhH6mt02uu+odPmF4t3B4Gkrm8hOTW7ZgXOOkAZXhWw4dOjGtj4R3VxZYw==,iv:kpnRwl7udRMby/PcMmcbxB3fGN6xs8eMDg3/4uXiAdM=,tag:fcLdf+R9fBqCIg3Ik2me5Q==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaE1tbDREZjYycTVwNkN0
        Z29FaU5SaTV3c3VNVTZwQlI3a29ySnRaenc0CnViOWt1anBWOWlaMTJqOHlkM1Fo
        SE5yMnhFS2Q2cVREL1RIY2RJanBkVDAKLS0tIFhSRExqVFZtSW9GcEpXNmlCSXAw
        ZnFVY1BHTUtWNnh5c0Y5cThGNGJYZjAK6aQZBHJVJyLfC3jTBHDLLY/SLmzSu1zT
        qgb0SQv5wIA++uXmIVkpgeezyTqy62yuEirwI2NKqQVCAN0wswXxVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T21:03:08Z"
  mac: ENC[AES256_GCM,data:TzUOpfnjvkOc3iP9ha2FdMqzGlnRu7lVJXcxqIxS9oRtOJJRRcsOWOWXUI0n2o8l0ssa/ETr044r+AtHAvI6JsfMYxhcMgCAwsdibJ6a62ABGtOrGlGf5T93v2xVOkhyO11thUSB7Z/SfKAkuuE7VumQD8j9ly/Peoob4Wak3vw=,iv:iuPz2y80iBXztWr3o5+Z31e47Jwap0waqLF/nxeNCGs=,tag:/kVtgDO0I0Ema1SaWmWjgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
