apiVersion: v1
kind: Secret
metadata:
  name: credentials-admin
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:HaBSZBB6YF0=,iv:dI+Ka+fV9Sy3gpaNPwFfGeFKBR4fqc5WxJsOlgjFaao=,tag:nnvKPBz4HvCvFSq5MXfNzA==,type:str]
  password: ENC[AES256_GCM,data:/f0rpC/Jac1SulC1QbfdGli23cstYLrblPuGSfNIU0vS1dw5jO1XF5Ff2N6rzwKA,iv:1wa/gU9xPavMrMa8IXIl4Qj9FS1X29esTOidDD1Gqj8=,tag:p8izy8l78NSvClEARxoqBg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWmdOTW9lVzJacUY5Njhv
        NDVsRGh1dFNlVFZRODhrQzI4WVNROW9Ma1JrCnRGb0QxZzF0eSttbUFDYWJQSG1y
        R2dKcWg3Y1dreDg1czQ4aDA2cHFnRGsKLS0tIGhpaVBiM3B1NTlaZXFwMXc2Rkg2
        WHhXODNQM3RWUlArYU9UMUM3QkJ0ZkEKUtrQk0ksm/zdCD0Uz5nlkVnPNcdqAgn9
        h8uGmHOwwq5YCI+yzv0mkS68iTtARG10Zt81ReA6yBCD8/OGrEqzxg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-19T02:56:14Z"
  mac: ENC[AES256_GCM,data:lD+AEjvrNfBN+pcDQCfzTtcwL1a9HF9pyPxNjndKLbgjFm+sHg9bfp4d5of+7hxv6vJhdc+T51XQ/jGBPIvkSCFjtGkKF/2xIQwrCWGUVtc9tO2K6dHlu+jtK4P5Hhjcdy1PnsJqwLBS9SvBcZXUxYxWFv82u2EJO69TW2oEyVE=,iv:fufasDXoZtIosjmE+J7G/pfY1KhXI6f1WrgzmtKtNv0=,tag:1NpCyGDY0tDQPFRI2yl09w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-hass
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:P2XIBg==,iv:lTbcXgBw+FPomDdo+7pwhCliqAorS0NiTW6h1Vu66KI=,tag:9FwEFv/PFqmopJr6DV67MQ==,type:str]
  password: ENC[AES256_GCM,data:YTwyN9sCJlfOkrtG5Yz52Y7mDMsS9sbvf7tlV+EfZG0QZxlG+4jJ3pSK4KqFdIqF,iv:8yI8ri/yBYKY5Jp+7lGzaa3WPtVkpVfi428+VKN0OsY=,tag:q6std4DLNqPXSOsk3rd5iQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWmdOTW9lVzJacUY5Njhv
        NDVsRGh1dFNlVFZRODhrQzI4WVNROW9Ma1JrCnRGb0QxZzF0eSttbUFDYWJQSG1y
        R2dKcWg3Y1dreDg1czQ4aDA2cHFnRGsKLS0tIGhpaVBiM3B1NTlaZXFwMXc2Rkg2
        WHhXODNQM3RWUlArYU9UMUM3QkJ0ZkEKUtrQk0ksm/zdCD0Uz5nlkVnPNcdqAgn9
        h8uGmHOwwq5YCI+yzv0mkS68iTtARG10Zt81ReA6yBCD8/OGrEqzxg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-19T02:56:14Z"
  mac: ENC[AES256_GCM,data:lD+AEjvrNfBN+pcDQCfzTtcwL1a9HF9pyPxNjndKLbgjFm+sHg9bfp4d5of+7hxv6vJhdc+T51XQ/jGBPIvkSCFjtGkKF/2xIQwrCWGUVtc9tO2K6dHlu+jtK4P5Hhjcdy1PnsJqwLBS9SvBcZXUxYxWFv82u2EJO69TW2oEyVE=,iv:fufasDXoZtIosjmE+J7G/pfY1KhXI6f1WrgzmtKtNv0=,tag:1NpCyGDY0tDQPFRI2yl09w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-jellystat
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:Ts1Hcu96zotj,iv:KOEituoteJEHlfieUKYDxoEg+KKimJNh1xcI7wmXGRo=,tag:HxbK7Txgoha+QzsqSVGJKw==,type:str]
  password: ENC[AES256_GCM,data:STIcxE/htsBI1oDxerOQ95cxNtRdRXSIeGuJYHP08Dp+h7O16LFUKOAlYYH1v4cB,iv:O/TkLOtXaojeR5OM5+UvuCwlK8YrA2Zzx5SmUrVzj+s=,tag:53G5BDsrOwAJSDNZoavNTg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWmdOTW9lVzJacUY5Njhv
        NDVsRGh1dFNlVFZRODhrQzI4WVNROW9Ma1JrCnRGb0QxZzF0eSttbUFDYWJQSG1y
        R2dKcWg3Y1dreDg1czQ4aDA2cHFnRGsKLS0tIGhpaVBiM3B1NTlaZXFwMXc2Rkg2
        WHhXODNQM3RWUlArYU9UMUM3QkJ0ZkEKUtrQk0ksm/zdCD0Uz5nlkVnPNcdqAgn9
        h8uGmHOwwq5YCI+yzv0mkS68iTtARG10Zt81ReA6yBCD8/OGrEqzxg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-19T02:56:14Z"
  mac: ENC[AES256_GCM,data:lD+AEjvrNfBN+pcDQCfzTtcwL1a9HF9pyPxNjndKLbgjFm+sHg9bfp4d5of+7hxv6vJhdc+T51XQ/jGBPIvkSCFjtGkKF/2xIQwrCWGUVtc9tO2K6dHlu+jtK4P5Hhjcdy1PnsJqwLBS9SvBcZXUxYxWFv82u2EJO69TW2oEyVE=,iv:fufasDXoZtIosjmE+J7G/pfY1KhXI6f1WrgzmtKtNv0=,tag:1NpCyGDY0tDQPFRI2yl09w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-firefly
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:f9JmcqAmlg==,iv:7njTG/4eOw0uVNxCfmn/zyrvEo8WCb7MN8Byy1ztitk=,tag:8PgGQkdWTfiWWWli+f2hRA==,type:str]
  password: ENC[AES256_GCM,data:yeivszEbjPBQ8Eek7golMEvZps8tDnAkKZZ5UCTNvtDASme61ZPu9X0n3xMbnPMD,iv:stTwSwsYTDaqOFCsLZGN/h3zXKEJHuF5CuKO443oekI=,tag:9RgKOyxzMWfG7U/hugvhTA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWmdOTW9lVzJacUY5Njhv
        NDVsRGh1dFNlVFZRODhrQzI4WVNROW9Ma1JrCnRGb0QxZzF0eSttbUFDYWJQSG1y
        R2dKcWg3Y1dreDg1czQ4aDA2cHFnRGsKLS0tIGhpaVBiM3B1NTlaZXFwMXc2Rkg2
        WHhXODNQM3RWUlArYU9UMUM3QkJ0ZkEKUtrQk0ksm/zdCD0Uz5nlkVnPNcdqAgn9
        h8uGmHOwwq5YCI+yzv0mkS68iTtARG10Zt81ReA6yBCD8/OGrEqzxg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-19T02:56:14Z"
  mac: ENC[AES256_GCM,data:lD+AEjvrNfBN+pcDQCfzTtcwL1a9HF9pyPxNjndKLbgjFm+sHg9bfp4d5of+7hxv6vJhdc+T51XQ/jGBPIvkSCFjtGkKF/2xIQwrCWGUVtc9tO2K6dHlu+jtK4P5Hhjcdy1PnsJqwLBS9SvBcZXUxYxWFv82u2EJO69TW2oEyVE=,iv:fufasDXoZtIosjmE+J7G/pfY1KhXI6f1WrgzmtKtNv0=,tag:1NpCyGDY0tDQPFRI2yl09w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-immich
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:LID8RRzr,iv:jlqDBxFMHpXUXVNj/wzGTWGtx2fov9vUefjgxgwELgM=,tag:iQUa5S3nWb/ZqVLvauv2Nw==,type:str]
  password: ENC[AES256_GCM,data:/OHEPi586yTr7qMudXmIg8ig2sOZOXnnbsHxsMKflIZMeURaObrsM5Jlgt8skA9/,iv:GmY9jT/lKxGzVI6UAJVHcnu7PToJDLg7h0443qrb+4k=,tag:abSJomdF1UDdK5U6uL8A5A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWmdOTW9lVzJacUY5Njhv
        NDVsRGh1dFNlVFZRODhrQzI4WVNROW9Ma1JrCnRGb0QxZzF0eSttbUFDYWJQSG1y
        R2dKcWg3Y1dreDg1czQ4aDA2cHFnRGsKLS0tIGhpaVBiM3B1NTlaZXFwMXc2Rkg2
        WHhXODNQM3RWUlArYU9UMUM3QkJ0ZkEKUtrQk0ksm/zdCD0Uz5nlkVnPNcdqAgn9
        h8uGmHOwwq5YCI+yzv0mkS68iTtARG10Zt81ReA6yBCD8/OGrEqzxg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-19T02:56:14Z"
  mac: ENC[AES256_GCM,data:lD+AEjvrNfBN+pcDQCfzTtcwL1a9HF9pyPxNjndKLbgjFm+sHg9bfp4d5of+7hxv6vJhdc+T51XQ/jGBPIvkSCFjtGkKF/2xIQwrCWGUVtc9tO2K6dHlu+jtK4P5Hhjcdy1PnsJqwLBS9SvBcZXUxYxWFv82u2EJO69TW2oEyVE=,iv:fufasDXoZtIosjmE+J7G/pfY1KhXI6f1WrgzmtKtNv0=,tag:1NpCyGDY0tDQPFRI2yl09w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-backup-s3
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:PRYitIJOMyUhmc9+MbSk9HCT/pH8+XypOMM=,iv:qWajf4bHxvwOBGhspIDhwMBSDnx+hyw9C4fk6mHcRD4=,tag:giVGUZ7PqwufHYq+mzCo2Q==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:KMAk3JSh9oj0ZEUWbHhM3a/hGsYFO8AppEvCYVOFdQTdaWP4vjCMUfV2e9gebwgi+xtSWiptizRzPi3rE18QWA==,iv:+XcIL9ddqfyfiNfsWgccS3xkgExWsVIMTsao6yOhTcM=,tag:rPDLx7IRGBPX65yLqbm3Ug==,type:str]
  REGION: ENC[AES256_GCM,data:fqnIPfdtLg==,iv:+nL/l6KgDCsS048J9M+HhNmmT5rf9NG/bOqfSA5NqXE=,tag:Liav1BPX5quZcJgalhNZGQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWmdOTW9lVzJacUY5Njhv
        NDVsRGh1dFNlVFZRODhrQzI4WVNROW9Ma1JrCnRGb0QxZzF0eSttbUFDYWJQSG1y
        R2dKcWg3Y1dreDg1czQ4aDA2cHFnRGsKLS0tIGhpaVBiM3B1NTlaZXFwMXc2Rkg2
        WHhXODNQM3RWUlArYU9UMUM3QkJ0ZkEKUtrQk0ksm/zdCD0Uz5nlkVnPNcdqAgn9
        h8uGmHOwwq5YCI+yzv0mkS68iTtARG10Zt81ReA6yBCD8/OGrEqzxg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-19T02:56:14Z"
  mac: ENC[AES256_GCM,data:lD+AEjvrNfBN+pcDQCfzTtcwL1a9HF9pyPxNjndKLbgjFm+sHg9bfp4d5of+7hxv6vJhdc+T51XQ/jGBPIvkSCFjtGkKF/2xIQwrCWGUVtc9tO2K6dHlu+jtK4P5Hhjcdy1PnsJqwLBS9SvBcZXUxYxWFv82u2EJO69TW2oEyVE=,iv:fufasDXoZtIosjmE+J7G/pfY1KhXI6f1WrgzmtKtNv0=,tag:1NpCyGDY0tDQPFRI2yl09w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-lubelogger
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:1uvKacbZVBXoaA==,iv:KBtnRRcGw9UMAqK3lsomWECzivgz+a6aX+L+h4Mgfdo=,tag:cVXp4RmokH8WU3raebOQeg==,type:str]
  password: ENC[AES256_GCM,data:wGeg3p7hVctmEmL70JBCsSKg2CN/lwR47caVr1GKAuNSe/k6sjlFbfTK8P4pGXYco9VAJmjcQ+DUpGrF9XtdRQ==,iv:EyJPX9Cvd7D9TFdYcKA5uEB3R3IYgrPHMjf6PdwtzEo=,tag:lpE+f7wM9y8P6a7NfZaX2g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWmdOTW9lVzJacUY5Njhv
        NDVsRGh1dFNlVFZRODhrQzI4WVNROW9Ma1JrCnRGb0QxZzF0eSttbUFDYWJQSG1y
        R2dKcWg3Y1dreDg1czQ4aDA2cHFnRGsKLS0tIGhpaVBiM3B1NTlaZXFwMXc2Rkg2
        WHhXODNQM3RWUlArYU9UMUM3QkJ0ZkEKUtrQk0ksm/zdCD0Uz5nlkVnPNcdqAgn9
        h8uGmHOwwq5YCI+yzv0mkS68iTtARG10Zt81ReA6yBCD8/OGrEqzxg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-19T02:56:14Z"
  mac: ENC[AES256_GCM,data:lD+AEjvrNfBN+pcDQCfzTtcwL1a9HF9pyPxNjndKLbgjFm+sHg9bfp4d5of+7hxv6vJhdc+T51XQ/jGBPIvkSCFjtGkKF/2xIQwrCWGUVtc9tO2K6dHlu+jtK4P5Hhjcdy1PnsJqwLBS9SvBcZXUxYxWFv82u2EJO69TW2oEyVE=,iv:fufasDXoZtIosjmE+J7G/pfY1KhXI6f1WrgzmtKtNv0=,tag:1NpCyGDY0tDQPFRI2yl09w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
