apiVersion: v1
kind: Secret
metadata:
  name: credentials-backup-s3
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:WQAr0o55+1sTiLLfvHbo3d61mkI=,iv:Zo2B2AgX9qHJZ4yhdhhu5qs+eIYyH2De730Sw2eRnlk=,tag:RijiuSnzzz+j/WljIWyx7A==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:HQ5EjXMrs5iVQa2+VuR8BgQO2GodIFkMAa2AEtKodo3RxhrH6hpttg==,iv:ODpq0EsxTb36rIElZlu18W/ws/3OjNBZ86CuwQGprHs=,tag:BavdMI6gN74pb5zz2bKziw==,type:str]
  REGION: ENC[AES256_GCM,data:gUKbmZLUi6T2,iv:gyq8SSCZtmawbwDg+SMl2rNEV4YxWUhdN5vGW8u/BXQ=,tag:BW2os0janfkkv66AYYFdgA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWjdJd3NUQVBmSXBvWUtE
        Tk9IT1RTaEE2QlIzbWJIQzZ6RkdjdmYrelRNCkZnK3BNdTNpdXo5bGxaMnM4SlRF
        RURvb05uRlZrSVo1dlZ6YTF4anpNMlkKLS0tIE5vRW5EUjFCOWwwMy9JSSszK2ty
        bDNmVTJqMUxKRGE5MnBNWVZjZElkRHcKXSoPGfaPk8QTbLbizRHw+j+XBD2baXeC
        Im0qlm/NQ9sWTKCl+su1P4B3iwahT3du3Xh0hh2oh23TE+lc+V+fZQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-08T02:51:03Z"
  mac: ENC[AES256_GCM,data:vBfphsZY8PBqyxv0MZuL/rfcQVrJ5cLfCv/5cGGiHxYTn3hhwNAwmBXpiycAYjLVzeU5tbUSDrwNFbg05kq4s3rXEVKEholWyLUptp+GHIxv2bFa1DgHIno2e36PP4zv0Fs20dxwAiTX0nvN66vp1bUWX/obW09w9+lVpgwoNbk=,iv:yjWJIGXCwgb75da9QXSH1elKo/JPKydMUXeIeXg91tk=,tag:nAK3pCRa8IDlDeHawwNxHw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
