apiVersion: v1
kind: Secret
metadata:
  name: credentials-admin
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:0qt1pY5XdTM=,iv:5pTTy2xLTpMQRgpnLSkFmFOqEc8VAwOkyB8WoH/cL9c=,tag:Cx6pKsbRmC9ykZrXmNp2fA==,type:str]
  password: ENC[AES256_GCM,data:QxGoUTXqwfMwfMZJHXBa3CYN6iLGXFYyzgByJn+sAWndj5jm8+AAJW4rvvWIPEqq,iv:jVydv6tnC4UBBsbUEIW0Y1OOziegSk9je4QRjJiJ0Y8=,tag:yucAYLUjgWuI/8IazahN8A==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYS1JNdEM4YXJ0aXJnbWZi
        YURKSHlEWWdHaXJpTFc1NWVCa1lKakNLK2ljCmt4dnR6YVRwelhzWDBJSXluTXVT
        blZnVFVOQzgvM0FSdHB2Qkg3WHhGOHMKLS0tIDByYjF4LzlPODVLSittUFpmcWVJ
        T0JBQ05IU3gxbW9DUW1PL1g5Umo5c1kKbwvgm3odlPTzHW3VJxcO7CryKCoSxFYy
        PKp28XM3S6+ptPO+8qeCHY+sQAxsroF3dl+3B51wVeyRwVkLrLzACA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T16:42:55Z"
  mac: ENC[AES256_GCM,data:KCAHi6lDEtn7SBX4wSWolmTyoY+0sLkzyZdf3+tvL5mxOUGzaXXqDZ5Pnl3FzQK8kQjidaqeVwq0J0Q/FMc+f7qcq1Mp5aMtvXVx2q7jEo7kt+vTSsnS0Zb+wj5rr0VxK76c+h+G4BC2MKldxcX6UyvTR2qc91leZyH8xd3p46Y=,iv:5K9QNmSmYptwIXOyKmQb2jBD7Gq+4lLiOVGEvSm85FI=,tag:cwsJbR/kngjm1+GgZJ8wQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-hass
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:w0L8dQ==,iv:OMRKiSsZF46YBRbZq4+JCqcYeR01XyqqA1P0V0uuHjU=,tag:0TAWRUYJlOs3N/Z5fQM2TQ==,type:str]
  password: ENC[AES256_GCM,data:aspOTzoBWy+GG7AAm8UT/BXHt1ZavHL9AXN8r7VcMIiLZsJ7VsYOXDyuLD+Sp/L7,iv:4pJj5B6T9ePDOiO90xn77v0rPFiXVjr4/QjTb0/WOY8=,tag:bwK5dQdKyi9MYRGXAqGxNA==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYS1JNdEM4YXJ0aXJnbWZi
        YURKSHlEWWdHaXJpTFc1NWVCa1lKakNLK2ljCmt4dnR6YVRwelhzWDBJSXluTXVT
        blZnVFVOQzgvM0FSdHB2Qkg3WHhGOHMKLS0tIDByYjF4LzlPODVLSittUFpmcWVJ
        T0JBQ05IU3gxbW9DUW1PL1g5Umo5c1kKbwvgm3odlPTzHW3VJxcO7CryKCoSxFYy
        PKp28XM3S6+ptPO+8qeCHY+sQAxsroF3dl+3B51wVeyRwVkLrLzACA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T16:42:55Z"
  mac: ENC[AES256_GCM,data:KCAHi6lDEtn7SBX4wSWolmTyoY+0sLkzyZdf3+tvL5mxOUGzaXXqDZ5Pnl3FzQK8kQjidaqeVwq0J0Q/FMc+f7qcq1Mp5aMtvXVx2q7jEo7kt+vTSsnS0Zb+wj5rr0VxK76c+h+G4BC2MKldxcX6UyvTR2qc91leZyH8xd3p46Y=,iv:5K9QNmSmYptwIXOyKmQb2jBD7Gq+4lLiOVGEvSm85FI=,tag:cwsJbR/kngjm1+GgZJ8wQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-jellystat
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:alZBWPKNPlk7,iv:JkPj/nD9mUhn68DlnB5kiMQxA0FfnZOECr2eh0Jt1Wc=,tag:DfQUFz72a18vnseKslnYrw==,type:str]
  password: ENC[AES256_GCM,data:CWJRdZT9zBIOVrXoyJXxI7e8GAAyAsgiDj1QQ4Nag7VMtYF1vQRW+2D0zRmQPA9d,iv:eYum6aV/oQpKcNIulOxHLa5VDKzHrMgSTDyeTfRQ+t0=,tag:bdma+1uD0h/WH2QxkCmdxQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYS1JNdEM4YXJ0aXJnbWZi
        YURKSHlEWWdHaXJpTFc1NWVCa1lKakNLK2ljCmt4dnR6YVRwelhzWDBJSXluTXVT
        blZnVFVOQzgvM0FSdHB2Qkg3WHhGOHMKLS0tIDByYjF4LzlPODVLSittUFpmcWVJ
        T0JBQ05IU3gxbW9DUW1PL1g5Umo5c1kKbwvgm3odlPTzHW3VJxcO7CryKCoSxFYy
        PKp28XM3S6+ptPO+8qeCHY+sQAxsroF3dl+3B51wVeyRwVkLrLzACA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T16:42:55Z"
  mac: ENC[AES256_GCM,data:KCAHi6lDEtn7SBX4wSWolmTyoY+0sLkzyZdf3+tvL5mxOUGzaXXqDZ5Pnl3FzQK8kQjidaqeVwq0J0Q/FMc+f7qcq1Mp5aMtvXVx2q7jEo7kt+vTSsnS0Zb+wj5rr0VxK76c+h+G4BC2MKldxcX6UyvTR2qc91leZyH8xd3p46Y=,iv:5K9QNmSmYptwIXOyKmQb2jBD7Gq+4lLiOVGEvSm85FI=,tag:cwsJbR/kngjm1+GgZJ8wQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-firefly
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:RLqE37I8qg==,iv:EPWmOC0kWhPKR+MPF9vnoi6eIpzor9p+96EVg5QESQU=,tag:/W+Z/V9GIL2SEauDSd1RFQ==,type:str]
  password: ENC[AES256_GCM,data:x8ICbJX90PQAFyZfmn2Qkp34hm38lenSuX2rBS94oqP1nNTD8zlC3Jp+Dut5AvCL,iv:DCiWoOYhFTMKiSLda10Vax93qVY4K3wnxs0j+mKxVkQ=,tag:0pe4yKCLfwPV7Q0HAUjMgQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYS1JNdEM4YXJ0aXJnbWZi
        YURKSHlEWWdHaXJpTFc1NWVCa1lKakNLK2ljCmt4dnR6YVRwelhzWDBJSXluTXVT
        blZnVFVOQzgvM0FSdHB2Qkg3WHhGOHMKLS0tIDByYjF4LzlPODVLSittUFpmcWVJ
        T0JBQ05IU3gxbW9DUW1PL1g5Umo5c1kKbwvgm3odlPTzHW3VJxcO7CryKCoSxFYy
        PKp28XM3S6+ptPO+8qeCHY+sQAxsroF3dl+3B51wVeyRwVkLrLzACA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T16:42:55Z"
  mac: ENC[AES256_GCM,data:KCAHi6lDEtn7SBX4wSWolmTyoY+0sLkzyZdf3+tvL5mxOUGzaXXqDZ5Pnl3FzQK8kQjidaqeVwq0J0Q/FMc+f7qcq1Mp5aMtvXVx2q7jEo7kt+vTSsnS0Zb+wj5rr0VxK76c+h+G4BC2MKldxcX6UyvTR2qc91leZyH8xd3p46Y=,iv:5K9QNmSmYptwIXOyKmQb2jBD7Gq+4lLiOVGEvSm85FI=,tag:cwsJbR/kngjm1+GgZJ8wQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-immich
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:1R/CDTma,iv:57TG07/Ms8QlWrKnkAuTndshrlbgO9YytOYnLTfyjUI=,tag:o/jSRaShpANNX6KKit2s9Q==,type:str]
  password: ENC[AES256_GCM,data:qFuHE/9ggjaiRJLIivyiYR5pCS80mxZQwbQeN7cFczx4mM1mFn8OkcmgSTx0iSmN,iv:RBE3FTqixg1jwCKL3EAUrNfITStgqT8uMnN7BAif0VU=,tag:M+F4CoEcCBVDshYoOb/NwQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYS1JNdEM4YXJ0aXJnbWZi
        YURKSHlEWWdHaXJpTFc1NWVCa1lKakNLK2ljCmt4dnR6YVRwelhzWDBJSXluTXVT
        blZnVFVOQzgvM0FSdHB2Qkg3WHhGOHMKLS0tIDByYjF4LzlPODVLSittUFpmcWVJ
        T0JBQ05IU3gxbW9DUW1PL1g5Umo5c1kKbwvgm3odlPTzHW3VJxcO7CryKCoSxFYy
        PKp28XM3S6+ptPO+8qeCHY+sQAxsroF3dl+3B51wVeyRwVkLrLzACA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T16:42:55Z"
  mac: ENC[AES256_GCM,data:KCAHi6lDEtn7SBX4wSWolmTyoY+0sLkzyZdf3+tvL5mxOUGzaXXqDZ5Pnl3FzQK8kQjidaqeVwq0J0Q/FMc+f7qcq1Mp5aMtvXVx2q7jEo7kt+vTSsnS0Zb+wj5rr0VxK76c+h+G4BC2MKldxcX6UyvTR2qc91leZyH8xd3p46Y=,iv:5K9QNmSmYptwIXOyKmQb2jBD7Gq+4lLiOVGEvSm85FI=,tag:cwsJbR/kngjm1+GgZJ8wQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-backup-s3
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:0LPmrppZpryZ0CefRbwYnJ9OZNEoyF+bvsA=,iv:Y/LckZEPns78ABBdp8aBl0IxS2bhEZgq7+sAnBCrrtw=,tag:TeTMK5aqpanhVuxaEUilvw==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:IDp6eDwKxQcF2HQvOVwy/w6AGlLD3s5UpLDxmoLloDXi8wBKGMzLHf+zFk4qZUTfYuegvvYdmoYjviBV7nBygw==,iv:7u+E/Bf8JEbK94lyQKSMh4qWpalz1R5bJ5AqnfA5KOg=,tag:faOUUBvy+Ylr0Kcj2AIwrQ==,type:str]
  REGION: ENC[AES256_GCM,data:+h+c6VuWNQ==,iv:wjgXbKZBmX8SUNvvZOdpRsgeP7zg6q68tAuhVZeGKHM=,tag:kCLPJkjDbgOUPaShIrcstg==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYS1JNdEM4YXJ0aXJnbWZi
        YURKSHlEWWdHaXJpTFc1NWVCa1lKakNLK2ljCmt4dnR6YVRwelhzWDBJSXluTXVT
        blZnVFVOQzgvM0FSdHB2Qkg3WHhGOHMKLS0tIDByYjF4LzlPODVLSittUFpmcWVJ
        T0JBQ05IU3gxbW9DUW1PL1g5Umo5c1kKbwvgm3odlPTzHW3VJxcO7CryKCoSxFYy
        PKp28XM3S6+ptPO+8qeCHY+sQAxsroF3dl+3B51wVeyRwVkLrLzACA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T16:42:55Z"
  mac: ENC[AES256_GCM,data:KCAHi6lDEtn7SBX4wSWolmTyoY+0sLkzyZdf3+tvL5mxOUGzaXXqDZ5Pnl3FzQK8kQjidaqeVwq0J0Q/FMc+f7qcq1Mp5aMtvXVx2q7jEo7kt+vTSsnS0Zb+wj5rr0VxK76c+h+G4BC2MKldxcX6UyvTR2qc91leZyH8xd3p46Y=,iv:5K9QNmSmYptwIXOyKmQb2jBD7Gq+4lLiOVGEvSm85FI=,tag:cwsJbR/kngjm1+GgZJ8wQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-lubelogger
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:bZscclh0uZCzGg==,iv:7yIlNx1Uhv/fnv2pFWmzE6aPG93mnkYck8dY6FRp37c=,tag:m7u8avVTgeSfvYeVara+VQ==,type:str]
  password: ENC[AES256_GCM,data:76ddCZuQanMxpUBr+Cvm9kU3KLS0UmSPxh6I7ixYE1Bc7pIdcw5DHJ+7QLLoj/nCx6KyP/l34b2CzaVFQKrm1w==,iv:KIgrhizD9/SuOabC0l9EhIcEAI1967z/3LwPp6DpQcI=,tag:+ATKGky+IJ+fbmSJeuQciA==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYS1JNdEM4YXJ0aXJnbWZi
        YURKSHlEWWdHaXJpTFc1NWVCa1lKakNLK2ljCmt4dnR6YVRwelhzWDBJSXluTXVT
        blZnVFVOQzgvM0FSdHB2Qkg3WHhGOHMKLS0tIDByYjF4LzlPODVLSittUFpmcWVJ
        T0JBQ05IU3gxbW9DUW1PL1g5Umo5c1kKbwvgm3odlPTzHW3VJxcO7CryKCoSxFYy
        PKp28XM3S6+ptPO+8qeCHY+sQAxsroF3dl+3B51wVeyRwVkLrLzACA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T16:42:55Z"
  mac: ENC[AES256_GCM,data:KCAHi6lDEtn7SBX4wSWolmTyoY+0sLkzyZdf3+tvL5mxOUGzaXXqDZ5Pnl3FzQK8kQjidaqeVwq0J0Q/FMc+f7qcq1Mp5aMtvXVx2q7jEo7kt+vTSsnS0Zb+wj5rr0VxK76c+h+G4BC2MKldxcX6UyvTR2qc91leZyH8xd3p46Y=,iv:5K9QNmSmYptwIXOyKmQb2jBD7Gq+4lLiOVGEvSm85FI=,tag:cwsJbR/kngjm1+GgZJ8wQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
