apiVersion: v1
kind: Secret
metadata:
  name: credentials-immich
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:fEyILFAv,iv:RWWz7g1hKHyTicdnwo+KvrpxYi3iRizZnPnifT+a/rE=,tag:VcxWZ692tuT0uZBgXBFjdA==,type:str]
  password: ENC[AES256_GCM,data:G1yVmgqdnLKOFwFCqvvyNhEYlnbRF8K/xsq23NU9bYvFC9VzgollnJfvQEmPkuMc,iv:siBkydDRdvn4pFsp82bf/AzLcOLTGmnFHpCvLzmOfss=,tag:ROXlfCEEPTomryKxc+Qfhw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUTYyM0IzdFBRNEZyZC9B
        K3NLOGZvZ0lhOGgxTnZMeWZobzh6UnFzamw0Cjg0ZnA3SE1jc3pEK3BGTHhHdmFF
        aGUyWFBWZEZDcXhjcU94WjJMZFVZSW8KLS0tIFl0TWFiK2czdGVsZWxLK25SdUY5
        YnFHWUNuMlZEV283UTZ2UTFsMVA0SWMKXusrUc3y7tfHSbvoo6DJUh4xXrGVWUl5
        voQ6PXitV9cmtDTNyZmYAOmcgKJQ+jmeuuVKu+UF02DkzH9K7Zszqw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-08T02:51:31Z"
  mac: ENC[AES256_GCM,data:6PTxOc33WP6s/YVJL0hAwS3la0iY38tNOAc5kI6CbArNNoAZ4bNvcTNyu8cqbPnCy3q5OjRsSs8sqkl3nNihAd25MmsDn9llyW5efZmTAzn9DHHBGYHphg2fyWWnPK/UYVQspTdkcb4ISMmjgmnSOaJk5bpUpdPbO0jd7o+fhCg=,iv:aFiZNhbZVY2RfKMvbN41zwXoadc0mVhN3lW743Z8NyY=,tag:/LPHvmVtnbrSswCoQcBBrQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
