apiVersion: v1
kind: Secret
metadata:
  name: credentials-admin
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:BXhj68CetME=,iv:B0oTxRzgb0R2/fj96ZSzcQFc/f4yUo4ExudYMRqZk48=,tag:0sEAZOHKItRUvt2VYrW8Xg==,type:str]
  password: ENC[AES256_GCM,data:Kx/qQJ6m3vIJFURCD7sVzLimLn8/86tvxlhUJJLtMbKOjitA454pDz+Ai1/EkR57,iv:BEJyb4Ko9KOyeHsWtIcrN3nEdEd+cAfJ2ASgQu9dp/4=,tag:auyhmx01ar2E+dkfPynsQg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaERsUS9HTys3dkdOZkE1
        YXhrV0FDLzh0REFWVGpMaFhtY3U0aUlXbkVnCmE5SENVZUEvUGk3QW1YVkkzMExy
        VS9wc3JaZHdMM2xhYlB2Q0J1Mnp1MFUKLS0tIENzM25JZnZaVWZ2SE41R0ZOUzha
        MzdodGxPMkRaYWNBWnUzbWQ0bDIyemMK0fllFv82ro+uWhdo99WFu8O9QSMGhUw4
        GPOPWIH7vv/VzrD4RDP1MbBan8T5xg0PJg+afmc+qtID6vBaOVlr2Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-08T02:50:59Z"
  mac: ENC[AES256_GCM,data:DBC/Z8xHZTyqd5kT65BhMfnjC7/kTYpW+gQdOYNdaJd8lgpGbpXQ5h/Dwp6zYlcu1CVjLijYBh+kBvs6dKNf5F80YIhKfGZxpYWaz4vEag30OlnSVIDEW+aByFrWqaz5tlon3es83/sz5ktfsUZIEctsJEwgrIi4/vwDnncmoIQ=,iv:NUnolmdHQ6ALFM+EgQ1tSRZTzIDacQ4ZadiblT2eDgo=,tag:F9pIoAZwkZzcRJF5oSLtgQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
