apiVersion: v1
kind: Secret
metadata:
  name: credentials-hass
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:hPNLLQ==,iv:aK2d6aPQLMB2k0XpvyiVowvzaxzrYHt3CYIzQEO9WAc=,tag:em/N+XulcJz7YvVgoreCWQ==,type:str]
  password: ENC[AES256_GCM,data:57ViJAA8Z8YBM6AXtWAU7ngoXXNQ5Xc7gqSv5uqPzpZ6K0EuPdxoNWLm7nRsmsqk,iv:FGJan0i7Ro2nCO+iUHZTv4TuhqKqc5FXBVYn44GdYzg=,tag:aFQ+jWfql8XMOvNsQgXgWA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUW5LelZLckVPSWlyR0xN
        ekpiR1VwbnJwYWFvcUpIeW9DdFphQmJKWURFCnhMTXNjRktlVFN4bTNzSmtjY0p5
        ZnV4UGpqdTJVemJwSjFSQUQvVXZzWTQKLS0tIG16MWp3NVJiSFhwemd5VEhqU1Zm
        Q1BMQkFJRHM5Vzk5YXpTL1VVVzI5ME0KwMpo2feL+LxbOOjik5HDu4RF2jlxG33n
        FxjnKG7E/B2S2TpD57xqHRQCGpHOa14ERfb4oXTPbEVM2rJtd7QHdQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-08T02:51:22Z"
  mac: ENC[AES256_GCM,data:Weyz6sCKtiaME7Y15vcRmNSh65YaEpUQDbtfE/PgL+k6vwBgutfgcdQVEba2RslGi5R2RnWtjgeRfgTvGjg6qfooFCNi90Hl3qWSVC30GOaKHIU9P62iz/yZ1oBEL0nflIjfGm/J1qX65B2OSaQWPYz3U5yvaN/ve8W1xcdDqf8=,iv:8xqq97tGeMBMIgdWX/4zaYbk2rOlmVKP90Zh9U+/QnQ=,tag:SbSvSymO1upTegcrmNOYGA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
