apiVersion: v1
kind: Secret
metadata:
  name: credentials-buzz
  namespace: database
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:gAlEJQ==,iv:N2mDUNMBUAJsQkOIZyTgYSQ+pPwxml7i9XjDqloJhko=,tag:25f2VksYCvPxuXdDL3WZsQ==,type:str]
  password: ENC[AES256_GCM,data:XJzeFBP7mwT4XN2j4B6Wj0RDK/gU6SvYKfKHLNtHrfX5Y03dWmjoIJ//6C0uZ2EsiEzJJy0G0klBiXmMiIgERQ==,iv:YzttI1Uu7Xwpnt4FkeLvbulMqEgoo0Ef4+4+iqIg7aA=,tag:jvtnud/0hl8jmtC40Hj2PQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZlkzNWxib2pvbEVKS1hF
        S1A3QmJ0OVNnTm13YzMyMmV1ckloYk1xN0hFCjV3ekR0RDhrNDhrRi9pc1o1UndU
        eUMxdG1hVkFid0FZWDgxYUdDSXNIMEkKLS0tIGI0amRhWTZpRFFFQkovYk92cHFB
        VWRhbnZpZk9NMjFGVjBmTFFNaDFzVGMKuYN9/hUGrscj7+4A9AbTwbw4M+IaMhXw
        iIcwiCz5fkk3xKZLcafH3d9Ez/X+TZ/SfNGtq5x6ZNPYL9C8FuL/xQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-29T16:54:50Z"
  mac: ENC[AES256_GCM,data:Oyt3PZdukPhIzXAT3coShM4psZ82gLICTd9LvGmr7CyyXB1aRJRTFv1MYLLmD6tacZxfF536YDMauZR7yPk2f800GX1boPzlXUbra2lV54yFIR9dZXMVTQM1o+6dZkc1Q3wF1U1uWnDnEPN8aDxm+NNe8SXp0FK7IBSe5Vp0vjY=,iv:19oFLAnQ/UeN17Vq6CV/Pm4DV7SuFWnHro8LRjIi1sQ=,tag:YrBPMPQ0uetfhpffgnPWpw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
