apiVersion: v1
kind: Secret
metadata:
  name: credentials-firefly
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:7H36C1wj0g==,iv:JNB6VNgZL3l0xr8QZ2PXDd/8lZ7xbw4gsuF39LSiyWA=,tag:zUm58ejnuH1/4UnC+9zEFw==,type:str]
  password: ENC[AES256_GCM,data:cTqSWEuniFbz+yzAx19+o7n5+xACuQ2FmhR7LCHMriXGpSwcvTzMhdJr4R8q18rN,iv:FncIrPPybR8JreqqFgv/nPg9cxku17Q8VtlW1qh1vSs=,tag:wmfRFPPw63DFrkZ1YLqHWA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqODRCckNicGI4dFViUlFW
        VFFsQjJHTXlTNEdUa3p5Zis5RmYyMWtmTlRBCk9yTjI4ODFFa0dPbEFQR3IzZWdo
        dUNaenhYZDFzT3RDTjFrdzQwTmEvUVkKLS0tIDhBMmpUWURBcUUwd0w0U1Ewdldk
        S2I1OTJnMmU0SEdpTEQxbTlOKzNXWjAKOjCieTm0dqRNFQU9Z6aSJRIorQWrcr57
        3kEpjJL76lb1gkuy7uOfwW05e6yw51KS+oarse8hDYDQ8/8RAeUbNg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-08T02:51:16Z"
  mac: ENC[AES256_GCM,data:16V0d+s/Tp0Er4PjHTutCcb543COBOyiTsJwvMk001dzhVb+eBVKS5kAJiKTMTquKJH5RoWws3FcFwJ7xCbk1dIDGWNtHny8zDLlB3ExrQtC8NMuAv12p8tw+2JF8A/GYSoHzk3KVqI1Kuofso6U1iyhCBPzqEPXRdp4ticL5VE=,iv:w0bLP2REuf9aiUmzAuecx1xgDoDRk6gW0cMQ85XdQuo=,tag:g5kP07lUa8tj41nYGk/K6w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
