---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./credentials-admin.sops.yaml
  - ./credentials-backup.sops.yaml
  - ./credentials-buzz.sops.yaml
  - ./credentials-firefly.sops.yaml
  - ./credentials-hass.sops.yaml
  - ./credentials-immich.sops.yaml
  - ./credentials-jellystat.sops.yaml
  - ./credentials-lubelogger.sops.yaml
  - ./objectstore.yaml
  - ./scheduledbackup.yaml
  - ./podmonitor.yaml
