apiVersion: v1
kind: Secret
metadata:
  name: dawarich-secrets
stringData:
  DATABASE_USERNAME: ENC[AES256_GCM,data:rlpWdkWnYvM=,iv:buTgoa2cCS/yNkxMSZYFh/b8eAhuFYVuk3eCuJEnUKc=,tag:9f6sK+MtG/g7zfOlKRgCzg==,type:str]
  DATABASE_PASSWORD: ENC[AES256_GCM,data:yk5q+dKTfjDhpGlcUmb5Qa2tiyXKckdbwhCyJTyuVyRi/4RXmonvw+lPMNdi39diz0GVVrZZDFyVO3imgd6qaA==,iv:vvwPZ/qzY16MNypLvLa+nQcm8sI6OM6yM0gtAEmyst8=,tag:/QJj3mwxjknqCxMQQ4GBeA==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:tdRhXixMSi6711w4dhJbAsn8ZE3pLjYPUwf1LcW1XGf8/l5jc2NNq3qkeQBy71sHuYd2LUjZTpGQTo891cyvEJtqeRjCrSl0ePuKqEVxLHyqHFI4z3YBDLhH4e5lz6Gskta2vagwVahACES9x1BXtVebA6TizS3m3TCa,iv:ETysYekWmwLTIFFl4ED6Q0yFg8YAewx91LutyjCKQCs=,tag:UZcsSy6gVm4BEPFnHqw0xw==,type:str]
  SECRET_KEY_BASE: ENC[AES256_GCM,data:5yH9Un4ug15ItmuOgMesuJzxZkEDhaxowH+mhlV7M9jhuPhhymcviYhqyzu6t65iyuspiJslkSn3bcfWcWzLx5SgD2aIA7KqPwKT9BXu+KDOGjgK2yxhEg3H3cu2Y0K2brb6SNIqgfAjlTOF0/yrO5dhgPJ4oyLQRLmYWuOpx7o=,iv:VIklYGmi9zyBOIWVSo1WeQqnpnBPgeH6FyUz1ZyAbnw=,tag:exkKUrEGA1we9fev6WxrGQ==,type:str]
  METRICS_USERNAME: ENC[AES256_GCM,data:+cRnIh6s3w==,iv:ejaybr29UqmJhO/mW2l711X9TVS6UFv5G4UPoPf8jC8=,tag:+UoXLXf/qaiE3CpMVIRtEw==,type:str]
  METRICS_PASSWORD: ENC[AES256_GCM,data:/xG3TSmFwA==,iv:L8X+XxDoX7IyMtA7/2uvUB5jeWYDkzCMA/x40CXS6IE=,tag:uUEOBpGc6j+wYH6RxfTJeA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Gkl0CzPW+KZmdntKcP/WQNYpkCZdPDNV79ZBPnWkJXJxu1ResYsIZK6MDkG9c18XvHmey+EFtVGe2oy0v4s6pI0PDqwLDsRuTHWe0sQ2YSnWPBLxm+xoPCO4dO7tJhJmdY7to5uMMoJl7gQupThZYjn3tKmk6zyRpPnPKS69pYg=,iv:QcHOerClhMF9UGZjH9BGb/g5Gyn5TvW2FbsII09DYWU=,tag:keTA9p3aLSiqwQe3ZGqjFg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdEo2SytOeFJnMWY2SWU1
        S3NrdTl4Sm5BZmQzcUkyUy9rRlhONDVoM1RrCktlWFFQbU9hMVdSSWN5ZWtZelR5
        WFJEZXEvWW4rUFdLRlh5Vm1qSG5ZWWMKLS0tIC8ycExWUGVLZkZabzJVNndyNnV5
        elBVZ1lIeUsybzhjblNRbS8yY2VZa0UKr+762yFJpxMRZcEn+QDlyOHPBLkZb4FB
        shEpFU5GXQHwIoVeEYoA+6vqRZmd74hEAxpVPJF7AVfOk9XrI+MjNw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T01:49:54Z"
  mac: ENC[AES256_GCM,data:n9SrlQyafkSR0vcy6QQOlfvNlOdUqj6oi5xkXhaGRWwUCi8dOCS+te/9UF/kj7zsmy/0/uNezxlDOFqziujIa3HPbaNVR3wbXGOXj0aRZQL5XKkDseDNfZ/6vNEubUGeFxVvKukbrtES2K8Aki5NvdOe+BIsDF2IOLni8vnX0bE=,iv:vCq5+wW9Kp8za9DJJjRFwttpMcT9QmjWxtQ58ayrCxg=,tag:ynfDqoWFBjDVURRtQ2s1yg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
