apiVersion: v1
kind: Secret
metadata:
  name: dawarich-secrets
stringData:
  DATABASE_USERNAME: ENC[AES256_GCM,data:rlpWdkWnYvM=,iv:buTgoa2cCS/yNkxMSZYFh/b8eAhuFYVuk3eCuJEnUKc=,tag:9f6sK+MtG/g7zfOlKRgCzg==,type:str]
  DATABASE_PASSWORD: ENC[AES256_GCM,data:yk5q+dKTfjDhpGlcUmb5Qa2tiyXKckdbwhCyJTyuVyRi/4RXmonvw+lPMNdi39diz0GVVrZZDFyVO3imgd6qaA==,iv:vvwPZ/qzY16MNypLvLa+nQcm8sI6OM6yM0gtAEmyst8=,tag:/QJj3mwxjknqCxMQQ4GBeA==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:tdRhXixMSi6711w4dhJbAsn8ZE3pLjYPUwf1LcW1XGf8/l5jc2NNq3qkeQBy71sHuYd2LUjZTpGQTo891cyvEJtqeRjCrSl0ePuKqEVxLHyqHFI4z3YBDLhH4e5lz6Gskta2vagwVahACES9x1BXtVebA6TizS3m3TCa,iv:ETysYekWmwLTIFFl4ED6Q0yFg8YAewx91LutyjCKQCs=,tag:UZcsSy6gVm4BEPFnHqw0xw==,type:str]
  SECRET_KEY_BASE: ENC[AES256_GCM,data:5yH9Un4ug15ItmuOgMesuJzxZkEDhaxowH+mhlV7M9jhuPhhymcviYhqyzu6t65iyuspiJslkSn3bcfWcWzLx5SgD2aIA7KqPwKT9BXu+KDOGjgK2yxhEg3H3cu2Y0K2brb6SNIqgfAjlTOF0/yrO5dhgPJ4oyLQRLmYWuOpx7o=,iv:VIklYGmi9zyBOIWVSo1WeQqnpnBPgeH6FyUz1ZyAbnw=,tag:exkKUrEGA1we9fev6WxrGQ==,type:str]
  METRICS_USERNAME: ENC[AES256_GCM,data:+cRnIh6s3w==,iv:ejaybr29UqmJhO/mW2l711X9TVS6UFv5G4UPoPf8jC8=,tag:+UoXLXf/qaiE3CpMVIRtEw==,type:str]
  METRICS_PASSWORD: ENC[AES256_GCM,data:/xG3TSmFwA==,iv:L8X+XxDoX7IyMtA7/2uvUB5jeWYDkzCMA/x40CXS6IE=,tag:uUEOBpGc6j+wYH6RxfTJeA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdEo2SytOeFJnMWY2SWU1
        S3NrdTl4Sm5BZmQzcUkyUy9rRlhONDVoM1RrCktlWFFQbU9hMVdSSWN5ZWtZelR5
        WFJEZXEvWW4rUFdLRlh5Vm1qSG5ZWWMKLS0tIC8ycExWUGVLZkZabzJVNndyNnV5
        elBVZ1lIeUsybzhjblNRbS8yY2VZa0UKr+762yFJpxMRZcEn+QDlyOHPBLkZb4FB
        shEpFU5GXQHwIoVeEYoA+6vqRZmd74hEAxpVPJF7AVfOk9XrI+MjNw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T20:55:41Z"
  mac: ENC[AES256_GCM,data:Z9JgFT6cCvgBw8d/+6UcpVJWe59jvDRXbfRrnGeDjmt3AKhr3AIxtF+VDFkoQMvy8Rp2kJwk4tKxjS+P3MDozZWiBoxlU8i/Ld1ta/eHupZbeLLKVE+5YISYgQwS0oB8TDG6x7XQ6IGCfl6ovf1VuH5DGC2hVht/G8quWUpA2Ok=,iv:DBRg+1qdLfxxL1/tYuf3xQhaOsWHT1aLXutXOvNTyGk=,tag:kYPrNoYSCP77JAnRlbxD3A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
