---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dawarich
  labels:
    monitoring: otel
spec:
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
      basicAuth:
        username:
          name: dawarich-secrets
          key: METRICS_USERNAME
        password:
          name: dawarich-secrets
          key: METRICS_PASSWORD
  selector:
    matchLabels:
      app.kubernetes.io/instance: dawarich
      app.kubernetes.io/service: dawarich
  namespaceSelector:
    matchNames:
      - dawarich
