---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hajimari
spec:
  interval: 30m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    hajimari:
      title: Hajimari
      darkTheme: "chalk"
      alwaysTargetBlank: true
      showGreeting: false
      showAppGroups: false
      showAppStatus: true
      showBookmarkGroups: false
      showGlobalBookmarks: false
      showAppUrls: false
      defaultEnable: false
      namespaceSelector:
        any: true
      globalBookmarks:
        - group: node
          bookmarks:
            - name: GitOps
              url: https://github.com/npawelek/home-ops
            - name: Firmware
              url: https://github.com/npawelek/firmware
            - name: Renovate
              url: https://app.renovatebot.com/dashboard#github/npawelek/home-ops
        - group: network
          bookmarks:
            - name: UniFi Network
              url: https://udmp.${SECRET_DOMAIN}/network/default/dashboard
            - name: UniFi Protect
              url: https://udmp.${SECRET_DOMAIN}/protect/dashboard
            - name: UDM-Pro
              url: https://udmp.${SECRET_DOMAIN}/settings/updates
        - group: storage
          bookmarks:
            - name: Synology DS1512+
              url: https://derpnas.${SECRET_DOMAIN}:8079
            - name: Synology RS1221+
              url: https://racknas.${SECRET_DOMAIN}:8079
        - group: miscellaneous
          bookmarks:
            - name: HyperHDR Samsung 55
              url: https://hyp-samsung55.${SECRET_DOMAIN}
            - name: Octoprint
              url: https://octopi.${SECRET_DOMAIN}
            - name: Valetudo (Rosie)
              url: http://192.168.10.145
            - name: Valetudo (Floofeater)
              url: http://192.168.10.146
            - name: HDHomeRun
              url: http://192.168.20.98/
      defaultSearchProvider: Kagi
      searchProviders:
        - name: Kagi
          token: k
          icon: simple-icons:keras
          searchUrl: https://kagi.com/search?q={query}
          url: https://kagi.com
        - name: DuckDuckGo
          token: d
          icon: simple-icons:duckduckgo
          searchUrl: https://duckduckgo.com/?q={query}
          url: https://duckduckgo.com
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          # This should be the in-cluster DNS name for the authentik outpost service
          # as when the external URL is specified here, nginx will overwrite some crucial headers
          nginx.ingress.kubernetes.io/auth-url: |-
              http://ak-outpost-authentik-embedded-outpost.auth.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          # If you're using domain-level auth, use the authentication URL instead of the application URL
          nginx.ingress.kubernetes.io/auth-signin: |-
              https://hajimari.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
              Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
              proxy_set_header X-Forwarded-Host $http_host;
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
          hajimari.io/enable: "false"
        hosts:
          - host: &host "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-settings
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M
