apiVersion: v1
kind: Secret
metadata:
  name: fireboard2mqtt-secrets
stringData:
  FB2MQTT_FIREBOARDACCOUNT_EMAIL: ENC[AES256_GCM,data:+6TP/euoKBWFNUwMYbIlIv13XQMi+PlT,iv:RdcUuAhaXNblTY2fSnbaFvDsfzia6eFk+JG4MubjE1M=,tag:J7fN0h37Jx8OhftsSIYODQ==,type:str]
  FB2MQTT_FIREBOARDACCOUNT_PASSWORD: ENC[AES256_GCM,data:FwQt7fdMq9/kerlSwSFwGK6UouqdnuVovGqGCWa3oI4=,iv:9VRqM/RclJ8MvyDBpChXkfCgZqC/n0yyXGtxiDGqlNc=,tag:uc+U5vOM8JQa9MaKK2xOog==,type:str]
  FB2MQTT_MQTT_URL: ENC[AES256_GCM,data:vVxprF5OgqAmqoDsPlKf2GneSjpxB/vO003lYEm0CXZLjA==,iv:GRlNaJHoaqo1UdxZ9gTC8jEYu8t+zJC9mFpLGpZJIPI=,tag:FT/AonR9Yc3a/Huc+hBPHw==,type:str]
  FB2MQTT_MQTT_USERNAME: ENC[AES256_GCM,data:ItG5,iv:hxpU0aQKTD/0wX5oOE6kd53hYEPgyy+c2ngi4Q1c148=,tag:Gy2AyYyTakFnG2u9ZUesnA==,type:str]
  FB2MQTT_MQTT_PASSWORD: ENC[AES256_GCM,data:08TBd6UKRQWt3vAkcPTInG4iDTuMP9aci5O0X80eND0=,iv:4azGuQTKrJ9MOVlKIIBNLuicj/uIFltl+pPlMUrQLJA=,tag:gDAgOf5C/z0kJDSsbVGZxg==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cTRQT0RvVXZ1THk5NVJL
        R1BNZjFxQVNBbVhHL1EvZ0xWV01Rb0Y5Y1dzCjg2bFNRa211WVE3SVA4M1Qzdytr
        WU1BT250VXlWa2N6b3lwYW1qRHk2MFUKLS0tIHRlRmJHVENESE52QWJEQUMwRFdU
        NnRsdFYzKzhkWlpFUW9zdWhCVm1qa28KqMKRO0sOctSebjRA6jKNtETfmRITfo5O
        7guyvVVh6chl8XJ6WHLhTYd89ba341uBGaRYP5nyh+tJcg69E30VhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T15:44:48Z"
  mac: ENC[AES256_GCM,data:TENqRQhtYPpAl4mEUC3EafSneuuJpM82KzmdGhWen9MpNrp9XlPIaQtOEzslTm7s0PzYwQv/5iFkdM7Twu5TdYKe8c9ST7o9y8cFpQMoJ+A8DqWXJ55gaqP2RWIFJZrDhfG/JJ/yE5iWRWR98TtfN0ugd/BBtEvh6ibTexMAq+Y=,iv:vjF+4fJx/QDe4fUJ60shCzKWiDPY9QuS7QEyaOSQ/Tc=,tag:SEKLLW0+pzzS54xvxbSfkg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
