apiVersion: v1
kind: Secret
metadata:
  name: copilot-secret
stringData:
  GH_TOKEN: ENC[AES256_GCM,data:OThouG70VJioPlEV7xuFAzWI7r+XOm8UWfC42T+vQIEiE2BJzHKWig==,iv:+YbiJyEgCuQEulHVjkMHYuDMCPHjLoGfYzqZ97QLbFg=,tag:Pf9M6awHJOc598FRVdp6pw==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVWtKNmozb2tuNU8rMmo5
        RlVaLzFZNGU1Y2ZkQkY1c1ZBM3ZudWVaZ2tRCnlkbWdPbm9mNHdxRWpsbm5rR3ZB
        eXJZdDdHYmxob0NPazJFbHNvdHk1ZTAKLS0tIGdSK2NGK2txeXdjaW9pK1BFZmVp
        dDNEUm9PTCtHT2NoNTM4SkE0NDhaaUkKz41A0I6GSLg1uBjmfYZoIK85vVM7sAsa
        DZ34N2vincKRyqg0JTeAdERMhVLoStawJTOLmk1VKRgfY8YZsx5YOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T04:33:22Z"
  mac: ENC[AES256_GCM,data:BCyV7+tiM+4LTvUp5mXgietD3xZG7EvSau+2Si5HwmH/0B7A47XYs/wDYsuBD2uQt3H/KWLKNiJpkTTeY6H/cUAM7q7S5lrL9ixEGrBWxdbf4ephK6m8QGsExg1Isy9JkAUBHT2yxvAfN1bvJT46JcIxBBt75pbv55cRzq+rn/M=,iv:S4g0oM3izHY6yFCbuqp9Csz0grHYepBXGIMsV+/FdxM=,tag:itF6C6Vvde8Kz6ivsjiFlg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
