apiVersion: v1
kind: Secret
metadata:
  name: copilot-secret
stringData:
  GITHUB_TOKEN: ENC[AES256_GCM,data:rQhJwHAn/2niitOuFC4KARO2c+Qg5TdEPshzGqKrXVsD68ZgVqRy/w==,iv:dNzUmqZvnE+DFKQ07mT37b6209ZPZ+Qk0e2j5Fz3qfI=,tag:CFCYEquQQa6ROClW+12wzA==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZkxyTVkrbVpLUEJnaE5n
        ZXplNm1IQWlYK0k1RDFveThsODNBSVlGakQ4CmhvKzJCdHMyaEg1bFVldVFOUjRH
        UFZnaGJyWUY2aC9mQXVYbHpaZkpXK0EKLS0tIGNucC9iVU1ib0JQcjlscGF2WXJs
        NkFBYVV5N200Nmh4bEVNQVg5VWNnUVkKwxH0zdh/0C3VaNElm3/1H/Tg8NQ/hsNd
        7doNa4rkWPB/flFgtor9dojPD6cYhTTQoj2Fo71uLZFmf2KbwWB/3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T04:18:35Z"
  mac: ENC[AES256_GCM,data:uzkkwDC11zgYYDpxz6FUy/Vy6hgH6UciOTAWF2aCKurJqv0uzUyrzNBXe5dt7cqTiJ8FViFm6td734GG+j0dJx5OSnP0lKerdrpE34lenMOSEA09ZnUTPedy18iSMvEUhHcNB2L4o/kHGfaqd+Aa5yzQb9o/pwKNqnZXz3wl7vU=,iv:U4sqQ+TooQTGrVE0m0+YM7jtrwU+3GoI9wi+2Cgp4gs=,tag:vrNERo58i4KEZgr0xmqWtg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
