---
name: "Lychee"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

env:
  WORKFLOW_ISSUE_NUMBER: 1061
  ISSUE_LABEL: lint/lychee

jobs:
  lychee:
    name: Lychee
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Scan for broken links
        uses: lycheeverse/lychee-action@c3089c702fbb949e3f7a8122be0c33c017904f9b # v1
        with:
          args: --verbose --no-progress --exclude-mail './**/*.md'
          output: /tmp/results.md
          labels: "${{ env.ISSUE_LABEL }}"

      - name: Update Issue
        uses: peter-evans/create-issue-from-file@24452a72d85239eacf1468b0f1982a9f3fec4c94 # v5
        with:
          title: Link Checker Dashboard 🔗
          issue-number: "${{ env.WORKFLOW_ISSUE_NUMBER }}"
          content-filepath: /tmp/results.md
          labels: "${{ env.ISSUE_LABEL }}"
