apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secret
stringData:
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:oCr4iM4cdkm7T0wg+ndcx4r3JFDgN/euaaIbgfWAUR3dB3AZpVZUzMcMxeFFY3Y9,iv:+4i+TLkh0sqHkM9PIq9eBUFZalaUD2H4LE+dUabdeyM=,tag:SwLiILAU8bA0AC+EdYvB3Q==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:+K2SdaVGAGFipIx69p6Ly+bM8QggBdqcqG4WRSnxs3xAXgrLBICf3RrihtVNjQquJwNk14+HgfS+YC0JfspDfK290C/8XJeAurwkDAf2YStjj07igjfqXJr3zGS1mN5219orDRDPH8V6dgPqLLfYhIZxljziTJukp8Blpe/bhKo=,iv:gu6nlGl2QZN3ki5OAqi0AL3BXo5R/Ox9vGPuJ/1oK9I=,tag:TmHjeH4HMOoYdJHrUAHpYQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqM1hRK05sNGdZNFJKZnQ1
        K1VPa2ZpWU1lMWRCYndnWXMwVjltcGNCUG5NCmVJdnRYa0Y2QmhFU2xqUjNRZ1Vs
        OTJnTWpMYUwxSG94V2tiYW1helF2RFEKLS0tIDFHWWRGU0VWN3FZdWd1VVFSa3kz
        ekhtRThCQndOWXRIaUpPWXhtTmhSeGcKPl/vBase+oAFPoZw8o/xbfswyAD4y+Rn
        yfn72glzC1DAz4RZSUql0Csyq+apwMsQun4+spQyxIum6D6P0A4ozw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T21:54:45Z"
  mac: ENC[AES256_GCM,data:zUjfMEuRCi1bueVlsJphpbPfmasjKETnPy2x5WsIjkpohHRvOtaMHN9Fw/c6JurnOuhZEpn+IacS3aurOnBCCaydB0TcVLWAao1l3RK4m7+lxN+gYSNOzSGyBZ3peQ4okmyNKlRhbmR27AJJBHVvf8TtwqSQagel84vDT72UhvE=,iv:oRUraFmZwVCEn0fOI7I12esuaOoyjrmbYczSlexKPYc=,tag:pbquJvirDPKdGhJu1qTPLg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
