---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./nfs-volumes/ks.yaml
  - ./nfs-pvc/ks.yaml
  - ./garage/ks.yaml
